pkg/apis/provisioning/v1alpha5/labels.go

Surfaces two new labels/tags that are used for tagging cloudprovider infrastructure resources
```yaml
tags:
karpenter.sh/discovery: $CLUSTER_NAME
karpenter.sh/managed-by: $CLUSTER_NAME
```

chore: Create Karpenter generic infrastructure tags

---

go.mod
go.sum
pkg/webhooks/webhooks.go

- Fixes broken `webhooks` package by using the default knative config for observability
Webhooks were broken by [this change](https://github.com/knative/pkg/pull/2610) which uses default as `nil` instead of an empty ConfigMap. This causes the process to crash.

bug: Fix Broken Knative Webhook

---

pkg/operator/operator.go
pkg/operator/options/options.go

- Fixes a bug where `docgen` was no longer working because `MustParse()` was moved inside of `options.New()`

fix: Move `MustParse` call out of options.New()

---

pkg/test/settings.go

- Makes the `test.SettingsStore` a map of `map[ContextKey]SettingsData` so that testing can inject whatever settings should be injected into the provisioner

test: Introduce a more robust way to do settings store test injection

---

pkg/apis/apis.go
pkg/operator/operator.go
pkg/utils/sets/sets.go

- Moves settings initialization up a level so that we can initialize settings that are not available in core
- This means that other packages will call `apis.Settings.Insert()` to insert settings into the global context on intialization

chore: Move `config.Registration` to Global Level in `apis.Settings`

---

pkg/controllers/provisioning/batcher.go
pkg/controllers/provisioning/provisioner.go
pkg/operator/controller/singleton.go
pkg/test/expectations/expectations.go

- Fix the time when settings are injected so that we perform `settingsstore.InjectSettings()` after we get a call to trigger the batcher. This will evolves into an abstract `WaitUntil()` mechanism for the `singletonController` which will wait before each call to `Reconcile()`

fix: Inject settings after the batcher completes waiting

---

pkg/cloudprovider/types.go
pkg/operator/operator.go

- RESTConfig was not being properly injected into cloudprovider context to `getCABundle`
This was broken starting in #29 

fix: Fix REST config injection

---

go.mod
go.sum
pkg/controllers/metrics/state/controller.go
pkg/operator/controller/singleton.go

- Automatically inject reconcile duration into singleton controller

chore: Automatically inject `reconcile_duration` and `reconcile_errors` into singleton controller

---

pkg/test/provisioner.go

- Injects the test discovery label into nodes created by the provisioner

test: Inject discovery label into node labels

---

pkg/apis/provisioning/v1alpha5/labels.go
pkg/apis/provisioning/v1alpha5/register.go
pkg/test/metadata.go

- Allow testing group `testing.karpenter.sh` to be used in testing code

test: Allow testing label domain

---

pkg/apis/provisioning/v1alpha5/labels.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/fake/instancetype.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go

Changes all instances of `"linux"` to `string(v1.Linux)` and instances of `"windows"` to `string(v1.Windows)`

chore: Use v1 operating system strings

---

pkg/operator/operator.go
pkg/operator/options/options.go

__BREAKING CHANGE: Integrating this new code in upstream `aws/karpenter` will break customers who were using these CLI args__
- Removes the AWS-specific options to prepare migrating the options into the ConfigMap

chore: Remove AWS options from CLI args and Env Vars

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/node/emptiness.go
pkg/controllers/node/suite_test.go

- removes duplicated deprovisioning logic used for emptiness. `node/emptiness.go` and `deprovisioning/controller.go` were both executing deletion logic. 
- moves respective tests over

fix: move emptiness tests to deprovisioning and deduplicate deletion logic

---

pkg/apis/config/registration.go
pkg/apis/config/settings/settings.go
pkg/apis/config/settings/suite_test.go
pkg/controllers/deprovisioning/suite_test.go
pkg/operator/controller/suite_test.go
pkg/operator/operator.go
pkg/operator/settingsstore/fake/settings.go
pkg/operator/settingsstore/settingsstore.go
pkg/operator/settingsstore/suite_test.go
pkg/test/settings.go

Fixes # 
SettingsStore configMaps should be required. This PR ensures there is no default settings that are set by the ConfigMapInformer but instead we wait for the creation of all configMaps before we continue to watching the configMaps.
- Manual deployment of new version to EKS cluster

chore: Wait for ConfigMap creation for SettingStore watcher

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/termination/suite_test.go
pkg/controllers/termination/terminate.go
pkg/utils/pod/scheduling.go

Fixes # 
[#1532](https://github.com/aws/karpenter/issues/2391), [#2391](https://github.com/aws/karpenter/issues/1532)
This reverts a change made in a [previous PR](https://github.com/aws/karpenter/pull/2092) to prevent a node from being terminated if a pod without an ownerRef is encountered ("naked" pod).  Per Kubernetes documentation, the use of naked pods should be avoided if possible and Karpenter should reinforce that recommendation.  There should be no assumption of reliability or stability when naked pods are used given an involuntary node interruption can cause the pod to go away and not be recreated.  Karpenter users should be aware of how naked pods are being used in their clusters and define how evictions should be handled on each pod.  Users can prevent naked …

BREAKING CHANGE: Evict pods with no ownerRefs by default

---

pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/node/initialization.go
pkg/controllers/node/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go
pkg/test/nodes.go

Fixes # 
Uses `.status.allocatable` and `.status.capacity` values immediately when they are set vs. waiting for node initialization

fix: Wait on `.status.Capacity` and `.status.Allocatable` in Initialization

---

pkg/controllers/controllers.go
pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/pdblimits.go
pkg/controllers/inflightchecks/controller.go
pkg/controllers/inflightchecks/failedinit.go
pkg/controllers/inflightchecks/nodeshape.go
pkg/controllers/inflightchecks/suite_test.go
pkg/controllers/inflightchecks/termination.go
pkg/controllers/node/initialization.go
pkg/events/events.go
pkg/test/eventrecorder.go

Report as events and logs the reasons why a node is stuck terminating or  failing to initialize.
Fixes  https://github.com/aws/karpenter/issues/2829
Unit testing & deployed.
Sample log:
```
karpenter-74bdb86d9c-kc77c controller 2022-11-10T15:56:42.861Z	INFO	controller.inflightchecks	Inflight check failed for node ip-192-168-85-164.us-west-2.compute.internal, Can't drain node, pod default/my-shell is not owned	{"commit": "f691533-dirty", "node": "ip-192-168-85-164.us-west-2.compute.internal"}
```
Sample event:
```
51s         Warning   FailedInflightCheck             node/ip-192-168-85-164.us-west-2.compute.internal    Can't drain node, pod default/my-shell is not owned
```
There is some duplication here as we also report failures to evict. I …

feature: add inflight checks to detect some configuration issues

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptiness.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/types.go

Fixes # 
This simplifies the deprovisioning interface by pulling out out some of the consolidation specific details from the interface.
This also fixes a bug introduced where the Consolidation TTL wasn't considered for empty nodes, resulting in cases where empty nodes would get more aggressively terminated. 

chore: simplified deprovisioning interface

---

pkg/controllers/provisioning/provisioner.go

Fixes # 
- Fixes a structured logging panic when the node has an error creating (Causing failed tests here https://github.com/aws/karpenter/pull/2883)

fix structured logging panic

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/provisioning/provisioner.go

Fixes # 
Consolidation used to be primarily triggered when there were no pending pods. Since this is no longer the case, we need to treat all pending pods as part of the consolidation solution to avoid prematurely consolidating.
Unit testing & deployed to EKS.

fix: track pending pods when consolidating

---

pkg/controllers/deprovisioning/controller.go

Fixes # 
- Removes duplicate log in deprovisioning reconciler (also not formatted properly)
```
2022-11-18T08:41:47.704Z 2022-11-18T08:41:47.701145575Z stdout F         2022-11-18T08:41:10.226Z       ERROR   controller.deprovisioning       processing cluster, %!w(*fmt.wrapError=&{determining candidate nodes, listing instance types for browplaid-2-qbupxthidb, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws "stingerwool-1-gxudy64fsb" not found 0xc0010edfc0})     {"commit": "f290d37"}
2022-11-18T08:41:47.704Z 2022-11-18T08:41:47.701147825Z stdout F         2022-11-18T08:41:10.226Z       ERROR   controller.deprovisioning       processing cluster, determining candidate nodes, listing instance types for browplaid-2-qbupxthidb, getting providerRef, …
```

chore: remove duplicate err log in deprovisioning reconciler

---

pkg/apis/apis.go

Fixes # 
- Fixes `go generate` so that it generates the `zz_generated_deepcopy.go` file
`go generate ./...`

fix: Fix go generate to generate deepcopy

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/fake/instancetype.go
pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/multinodeconsolidation.go
pkg/controllers/deprovisioning/singlenodeconsolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/inflightchecks/failedinit.go
pkg/controllers/inflightchecks/nodeshape.go
pkg/controllers/node/initialization.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/node.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go
pkg/scheduling/nodetemplate.go

Fixes # 
- Converts `InstanceType` interface to struct so values will be stored statically
- Expands instance types to expose values for default `kubeReserved`, `systemReserved`, and `evictionThresholds`

chore: Convert `InstanceType` interface to struct 

---

pkg/controllers/inflightchecks/controller.go
pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/provisioner/controller.go
pkg/controllers/node/controller.go
pkg/controllers/state/provisioner.go
pkg/operator/controller/typed.go

Fixes # 
- Adds object key to the typed controller in logger
`make apply`

chore: Add object key to Typed Controller in logger

---

.golangci.yaml
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/test/provisioner.go

Fixes # 
- Fixes missed changes in scheduling profiling file
- Adds the `build-tag` to the linter to catch misses in this file in the future

fix: Fix bugs/missed changes in scheduling profiling

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/node.go
pkg/controllers/state/pod.go
pkg/test/expectations/expectations.go

Fixes # 
dynamically update cluster state, rather than waiting for sync
Remove the special testing flow in the provisioner and more accurately model cluster state during tests.
`make test`

chore: dynamically update cluster state, rather than waiting for sync

---

pkg/controllers/provisioning/suite_test.go
pkg/controllers/provisioning/volumetopology.go
pkg/test/expectations/expectations.go

Fixes [#2971](https://github.com/aws/karpenter/issues/2971)
Node selector terms are OR'd together, so our relaxation removes them one at a time when we are unable to schedule.  This change ensures we add the volume topology zone requirement to all terms instead of just  the first one so the relaxation process won't remove it causing us to think a pod will schedule, when it won't.
Unit testing & deployed to EKS.

fix: add our volume selector zone requirement to all terms

---

.github/workflows/presubmit.yaml

chore: remove K8s 1.20 from CI

chore: remove K8s 1.20 from CI

---

pkg/apis/config/settings/settings.go
pkg/apis/config/settings/suite_test.go
pkg/apis/v1alpha5/labels.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/suite_test.go
pkg/metrics/constants.go
pkg/test/settings.go

Fixes # 
This adds the drift deprovisioner that allows cloud provider controllers to implement the IsNodeDrifted function, and label nodes with `karpenter.sh/node-drifted: true` to deprovision nodes when they don't match provisioning specifications.
This also adds a feature flag in the global settings configmap to enable drift. It is disabled by default.
- make apply && make e2etests

feat: added drift deprovisioner

---

pkg/controllers/deprovisioning/reporter.go
pkg/test/settings.go

Fixes # 
- Reduces scheduling test time by dropping batching window for tests

test: Reduce test time by decreasing batching window

---

pkg/operator/options/options.go

Fixes #127 
Change env variable `PORT` -> `WEBHOOK_PORT` as it is described in the docs

rename env-variable PORT to WEBHOOK_PORT

---

pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/utils/atomic/lazy.go

Fixes # 
```
// Continue to requeue until the pod is no longer provisionable. Pods may
// not be scheduled as expected if new pods are created while nodes are
// coming online. Even if a provisioning loop is successful, the pod may
// require another provisioning loop to become schedulable.
```

fix: Retrigger provisioning until all pods are scheduled

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/termination/terminate.go

Fixes # 
- Use a machine generated from a node for termination

Use a machine generated from a node for the termination loop

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go
pkg/controllers/metrics/provisioner/controller.go
pkg/controllers/metrics/provisioner/suite_test.go
pkg/controllers/metrics/state/suite_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/termination/suite_test.go
pkg/test/expectations/expectations.go

Fixes https://github.com/aws/karpenter/issues/3064
- Delete events were being ignored for the two metric state controllers as a result of https://github.com/aws/karpenter-core/pull/51

fix: Fix bug where metric gauges are not deleted on pod/provisioner delete

---

pkg/operator/controller/typed.go
pkg/operator/controller/typed_test.go

Fixes # 
- Fixes a bug where any typed controller implementation wouldn't update its `Status()` if the spec or metadata had an update

fix: Fix status not updating when the spec has an update

---

pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/inflightchecks/suite_test.go
pkg/controllers/metrics/provisioner/suite_test.go
pkg/controllers/metrics/state/suite_test.go
pkg/controllers/node/suite_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/suite_test.go
pkg/controllers/termination/suite_test.go
pkg/operator/controller/suite_test.go
pkg/test/cachesyncingclient.go
pkg/test/environment.go
pkg/test/expectations/expectations.go
pkg/test/nodes.go
pkg/utils/machine/machine.go

Fixes # 
- Adds a `cacheSyncingClient` that waits for WRITE operations to be propagated to the cache before proceeding
- It is meant to mock a direct client while also giving a client-side cache for indexing `fieldSelectors`

test: Add a `cacheSyncingClient` for testing that allows for custom FieldIndexers

---

README.md

Fixes # 
- Fix README build status badge
- Viewing the status badge on the README in the fork

docs: Fix README build status badge

---

pkg/cloudprovider/types.go

Fixes # 
- Fix `MachineNotFound` custom error type checking
- Updates the type appropriately since `errors.As` does not perform correctly when simply typing errors with `cloudprovider.MachineNotFoundError(err)`
This is a similar change to https://github.com/aws/karpenter/pull/2253
- https://go.dev/play/p/cjKCHV_Htfx

chore: Fix `MachineNotFound` custom error type checking

---

pkg/apis/apis.go

Fixes # 
https://kubernetes.slack.com/archives/C02SFFZSA2K/p1672755352432249
`make test`
`make diff`
```
make diff
helm diff upgrade karpenter charts/karpenter --namespace karpenter --reuse-values --three-way-merge
karpenter, defaulting.webhook.karpenter.sh, MutatingWebhookConfiguration (admissionregistration.k8s.io) has changed:
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
creationTimestamp: "2023-01-03T21:42:18Z"
labels:
app.kubernetes.io/instance: karpenter
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: karpenter
app.kubernetes.io/version: 0.21.1
helm.sh/chart: karpenter-0.21.1
name: defaulting.webhook.karpenter.sh
ownerReferences:
- apiVersion: v1
blockOwnerDeletion: true …
```

fix: remove machine from webhook-gen

---

pkg/controllers/deprovisioning/pdblimits.go
pkg/controllers/deprovisioning/suite_test.go
pkg/test/expectations/expectations.go
pkg/test/pods.go

Fixes # 
This change supports k8s-1.25 at the cost of removing support for k8s-1.20. The v1beta1/pdb API is no longer available in k8s-1.25 and v1/pdb is available in k8s-1.21. Users *must* upgrade to k8s-1.21 for this version of karpenter to work. EKS no longer supports k8s-1.20: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions
Rebased: https://github.com/aws/karpenter/pull/2354
`make test`
Created a 1.20 cluster. On scale down
```
karpenter-f474d4db-mfzxj controller 2023-01-04T20:42:28.809Z	ERROR	controller.eviction	evicting pod, Eviction in version "v1" cannot be handled as a Eviction: no kind "Eviction" is registered for version "policy/v1" in scheme …
```

feat!: support k8s-1.25, remove support for k8s-1.20

---

pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/node.go
pkg/controllers/state/suite_test.go
pkg/test/expectations/expectations.go

Fixes # 
- Fix missed return statement in `cluster.State` Capacity
- Fix incorrect capturing of remainingResources

fix: Fix missed return statement in `cluster.State` Capacity

---

pkg/operator/operator.go

Fixes #https://github.com/aws/karpenter/issues/2902#issuecomment-1366907523
Enable's knative/pkg's HA for webhooks
Manually
* Fresh Install
* Delete Pods
No errors other than shutdown.

fix: Enable HA on webhook reconcilers

---

pkg/controllers/counter/controller.go
pkg/controllers/node/controller.go
pkg/controllers/node/emptiness.go
pkg/controllers/provisioning/controller.go
pkg/controllers/termination/controller.go
pkg/operator/controller/typed.go
pkg/operator/controller/typed_test.go

Fixes https://github.com/aws/karpenter/issues/3153
Fixes #153 
- Remove auto-patching from typed controllers
- This doesn't add patch helpers for not patching on no change yet since it felt like an unnecessary abstraction given the amount of patching that we are currently doing.
`FOCUS=Scheduling make e2etests`
`FOCUS=Emptiness make e2etests`
`FOCUS=Termination make e2etests`

chore: Remove auto-patching from typed controllers

---

pkg/controllers/inflightchecks/failedinit.go
pkg/controllers/inflightchecks/nodeshape.go
pkg/controllers/inflightchecks/suite_test.go

Fixes #157 
`beta.kubernetes.io/instance-type` label is deprecated.
`node.kubernetes.io/instance-type` should be used instead.
I've tested it using arm64 macbook
```
make toolchain
make test
```
Result:
```
❯ karpenter-core (issue-157-fix) ✔ make test                                  
go test ./... \
-race \
--ginkgo.focus="" \
-cover -coverprofile=coverage.out -outputdir=. -coverpkg=./...
?       github.com/aws/karpenter-core/pkg/apis  [no test files]
?       github.com/aws/karpenter-core/pkg/apis/config   [no test files]
ok      github.com/aws/karpenter-core/pkg/apis/config/settings  1.037s  coverage: 1.6% of statements in ./...
ok      github.com/aws/karpenter-core/pkg/apis/v1alpha5 2.752s  coverage: 4.0% of statements in ./...
? …
```

fix: Use stable instance-type label in inflight controllers

---

pkg/controllers/termination/terminate.go

Fixes # 
- Ignore MachineNotFound in terminate calls

chore: Ignore MachineNotFound in terminate calls

---

pkg/operator/operator.go

This reverts commit ca4f017e60bfd88b0aa0627a20f8fbbbbdf9869d.
Fixes # 

Revert "fix: Enable HA on webhook reconcilers (#142)"

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/provisioning/provisioner.go
pkg/utils/functional/functional.go

Fixes # 
- Return a `v1alpha5.Machine` struct from the cloudprovider create call
- This change preps for the `machine.Controller` which will use the full response to update the Machine status
`make test`

chore: Return a machine struct from the cloudprovider create call

---

pkg/controllers/provisioning/suite_test.go
pkg/controllers/provisioning/volumetopology.go

Fixes aws/karpenter/#3219
We need to validate volume names if specified to ensure they exist so we  don't launch a node for pods that won't schedule anyway.

fix: validate volume names

---

pkg/apis/v1alpha5/labels.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go

Fixes # 
- Handle provider id changing in cluster state
- Fixes a potential memory leak if the providerID changes and cluster state never cleans up the old providerID

fix: Handle `providerID` changing in cluster state

---

Makefile
pkg/controllers/machine/suite_test.go
pkg/test/cachesyncingclient.go

Fixes # 
- Fix cache syncing causing transient failures
- Cache syncing was updating the pointer when it would try to re-get the object, so, in reality, the syncing portion of the client would only attempt to get the updated object twice

test: Fix cache syncing causing transient failures

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/utils/resources/resources.go

Fixes # 
- Fix `Fits` function to check that total values are non-negative
Discovered through investigation on https://github.com/aws/karpenter/issues/3302

fix: Fix `Fits` function to check that total values are non-negative

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptiness.go
pkg/controllers/deprovisioning/emptynodeconsolidation.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/multinodeconsolidation.go
pkg/controllers/deprovisioning/singlenodeconsolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/types.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/cluster.go
pkg/controllers/state/informer/provisioner.go
pkg/controllers/state/node.go
pkg/controllers/state/suite_test.go

Fixes #2021
* Nothing was using `ResultRetry`, which just became success/failed, which maps 1:1 with err being nil or not
* Combined `RecordLastState` from individual deprovisioners into cluster state, which enabled the deprovisioning controller to be unaware of any specific subcontroller.
`make test`

chore: simplify deprovisioning controller and remove dead code

---

pkg/apis/crds/karpenter.sh_machines.yaml
pkg/apis/crds/karpenter.sh_provisioners.yaml
pkg/apis/v1alpha5/machine.go
pkg/apis/v1alpha5/suite_test.go

Addresses Feat:  https://github.com/aws/karpenter/issues/3300
Add support for CpuCFSQuota.
Tested using unit tests

feat: add support for CPUCFSQuota

---

pkg/controllers/provisioning/scheduling/topology.go

Fixes # 
Improves the log message when scheduling fails due to an unsatisfiable topology constraint.

chore: improve log message when scheduling fails

---

pkg/apis/v1alpha5/limits.go
pkg/apis/v1alpha5/suite_test.go

Fixes #198
Change the definition of ExceededBy to allow exact resource matches (this can happen if a Provisioner has
`spec.resources.limits.cpu` set to a value identical to a node's CPU count (or a multiple of a node's CPU count))
I wasn't able to find an existing test suite that handled node provisioning (I did find a pod provisioning suite but couldn't write a test that would fail before this change and would work after this change). i.e. this change is as yet untested

fix: Ensure that resource limits that exactly equal capacity are allowed

---

hack/toolchain.sh
pkg/apis/crds/karpenter.sh_machines.yaml
pkg/apis/crds/karpenter.sh_provisioners.yaml
pkg/apis/v1alpha5/machine.go
pkg/apis/v1alpha5/provisioner_validation.go
pkg/apis/v1alpha5/suite_test.go

Fixes https://github.com/aws/karpenter/issues/3343
- Return an error when receiving no `provider` or `providerRef`
Tried using `x-kubernetes-validations` but this doesn't work for customers that have not enabled the feature flag and are using older versions of K8s
```console
error: error validating "pkg/apis/crds/karpenter.sh_provisioners.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
``` …

fix: Return an error when receiving no `provider` or `providerRef`

---

pkg/controllers/machine/terminator/terminator.go
pkg/controllers/termination/controller.go

Fixes # 
- Termination could panic with the following error when the Patch() update results in the apiserver immediately return back an object that doesn't contain a deletionTimestamp set inside of it (because the object was quickly removed)
```console
2023-02-06T21:35:18.371Z	INFO	controller	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"commit": "afe64e9", "controller": "termination", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"ip-192-168-112-11.us-east-2.compute.internal"}, "namespace": "", "name": "ip-192-168-112-11.us-east-2.compute.internal", "reconcileID": "4e585e34-4d43-412e-9f77-c5910f911e5f"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime …
```

fix: Fix panic in termination flow

---

Makefile
hack/toolchain.sh
pkg/controllers/deprovisioning/drift_test.go
pkg/controllers/deprovisioning/expiration_test.go
pkg/controllers/deprovisioning/suite_test.go
pkg/test/expectations/expectations.go

Fixes # 
- `go triggerVerifyAction()` was sometimes running after the test had completed. This meant that subsequent tests would trigger the verify action before they were expected, polluting the test
- This PR adds a tracker to the `sync.WaitGroup` so that we wait for the `triggerVerifyAction` to complete before proceeding to the next test

test: Deflake deprovisioning testing

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/machine/launch.go
pkg/controllers/machine/suite_test.go

Fixes # 
- Make an Insufficient Capacity Error a cloudprovider-neutral concept as well as ensure that if this error is returned during machine launch that we self-delete so we will go to re-launch

chore: Handle insufficient capacity self-delete

---

pkg/apis/crds/karpenter.sh_machines.yaml
pkg/apis/crds/karpenter.sh_provisioners.yaml
pkg/apis/v1alpha5/labels.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/machine/controller.go
pkg/controllers/machine/garbagecollect.go
pkg/controllers/machine/launch.go
pkg/controllers/machine/launch_test.go
pkg/controllers/machine/registration.go
pkg/operator/controller/singleton.go

Fixes # 
Stages out karpenter-core changes for linking machines to a backing cloudprovider instance by using a `karpenter.sh/linked` annotation on the Machine to tell the machine controller to link the machine instead of launching a new one

chore: Stage core changes for linking machines (migration)

---

pkg/cloudprovider/types.go
pkg/controllers/provisioning/scheduling/machinetemplate.go

Fixes # 
Truncates the instance types requirements list so that the list will not be too large when it is populated into the `v1alpha5.Machine` spec. This list is now truncated down to the top 200 instance types that match the requirements. Cloudprovider are obviously welcome to further truncate this list down more if they need for their requests.

chore: Truncate instance types requirements list

---

charts/karpenter-core/templates/webhooks.yaml
pkg/apis/v1alpha5/provisioner_validation.go

Fixes #https://github.com/aws/karpenter/issues/3409
If a bad CRD causes Karpenter to crash, customers can get stuck without the ability to remove CRDs, since deletion validation webhooks are on by default in knative. 
```
❯ k scale deployment karpenter -n karpenter --replicas 0
deployment.apps/karpenter scaled
~/workspaces/go/src/github.com/aws/karpenter │ deletionwh *1 !7 ?1 ───────────────────── dev ⎈ │ 14:58:23
❯ k apply -f test.yaml
Error from server (InternalError): error when creating "test.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": no endpoints available for service "karpenter" …
```

fix: Remove deletion webhooks

---

pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/emptiness.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/inflightchecks/termination.go
pkg/controllers/machine/terminator/terminator.go
pkg/controllers/termination/suite_test.go

Fixes https://github.com/aws/karpenter/issues/3383
Remove `do-not-evict` preventing eviction when the Node is forcefully deleted through `kubectl delete node` or some other forceful deletion mechanism (like AWS interruption). `do-not-evict` should only be considered for Karpenter's voluntary disruption mechanisms (like emptiness/underutilization/consolidation, expiration, drift, etc.)
__BREAKING CHANGE: Customers who are currently deleting nodes with pods that have `do-not-evict` annotations will no longer have nodes hang on draining for this, meaning that they can't use `do-not-evict` as a stop-gap__

fix!: Prevent eviction hanging due to `do-not-evict`

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/provisioner/controller.go
pkg/controllers/metrics/state/controller.go
pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/informer/node.go
pkg/controllers/state/informer/pod.go
pkg/controllers/state/informer/provisioner.go
pkg/operator/controller/singleton.go

Fixes # 
- Migrate all singleton metrics inside of the `controller_runtime` namespace by leveraging `prometheus` `AlreadyRegisteredError` to grab the already registered collector and fire metrics to the same namespace

chore: Merge metrics to fire singleton metrics to `controller_runtime` metric namespace

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/suite_test.go

Fixes # 
Don't reset the consolidation time if it didn't actually run.

fix: only reset consolidation time if an attempt was made

---

pkg/controllers/provisioning/provisioner.go

In support of: https://github.com/aws/karpenter/issues/3565
This changes improves the performance of the provisioner. We saw high CPU usage, using pprof I found out that a lot of CPU cycles are wasted on the Union function on the string set.
Instead of using union I inserted all the new strings in place in the set, this decreased CPU usage by up to 50%.
I tested it out by building karpenter from source and deploying on a cluster with high CPU usage. You can see the result here. The green line is the before and the yellow after the change:
I also have 2 pprof profiles, one before the change you can find the pdf here:
[profile-old.pdf](https://github.com/aws/karpenter-core/files/10942733/profile-old.pdf)
And one after the change: …

perf: Improve the performance of the provisioner

---

pkg/controllers/counter/controller.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/provisioning/provisioner.go

Fixes # 
- Right now, the cluster state syncing mechanism will have an exponential backoff which can create large gaps between runs of the provisioning or deprovisioning loop. This should not be an exponential backoff but a continued one second poll
- Also, the counter controller _should_ use cluster state sync when overwriting the status. Otherwise, there is a potential for us to overwrite the status with a smaller value and shoot over our limits

chore: Cluster sync should have short requeue, no backoff

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/provisioner/controller.go

Fixes [#3209](https://github.com/aws/karpenter/issues/3209)
New Karpenter pod memory profile is shown bellow. Below is the top 10 blocks of memory for the karpenter controller. 
```
flat  flat%   sum%        cum   cum%
5633.31kB 21.72% 21.72% 12318.57kB 47.49%  encoding/json.(*decodeState).objectInterface
4631.90kB 17.86% 39.58%  5149.23kB 19.85%  encoding/json.unquote (inline)
2644.87kB 10.20% 49.77%  2644.87kB 10.20%  encoding/json.(*Decoder).refill
1536.51kB  5.92% 55.70%  1536.51kB  5.92%  go.uber.org/zap/zapcore.newCounters (inline)
1536.23kB  5.92% 61.62%  1536.23kB  5.92%  github.com/aws/aws-sdk-go/aws/endpoints.init
1536.02kB  5.92% 67.54%  5149.22kB 19.85%  encoding/json.(*decodeState).literalInterface
1097.69kB  4.23% 71.77%  2133.79kB  8.23% …
```

fix: Metrics Controllers Memory Leak

---

pkg/apis/v1alpha5/machine_status.go
pkg/controllers/machine/garbagecollect/controller.go
pkg/controllers/machine/launch.go
pkg/controllers/machine/launch_test.go
pkg/controllers/machine/liveness.go
pkg/controllers/machine/liveness_test.go
pkg/test/expectations/expectations.go
pkg/utils/machine/machine.go

Fixes # 
- Rename `MachineCreated` status condition to `MachineLaunched`

chore: Rename `MachineCreated` status condition to `MachineLaunched`

---

charts/karpenter-core/templates/clusterrole.yaml

Fixes # 
https://github.com/aws/karpenter/issues/3673
Removes webhook update permission for defaulting.webhook.karpenter.sh which was removed a while back

remove old webhook permission

---

pkg/controllers/machine/garbagecollect/suite_test.go
pkg/controllers/termination/controller.go
pkg/controllers/termination/suite_test.go

Fixes https://github.com/aws/karpenter/issues/3562 
Adds in a termination check to see if the underlying instance is not found. If not found, Karpenter will delete the node and remove the finalizer.

feat: add in termination check for nodes without machines

---

pkg/controllers/machine/termination/suite_test.go
pkg/test/cachesyncingclient.go
pkg/test/expectations/expectations.go

Fixes # 
- Add CacheSyncClient Handling for patching out finalizer
- Wait for the Node to be Gone in the termination flow before calling Machine termination controller
Viewed a drop in the time that it took to complete finalization removal and the Patching out of a finalizer from the Node

test: Add CacheSyncClient Handling for patching Finalizer and Fix Flake

---

pkg/apis/v1alpha5/labels.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/deprovisioning/drift_test.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/expiration_test.go
pkg/controllers/node/controller.go
pkg/controllers/node/drift.go
pkg/controllers/node/expiration.go
pkg/controllers/node/suite_test.go
pkg/utils/node/node.go

Fixes # 
This changes expiration to annotate the node so that users can be aware of when an expired node is queued up for deprovisioning.

feat: added expiration as node annotation for monitorability

---

pkg/controllers/consistency/controller.go
pkg/controllers/consistency/events.go
pkg/controllers/consistency/failedinit.go
pkg/controllers/consistency/metrics.go
pkg/controllers/consistency/nodeshape.go
pkg/controllers/consistency/suite_test.go
pkg/controllers/consistency/termination.go
pkg/controllers/controllers.go

Fixes #3696
Added metrics for consistency checks.
```
karpenter-96d576577-djtgc controller 2023-04-07T17:48:25.908Z	ERROR	controller.consistency	check failed, expected 688 of resource pods, but found 345 (50.1% of expected)	{"commit": "0bcd446-dirty", "node": "ip-192-168-98-227.us-west-2.compute.internal"}
```
```
curl localhost:8080/metrics | grep karpenter_consistency_errors
karpenter_consistency_errors{check="NodeShape"} 1
```

feat: Added metrics for consistency checks

---

charts/karpenter-core/templates/configmap-logging.yaml
charts/karpenter-core/values.yaml

Fixes # 
Container-based log level should not be supported since the separate containers for the controller and the webhook were removed in #29. These values should be removed from the `values.yaml` file in the helm chart
BREAKING: A user who would normally set the logLevel through `--set controller.logLevel` will now have to set it globally; otherwise, the log level will default to the global level
`make apply`

chore!: Remove container loglevel from `config-logging`

---

charts/karpenter-core/templates/configmap-logging.yaml
charts/karpenter-core/values.yaml

This reverts commit 58087aec96e6bb88692fc1c80178c36e58e92401.
Fixes # 

Revert "Remove container loglevel from config-logging (#283)"

---

pkg/controllers/node/drift.go
pkg/controllers/node/emptiness.go
pkg/controllers/node/expiration.go

Fixes # 
We were previously not re-queuing at the node expiration time. This meant that nodes that weren't expired weren't requeued to get annotated at their pre-determined expiration time.

fix: add requeue into node expiration controller

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptymachineconsolidation.go
pkg/controllers/deprovisioning/expiration_test.go
pkg/controllers/deprovisioning/multimachineconsolidation.go
pkg/controllers/deprovisioning/singlemachineconsolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/types.go

Fixes:
* https://github.com/aws/karpenter/issues/3708
* https://github.com/aws/karpenter/issues/3576
Fixes a bug where Karpenter would exponentially back off upon successful deprovisioning a node, leading to Karpenter appearing to freeze. Semantically, controller-runtime treats `return reconcile.Result{Requeue: true}, nil` as an exponential backoff. Subsequent reconcile loops that return this will increase the time between loops up to a maximum of [1000 seconds](https://github.com/kubernetes/client-go/blob/master/util/workqueue/default_rate_limiters.go#L86), starting at one millisecond. 
For example, after 10 successful expiration/drifts, karpenter would be waiting ~1 second between loops. After 20 successful drifts, karpenter would be waiting ~1000 seconds or 16.67 …

fix: Requeue immediately after deprovisioning

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/provisioning/provisioner.go

Fixes # 
Adds logging if deprovisioning takes longer than expected.

add logging if deprovisioners take longer than expected

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/scheduling/volumeusage.go

Fixes https://github.com/aws/karpenter/issues/3647
Previously, when the following `volumeClaimTemplate` was used for `Deployments`, we would not discover the `storageClassName` that is being used as the default and fail to find the driver associated with a volume
```yaml
volumes:
- name: scratch-volume
ephemeral:
volumeClaimTemplate:
spec:
accessModes: [ "ReadWriteOnce" ]
resources:
requests:
storage: 3Gi
```
This meant that Karpenter and the kube-scheduler would disagree. Karpenter would think that more pods could schedule on the node and the kube-scheduler would reject this due to the volume limits on the node. This change fixes this discovery by finding the default storage class (if one is specified) and using that if no `storageClassName` is specified
**How was this …

fix: Discover default storage class when none specified

---

pkg/controllers/node/emptiness.go
pkg/controllers/node/suite_test.go

Fixes # 
The node emptiness reconciler wouldn't requeue when the node was nominated. This meant that if a node was nominated when it went through the node emptiness sub-reconciler and there was no update to the node afterwards, there would be no requeue that would mark the node as empty. This change updates the sub-reconciler so we do a short poll during the node nomination timeframe.

fix: Fix node requeue when node is nominated

---

pkg/controllers/metrics/state/scraper/node.go

Fixes # 
This function shows up in profiling as taking a significant amount of time.  At least for now, make is ~2x as fast.
benchstat results of before -> after:
```
name         old time/op  new time/op  delta
Original-12  32.5µs ± 1%  13.9µs ± 2%  -57.26%  (p=0.000 n=10+10)
```

fix: speed up labelsToString

---

pkg/controllers/termination/terminator/terminator.go

Fixes # 
If the cordon in a termination reconcile failed, we would still log as cordoned.

fix: only log after cordon succeeds

---

go.mod
pkg/operator/injection/injection.go
pkg/operator/logger.go
pkg/operator/operator.go

Fixes https://github.com/aws/karpenter/issues/3560
- Fix log formatting on startup logs so that all logs are structured using the `*zap.SugaredLogger`
```console
2023-04-19T05:55:38.652Z        DEBUG   Successfully created the logger.
2023-04-19T05:55:38.652Z        DEBUG   Logging level set to: debug
{"level":"info","ts":1681883738.6558979,"logger":"fallback","caller":"injection/injection.go:63","msg":"Starting informers..."}
2023-04-19T05:55:38.756Z        DEBUG   controller      waiting for configmaps  {"commit": "7131be2-dirty"}
2023-04-19T05:55:39.269Z        DEBUG   controller      waiting for configmaps  {"commit": "7131be2-dirty"}
2023-04-19T05:55:39.770Z        DEBUG   controller      waiting for configmaps …
```

fix: Fix log formatting on startup logs

---

pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/drift_test.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/expiration_test.go
pkg/test/machine.go

Fixes https://github.com/aws/karpenter/issues/3742 
Expiration and Drift deprovisioning would do a scheduling simulation even if there are no pods scheduled to the node. Since we know we want to deprovision these nodes that are empty, we can terminate them in parallel. 
--- With commit, scaling down 10 nodes took about 2 seconds.
```
karpenter-8b946654b-xz2lz controller 2023-04-20T17:00:45.603Z	DEBUG	controller.node	annotating node as expired	{"commit": "49a318e-dirty", "node": "ip-192-168-93-8.us-west-2.compute.internal"}
karpenter-8b946654b-xz2lz controller 2023-04-20T17:00:45.604Z	DEBUG	controller.node	annotating node as expired	{"commit": "49a318e-dirty", "node": "ip-192-168-191-174.us-west-2.compute.internal"} …
```

chore: add in empty check for expiration and drift

---

pkg/controllers/provisioning/scheduling/scheduler.go

Fixes # 
Add `provisioner` context to log line that says "3 out of 573 instance types were excluded because they would breach provisioner limits"
Now, the log message says
```console
2023-04-24T17:29:11.174Z        ERROR   controller.provisioner  Could not schedule pod, all available instance types exceed limits for provisioner: "default"   {"commit": "eb81e26-dirty", "pod": "default/inflate2-7f745d7464-cmslc"}
2023-04-24T17:29:21.175Z        ERROR   controller.provisioner  Could not schedule pod, all available instance types exceed limits for provisioner: "default"   {"commit": "eb81e26-dirty", "pod": "default/inflate2-7f745d7464-cmslc"}
2023-04-24T17:29:31.175Z        ERROR   controller.provisioner  Could not schedule pod, all available instance types exceed limits for …
```

chore: Add `provisioner` context to log line

---

pkg/controllers/deprovisioning/emptymachineconsolidation.go

Fixes # 
The `EmptyMachineConsolidation` validation check was validating if both the candidate had more than one pod scheduled to it and if it wasn't nominated. Based on the comment and understanding, the correct validation is to fail validation when _either_ of the following things are true:
1. There is a pod scheduled to the node
2. The node is nominated in the cluster state for a pod very soon

fix: Fix empty machine validation check

---

pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/test/expectations/expectations.go

Fixes # 
Orders the `existingNodes` in a consistent manner in the scheduling algorithm. This ensures that:
1. Existing nodes that are being simulated against will have a consistent ordering so that the nomination mechanism should often pick the same node on multiple scheduling simulations (making PodNominations more consistent)
2. Initialized nodes will be tried first in consolidation so that it's less likely for consolidation to fail by scheduling a pod that it is trying to consolidate against an un-initialized node

chore: Order initialized nodes for Consolidation

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptymachineconsolidation.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/types.go
pkg/controllers/deprovisioning/validation.go

Fixes # 
- Add additional eventing for reasons that we remove Machine/Node combinations out of our filtering when considering consolidation

chore: Add eventing for blocked consolidation on nodes or machines

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/test/expectations/expectations.go

Fixes # 
Fix a panic on testing that failed to schedule pods to a Machine/Node combination. We should return back a nil Machine if we fail to schedule and pass that back up so that we don't do any binding of that pod to the Machine/Node.

test: Fix panic on tests that don't schedule to nodes

---

pkg/controllers/deprovisioning/types.go

Fixes # 
Fix panic on dereferencing a provisioner name when the provisioner is `nil`

fix: Fix provisioner name dereference panic

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/emptiness.go
pkg/controllers/deprovisioning/emptymachineconsolidation.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/multimachineconsolidation.go
pkg/controllers/deprovisioning/singlemachineconsolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/types.go

Fixes #280  
Removes an the old `action` type in the deprovisioning controller since the type of action can be inferred from the len(candidates) to replace or len(replacements). 

chore: cleanup deprovisioning types

---

pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/metrics/cloudprovider_test.go
pkg/cloudprovider/metrics/suite_test.go

Fixes #244
This PR introduces a simple metric incrementor into the CloudProvider flow to count total number of errors by well-known error types.
// TODO

feat: add errors_total CloudProvider metric

---

pkg/controllers/provisioning/scheduling/machine.go

Fixes # 
improve logs displayed when scheduling fails

chore: improve logs displayed when scheduling fails

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/emptiness.go
pkg/controllers/deprovisioning/emptymachineconsolidation.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/metrics.go
pkg/controllers/deprovisioning/multimachineconsolidation.go
pkg/controllers/deprovisioning/singlemachineconsolidation.go

Fixes # 
This adds in metrics to distinguish per-deprovisioner metrics and adds in a metric that shows how many machines are eligible for deprovisioning
- make apply && look at prometheus server

feat: add deprovisioning metrics for eligible machines

---

pkg/controllers/controllers.go
pkg/controllers/termination/controller.go
pkg/controllers/termination/metrics.go
pkg/controllers/termination/suite_test.go
pkg/metrics/metrics.go

Fixes # 
This metric was erroneously removed in [#176](https://github.com/aws/karpenter-core/pull/176/files#diff-64df72489417909f8ad9a7adac469bb50c6513e5f29ab7265e5ce6e859e02d12R106)
`karpenter_nodes_termination_time_seconds` metric was not firing when nodes were being terminated. This meant that we were not getting summary metrics on the amount of time that it takes to drain and delete nodes on average.
- Manual Deploy and Viewing Prometheus

fix: Fix `karpenter_nodes_termination_time_seconds` metric not firing

---

go.mod
go.sum
pkg/operator/operator.go

Fixes aws/karpenter/issues/3867
Webhook readiness was not considered by probes, leading to brief downtime of the webhook during rolling updates.
Knative hardcodes port 8080, so I moved the metrics port to container port 8000 in a buddy PR. Metrics are still scrapable at the karpenter service on port 8080.
* Update Provisioner during single pod rolling update

feat: Include knative webhooks in readiness probes

---

.github/actions/install-deps/action.yaml
.github/workflows/presubmit.yaml

Fixes # 
This change leverages the cache used by `setup-go` in `v4` by default which automatically caches the go build cache the go mod package cache. It also checks for cache hits on `actions/cache` and ignores some steps if the cache is hit.
* Running GHA and seeing speed-up from not running `make toolchain`
**Does this change impact docs?**
**Release Note**
```release-note
```

Ignore `make toolchain` when hitting Cache

---

pkg/controllers/controllers.go
pkg/controllers/termination/controller.go
pkg/controllers/termination/metrics.go
pkg/controllers/termination/suite_test.go
pkg/metrics/metrics.go

Fixes # 
- Cherry-picks Node Termination Summary Metric (https://github.com/aws/karpenter-core/pull/335)
- Manually Checking Metrics in Prometheus

Release v0.27.5

---

go.sum
pkg/controllers/machine/termination/controller.go
pkg/controllers/machine/termination/suite_test.go
pkg/utils/machine/machine.go

Fixes # 
Prior to this change, in the release `v0.28.0-rc.1`, if a Machine failed to launch, the `.status.providerID` of the machine could possibly not be resolved. If this was the case, the Machine would eventually get deleted due to a timeout on registration, causing any nodes associated with the machine to also be removed.
In this case, we were not guarding against the case where the providerID has never been resolved, meaning that we were deleting all nodes that had an empty providerID, meaning that Karpenter would delete nodes that weren't managed by it.
This change guards this case so that the next release `v0.28.0-rc.2` will not terminate these nodes when machines with empty provider ids are removed.
- Manual …

fix: Gate nodes associated with a machine based on resolved `.status.providerID`

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/scheduling/topology_test.go
pkg/test/pods.go

Fixes # 
This PR adds a new test convenience `UnschedulablePods` that allows us to more easily send a bunch of identically configured unschedulable pods to the provisioner test foo.

test: UnschedulablePods helper for test pod dups

---

hack/toolchain.sh
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topology_test.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/test/environment.go

Fixes #329 
This PR brings introduces support for the `minDomains` pod `topologySpreadConstraint`. User impact is transparent, as the new configuration (which is able to be enabled starting in Kubernetes v1.24) simply enforces pod replica distribution across nodes according to the declared number of `minDomains`, before allowing any one node to accept more pod replicas relative to any other node, according to its `maxSkew` configuration.
Three new test cases tell the story.
Note: for karpenter-core devs: this PR will rev the k8s toolchain to v1.24 (from v1.22), and so once this hits main we'll need to re-run `make toolchain` to rationalize local dev environments w/ the v1.24 req's now expected in test flows (specifically `minDomains`). 
New …

feat: support topologySpreadConstraint.minDomains

---

.github/actions/install-deps/action.yaml
.github/workflows/presubmit.yaml
pkg/controllers/provisioning/scheduling/topology_test.go

Fixes # 
- Fixes a caching issues on `.github/actions/install-deps` where the cache wouldn't be differentiated on the K8s Version, which meant that we would use a single K8s version for testing
- Fixes a compatibility issue with a K8s test on 1.27

fix: Edit the cache for `install-deps` to use K8s version

---

.github/workflows/presubmit.yaml

Fixes # 
- Pass K8s version to make presubmit in `.github/workflows/presubmit.yaml`

fix: Pass K8s version to make presubmit

---

pkg/scheduling/hostportusage_test.go

Fixes # 
This PR adds targeted function UT coverage to `pkg/scheduling/hostportusage.go`.

chore: HostPortUsage UT

---

pkg/controllers/deprovisioning/multimachineconsolidation.go
pkg/controllers/deprovisioning/suite_test.go

* This is a cherry-pick of https://github.com/aws/karpenter-core/pull/367 to include in the v0.27.x release line
Fixes # 
- Some very dynamic clusters can receive a lot of multi-machine consolidation aborts. This is because multi-machine consolidation computes a consolidation action and then validates that the option is still a valid consolidation plan after 15 seconds to ensure safe consolidation. In a dynamic cluster where pods are being scheduled that changes the consolidation action frequently, will result in multi-machine consolidation not being able to make safe progress. 
- This change allows multi-machine consolidation to fallback to single machine consolidation if the validation fails on multi-machine consolidation. This will allow a small amount of progress to be …

perf: allow multi-machine consolidation fallback to single-machine consolidation when mutli-node consolidation validation fails

---

pkg/apis/v1alpha5/labels.go

Fixes # 
Converts the `karpenter.sh/managed-by` label to be an annotation so that there are no value or length restriction to support longer cluster names and characters that aren't supported by label values (like `:`)

fix: Convert managed by label to annotation

---

pkg/controllers/provisioning/scheduling/events/events.go
pkg/scheduling/requirements.go
pkg/scheduling/requirements_test.go

Fixes # 
Karpenter was not sorting scheduling requirements strings for it's events, which created the notion that one scheduling requirements was represented in multiple ways. 
- Old FailedToSchedule events 
```
default     36m         Warning   FailedScheduling   pod/inflate-c76d54fc4-cpfdg   Failed to schedule pod, incompatible with provisioner "default", daemonset overhead={"cpu":"125m","pods":"2"}, no instance type satisfied resources {"cpu":"125m","nvidia.com/gpu":"1","pods":"3"} and requirements kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [default], karpenter.k8s.aws/instance-category In [c m r] (no instance type which had enough resources and the required offering met the …
```

fix: dedupe for events FailedToSchedule nodes 

---

charts/karpenter-core/templates/service.yaml
pkg/operator/options/options.go

Fixes # 
The pod metrics port number was changed in v0.28.0, but the default here was not changed, and neither was the service port, although the hard-coded value in the example helm chart was. 

BREAKING CHANGE: change service metrics port to match pod port

---

pkg/test/deployment.go

Fixes #N/A 
- Propagate `testing.karpenter.sh` discovery label to pods owned by deployment so that pods that are created through this method will be properly waited for during the cleanup phase.
`/karpenter snapshot`

test: Propagate discovery label to pods owned by deployment

---

pkg/controllers/consistency/suite_test.go
pkg/controllers/deprovisioning/drift_test.go
pkg/controllers/deprovisioning/expiration_test.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/machine/lifecycle/initialization.go
pkg/controllers/machine/lifecycle/initialization_test.go
pkg/controllers/node/drift.go
pkg/controllers/node/suite_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go
pkg/scheduling/taints.go
pkg/test/expectations/expectations.go

Fixes #N/A 
- This updates the initialization logic to ensure that all known ephemeral taints that become present on the Node when the Node first registers are removed before Karpenter begins to consider the Node for deprovisioning
- This is particularly critical for the `node.cloudprovider.kubernetes.io/uninitialized` taint which is added to the Node until the external cloudprovider removes its taint to mark it as registered

fix: Ensure the ephemeral taints are removed before considering the Node Initialized

---

pkg/controllers/machine/garbagecollection/controller.go

Fixes #N/A 
- Reduces log spam by removing `garbage collecting machine with no cloudprovider representation...` when the Machine on the cluster already has its DeletionTimestamp set. 
```console
2023-07-03T06:51:04.069Z        INFO    controller.machine.termination  deleted machine {"commit": "fd312fe", "machine": "gargoylerowan-2-k4achn7nrr-5ptwq", "node": "ip-192-168-85-31.us-west-2.compute.internal", "provisioner": "gargoy
lerowan-2-k4achn7nrr", "provider-id": "aws:///us-west-2d/i-080f5613bc4270047"}
2023-07-03T06:51:04.075Z        INFO    controller.machine.termination  deleted machine {"commit": "fd312fe", "machine": "gargoylerowan-2-k4achn7nrr-x8mvl", "node": "ip-192-168-95-12.us-west-2.compute.internal", "provisioner": "gargoy
lerowan-2-k4achn7nrr", "provider-id": …
```

chore: Reduce log spam from garbage collection

---

pkg/operator/operator.go

Fixes: https://github.com/aws/karpenter/issues/4154
Use loopback address to call knative readiness/liveness internally so that `no_proxy` can be properly enabled to not proxy the request outside the pod.
`/karpenter snapshot`

chore: Use loopback address to call knative readiness/liveness internally

---

pkg/apis/v1alpha5/labels.go
pkg/controllers/machine/lifecycle/registration.go
pkg/controllers/machine/lifecycle/registration_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go
pkg/test/expectations/expectations.go

Fixes #N/A 
- Adds the `karpenter.sh/registered` label to keep internal data consistency within the Node after all the labels, annotations, and taints have been properly propagated onto the Node after registration

chore: Add `karpenter.sh/registered` label

---

.github/dependabot.yml

Fixes #N/A 
- Group dependabot updates together into a single PR using the new [group feature](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
- Fix the github action dependabot update checking

ci: Group dependabot updates together

---

.github/dependabot.yml

Fixes #N/A 
- Fix dependabot grouping dependencies with `exclude-patterns` to ignore `k8s` deps on all other dependency gathering

ci: Fix dependabot grouping

---

pkg/apis/v1alpha5/labels.go
pkg/apis/v1alpha5/provisioner.go
pkg/apis/v1alpha5/suite_test.go
pkg/controllers/provisioner/controller.go
pkg/controllers/provisioner/suite_test.go
pkg/controllers/provisioning/scheduling/machinetemplate.go

Fixes #N/A 
- Karpenter will create a provisioner hash of the fields that the team considers to be statically drifted 
- The will contain the values of each of those fields 
- `make battletest`

feat: Adding static drift hash annotation

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptymachineconsolidation.go
pkg/controllers/deprovisioning/multimachineconsolidation.go
pkg/controllers/deprovisioning/singlemachineconsolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/informer/provisioner.go
pkg/controllers/state/suite_test.go

There was a race with deprovisioning with steps 2 & 3 where we could: 
1) See the cluster as unconsolidated
2) Run the deprovisioners unsuccessfully
3) Something happens that makes consolidation possible (e.g. pod
deletion)
4) We mark the cluster as unconsolidatable
5) On the next round, do nothing since cluster is unconsolidatable
The end result is that we mark the cluster as unconsolidatable which prevents us from trying again to save CPU time. Thankfully this was built with a 5 minute timeout to handle recovering from ICE situations automatically which limited the severity of the problem.
This change modifies the code to use a monotonically increasing timestamp.  If the cluster state changes (or nothing changes for five minutes), it increases.
The race above is now …

fix: prevent consolidation from pausing for 5m

---

pkg/operator/operator.go

Fixes https://github.com/aws/karpenter/issues/4296
#4296 caught an issue where Karpenter was leaking file descriptors in its webhook checks. This can be observed from the following graph that shows the Karpenter `container_file_descriptors` metric that tracks the number of open file descriptors on a container.
The root cause of this issue is that Golang's default HTTP client opens a connection and holds that connection open when receiving a valid response from the server, which causes a file descriptor to remain open until the connection is closed (some details described [here](https://stackoverflow.com/questions/33238518/what-could-happen-if-i-dont-close-response-body)). 
This issue with not closing the response body was technically introduced in the following PR: #334 …

fix: Close response to fix file descriptor leak

---

pkg/apis/v1alpha5/provisioner.go
pkg/controllers/controllers.go
pkg/controllers/machine/disruption/drift.go
pkg/controllers/machine/disruption/drift_test.go
pkg/controllers/provisioner/controller.go

Fixes #N/A 
- Adding static one-way drift for the provisioner.
- The fields that will statically drift:
-  Taints
-  Labels
-  Annotations
-  Kubelet Configuration 
- Startup Taints
- Drift will check the hash that is produced from the provisioner against all its machines to validate the machines have not drifted
- Unit tested 
- E2E testing will be in https://github.com/aws/karpenter/pull/4305

feat: Provisioner Static Drift

---

.github/workflows/stale.yaml

Fixes #N/A 
- Adds the `needs-review` and `needs-design` PR labels to be ignored by the stalebot

ci: Add more exempt PR labels to stalebot

---

pkg/cloudprovider/types.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/statenode.go
pkg/scheduling/requirement.go
pkg/scheduling/volumeusage.go
pkg/utils/atomic/cachedvar.go
pkg/utils/resources/resources.go

Allocatable() is called a lot. Memoize this using a sync.Map so we can avoid the expensive calculation.
name               old time/op   new time/op   delta
Scheduling1-12       566µs ± 9%    382µs ± 5%  -32.54%  (p=0.004 n=5+6)
Scheduling50-12     26.2ms ± 4%   20.0ms ± 6%  -23.53%  (p=0.004 n=5+6)
Scheduling100-12    53.1ms ± 8%   39.4ms ± 6%  -25.70%  (p=0.004 n=5+6)
Scheduling500-12     272ms ± 5%    202ms ±10%  -25.68%  (p=0.004 n=5+6)
Scheduling1000-12    596ms ±11%    457ms ±12%  -23.38%  (p=0.004 n=5+6)
Scheduling2000-12    1.08s ± 4%    0.89s ±10%  -17.46%  (p=0.004 n=5+6)
Scheduling5000-12    2.83s ± 8%    2.21s ± 6%  -21.91%  (p=0.004 n=5+6)
Fixes #N/A 
By submitting this pull request, I confirm that my contribution is made under …

perf: improve scheduling speed

---

pkg/operator/operator.go

Fixes - https://github.com/aws/karpenter/issues/4216
Add leader election namespace during initialization so that Kubernetes clusters where default service account tokens are not automatically mounted can run Karpenter with leader election. Issue -  https://github.com/aws/karpenter/issues/4216
Tested in our setup where we don't mount default namespace service account.

[fix] Adding LeaderElectionNamespace to init of controllerruntime Manager

---

pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go

Fixes https://github.com/aws/karpenter/issues/4266
Prior to this change, Karpenter wouldn't consider capacity that wasn't owned by Karpenter for pod scheduling. This meant, paricularly in the case of consolidation, that Karpenter wouldn't scale-down Karpenter-managed nodes if there was other static capacity in the cluster that those pods could schedule to.
This change adds support for Karpenter discovering this capacity so that consolidation will scale-down these nodes.
- Manual validation using MNG and Karpenter-managed nodes

fix: Consider existing capacity for scheduling

---

pkg/controllers/provisioning/provisioner.go

Fixes #N/A 
Fire an INFO message rather than WARN on `no provisioners found` during the provisioning loop
`make apply`
```console
2023-08-01T22:30:23.302Z        WARN    controller.provisioner  no provisioners found   {"commit": "e08a862"}
2023-08-01T22:30:33.302Z        WARN    controller.provisioner  no provisioners found   {"commit": "e08a862"}
2023-08-01T22:30:43.303Z        WARN    controller.provisioner  no provisioners found   {"commit": "e08a862"}
```
```console
2023-08-01T22:28:11.912Z        INFO    controller.provisioner  no provisioners found   {"commit": "e08a862"}
2023-08-01T22:28:21.912Z        INFO    controller.provisioner  no provisioners found   {"commit": "e08a862"}
2023-08-01T22:28:31.913Z        INFO …
```

chore: Fire an INFO rather than WARN

---

pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #343 
This change enforces stricter compatibility for Machines/Nodes that are already deployed on the cluster. We will not provision until we have resolved all of the Machine labels. At the point that we resolve the Machine labels, we should know the expected machine requirements that should be compatible. Particularly, we shouldn't be considered a Machine/Node compatible if the Pod requirements require that a label exist like 
```yaml
- key: "topology.kubernetes.io/zone"
operator: In
values: ["test-zone-1"]
```
and this label doesn't exist on the requisite Node, we should not consider this node to be compatible. This compatibility check is _different_ when we are considering a "theoretical node" where we still have the ability to inject labels into the node to …

fix: Enforce stricter compatibility for existing nodes/machines

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
Updates cluster state to wait for a Node that is Karpenter-managed to propagate its providerID before adding it into cluster state. This prevents us having expectations about the state of this node (including having the instance type label which was causing spurious errors to be thrown) and ensures that we don't treat the node capacity as separate capacity from the tracked Machine while the mapping hasn't been established.
`/karpenter snapshot`

fix: Wait for Karpenter-managed node to populate provider id

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/scheduling/volumeusage.go
pkg/test/storage.go

Fixes https://github.com/aws/karpenter/issues/4003
Currently, we ignore in-tree drivers that we don't recognize since the volume limit for a node cannot be looked up from the CSINode that we use to maintain our other volume limits. This PR enables the translation mechanism from the in-tree provisioner name (if specified) to the out-of-tree CSI provisioner name (if one exists). This translation will happen both from the driver name in the volume and the provisioner name in the StorageClass.

fix: Translate all in-tree providers to CSI

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/machine/disruption/drift.go
pkg/controllers/machine/disruption/drift_test.go
pkg/controllers/machine/disruption/suite_test.go
pkg/controllers/machine/disruption/types.go

Fixes #N/A 
- To pass metric the cloud provider should pass back the field that is considered for logging and metrics 
- `make test`

chore: Update cloud provider interface to provide drifted reason

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/test/expectations/expectations.go
pkg/utils/resources/resources.go

Fixes https://github.com/aws/karpenter/issues/4392
add pod overhead into pod resources calculation
Unit testing and with the example pod in the issue.
Before change
```
karpenter-58d6968796-6mnj6 controller 2023-08-08T13:38:36.847Z	INFO	controller.provisioner	created machine	{"commit": "3f1bce4", "provisioner": "default", "requests": {"cpu":"185m","memory":"240Mi","pods":"5"}, "instance-types": "c3.2xlarge, c3.large, c3.xlarge, c4.2xlarge, c4.large and 95 other(s)"}
```
After change
```
karpenter-9d8787b9c-5pbpl controller 2023-08-08T13:43:24.686Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", daemonset overhead={"cpu":"185m","memory":"240Mi","pods":"4"}, no instance type satisfied resources …
```

fix: add pod overhead into pod resources calculation

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/scheduling/topology_test.go
pkg/controllers/provisioning/scheduling/volumetopology.go
pkg/controllers/provisioning/suite_test.go
pkg/scheduling/storageclass.go
pkg/scheduling/volumeusage.go
pkg/test/pods.go

Fixes #N/A 
Prior to this change, Karpenter would only handle volume topology for PVCs that were directly reference by pods through the `.spec.volumes[*].persistentVolumeClaim` field; however, pods can also reference [dynamically-generated generic ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes), referenced through `.spec.volumes[*].ephemeral`. We did not respect PVCs that were bound to pods with volume topology. This change allows us to handle ephemeral volumes and scale-out if the current nodes do not satisfy the volume topology.
- Deploying bound PVC/PV to cluster, removing nodes and expecting Karpenter to assign volume topologies correctly
By submitting this …

fix: Handle ephemeral volume topology

---

pkg/controllers/provisioning/scheduling/volumetopology.go

Fixes #N/A 
These can affect scheduling decisions and make it difficult to debug why pods aren't scheduling.  With this change, the new requirements are logged and it should become easier to diagnose incompatibility between volumes and pod requirements. Currently this creates an empty set requirement and the pod just fails to schedule.
Unit testing and observed the new log.
```
DEBUG	scheduling/volumetopology.go:74	adding requirements derived from pod volumes, [{topology.kubernetes.io/zone In [test-zone-2 test-zone-3]}]	{"pod": "default/facegarnet-49-9jvxmqcv0v"}
```

chore: debug log when we add requirements due to volumes

---

pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/drift_test.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/expiration_test.go
pkg/utils/machine/machine.go

Fixes #N/A 
When pods could not all schedule, expiration and drift would continue. This asserted that nodes that were expired or drifted would eventually be cleaned up. Yet, in the case where all replacement types were exhausted, this would just result in a delete action, which if the Provisioner has no correct configuration, could result in a scale to 0 situation. 

fix: continue for expiration/drift when pods cannot reschedule

---

pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/drift_test.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/expiration_test.go

Fixes #N/A 
This PR deflakes two test cases that deal with the ordering of nodes by specifically setting a status condition to a later time rather than relying on the `.StatusConditions().MarkTrue()` mechanism which relies on `time.Now()` and was prone to race conditions.
`make deflake`

test: Deflake tests that validate deprovisioning ordering

---

pkg/controllers/deprovisioning/consolidation.go
pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/validation.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #457
We still consider pending pods for scheduling calculation purposes, but if a pod was pending before scheduling, we don't let the fact that we can't schedule it prevent consolidation. This ensures that permanently pending pods won't block consolidation.

fix: ignore permanently pending pods during consolidation

---

go.mod
pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/events/events.go

Fixes #N/A 
Deprovisioning events were spamming event messages by providing the entire command reason log output in the event for _each_ Node and _each_ Machine. This meant that when there was a deprovisioning action that was taken that affected multiple nodes, it would provide the full command output for each event, which wasn't useful and was quite spammy.
```console
10s         Normal    DeprovisioningTerminating       node/ip-192-168-97-252.us-west-2.compute.internal    Deprovisioning node via delete, terminating 100 machines ip-192-168-12-92.us-west-2.compute.internal/t3a.small/on-demand, ip-192-168-8-101.us-west-2.compute.internal/t3a.small/on-demand, ip-192-168-113-135.us-west-2.compute.internal/t3a.small/on-demand, …
```

chore: Reduce event spam by replacing `command.String()`

---

pkg/controllers/deprovisioning/drift.go
pkg/controllers/deprovisioning/events/events.go
pkg/controllers/deprovisioning/expiration.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/types.go

Fixes #N/A 
Deprovisioning events were spamming event messages by firing `DeprovisioningBlocked` (and some `Unconsolidatable`) events right around that a Machine/Node is starting up. These events are not particularly useful at this point in time (since these events are mainly there for debugging and there to inform the user why Karpenter has not made a decision against a specific Node).  Karpenter should not begin firing these events until the Machine/Node has been initialized. At this point, we can assume that the Node is in a steady state and begin adding debug events if Karpenter cannot take an action against it.
```console
➜  karpenter git:(main) k get events | grep DeprovisioningBlocked | wc -l           
2000
```
```console
➜  karpenter git:(main) k get events | grep …
```

chore: Stop firing `DeprovisioningBlocked` until initialized

---

pkg/controllers/controllers.go
pkg/controllers/counter/controller.go

Fixes #N/A 
This PR starts staging out the changes for `v1beta1` to be supported across all controllers. It adds conversion for `v1alpha5.Provisioner`s into `v1beta1.NodePool`s so that all Provisioners and NodePools are treated the same in-memory for the Counter controller to update the status for the `NodePool` and the `Provisioner`.
`make apply`

chore: Enable `v1beta1/NodePool` conversion in counter controller

---

pkg/controllers/consistency/controller.go
pkg/controllers/consistency/events.go
pkg/controllers/consistency/nodeshape.go
pkg/controllers/consistency/suite_test.go
pkg/controllers/consistency/termination.go
pkg/controllers/controllers.go

Fixes #N/A 
This PR starts staging out the changes for `v1beta1` to be supported across all controllers. It adds conversion for `v1alpha5.Machine`s into `v1beta1.NodeClaim`s so that all Machines and NodeClaims are treated the same in-memory for the Consistency Controller to update the status for the `NodeClaim` and the `Machine`
`make apply`

chore: Enable `v1beta1/NodeClaim` conversion in consistency controller

---

pkg/controllers/controllers.go
pkg/controllers/leasegarbagecollection/controller.go
pkg/controllers/leasegarbagecollection/metrics.go
pkg/controllers/leasegarbagecollection/suite_test.go
pkg/metrics/metrics.go

Fixes #N/A 
- As part of our mitigation strategy for https://github.com/aws/karpenter/issues/4363, we are implementing a controller to delete node leases that do not contain any OwnerReference. 
- This controller should be removed once https://github.com/kubernetes/kubernetes/issues/109777 is fixed upstream
- Manually tested

chore: Garbage Collect Leaked Node Lease

---

pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation.go
pkg/apis/v1beta1/nodepool_validation_test.go
pkg/controllers/controllers.go
pkg/controllers/machine/disruption/drift_test.go
pkg/controllers/provisioner/controller.go
pkg/controllers/provisioner/suite_test.go
pkg/utils/nodepool/nodepool.go

Fixes #N/A 
This PR starts staging out the changes for `v1beta1` to be supported across all controllers. It adds support for reconciling the NodePool hash in the same way that we reconcile the Provisioner hash in the current Provisioner hash controller.

chore: Enable `v1beta1/NodePool` provisioner hash controller

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/provisioner/controller.go
pkg/controllers/metrics/state/scraper/node.go
pkg/metrics/store.go
pkg/metrics/suite_test.go

Fixes # 
This PR removes the individual logic in each controller for metric tracking and moves this as an abstraction over to the `metrics.Store` for tracking and replacing metrics.
This mechanism performs a very similar mechanism to `kube-state-metrics`, where it tracks the metrics for a particular "metric family" based on a given string key (in this case only one metric family is stored per key in each metric store). 
When a call to `Update` is made, the metric store will "refresh" these metrics by updating any existing metrics with the new values for those that match the labels and sweeping any old metrics assigned to the key that aren't in the new set.
When a call to `ReplaceAll` is made, the metric store will effectively perform `Update` across all of its metric keys, …

chore: Perform metrics tracking through a `MetricStore` abstraction

---

pkg/apis/v1alpha5/labels.go
pkg/apis/v1alpha5/suite_test.go
pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodepool_validation_test.go

Fixes #N/A 
This change allows users to pass labels prefixed with `node-restriction.kubernetes.io` into Karpenter labels and requirements. These labels were previously disallowed.
`make apply`

chore: Allow `node-restriction.kubernetes.io/` prefix in the label set

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptymachineconsolidation.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/deprovisioning/validation.go
pkg/controllers/machine/disruption/emptiness.go
pkg/controllers/machine/disruption/emptiness_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/state/cluster.go
pkg/controllers/state/informer/machine.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
This change converts all of the state functions to take in a provider id as a string rather than a name for `NominateForPod`, `IsNodeNominated`, `MarkForDeletion`, and `UnmarkForDeletion`. This change also changes the name tracking to providerID for deletion to happen per-kind so no naming conflicts cause inconsistent state or leaks.
`/karpenter snapshot`

chore: Handle shared state for Machine/NodeClaim

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go

Fixes #N/A 
If none of the provisioners in the cluster had a nodePool defined, users could see the following message when a pod fails to schedule, when Karpenter should either log or return here. 
Similarly, we should be able to opt these provisioners out of any scheduling simulations, since we know that the GetInstanceTypes() call will fail. 
```
ERROR	controller.provisioner	Could not schedule pod, all available instance types exceed limits for provisioner: "default"	
```
- `make presubmit` and local application

fix: do not consider provisioners without a provider

---

pkg/controllers/state/cluster.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
Adds an initialization flag to the inflight capacity and startup taints for `StateNode` ensuring that the values are only set once. Additionally, this change helps clean up spurious logging due to inflight resource checks during test environment tear down.

chore: single init inflight capacity / startup taints

---

pkg/apis/v1alpha5/suite_test.go

Fixes #N/A 
Adds a test to compare the hash of different provisioners to previously computed values. This ensures that equivalent provisioners hash to the same value between versions.

test: static provisioner hash test

---

pkg/controllers/termination/controller.go
pkg/controllers/termination/suite_test.go
pkg/test/environment.go

Fixes #N/A 
This PR adds the removal of the `v1beta1/NodeClaim`s that are associated with any given `v1.Node` provider ID. This change is another one of the changes on the path to fully migrating the repository over to the new v1beta1 APIs.

chore: Add handling to delete all `v1beta1/NodeClaim` on node termination

---

Makefile
pkg/controllers/state/cluster.go
pkg/controllers/state/informer/nodeclaim.go
pkg/controllers/state/suite_test.go
pkg/test/expectations/expectations.go

Fixes #N/A 
This change adds the informer for the `v1beta1/NodeClaim` to the `cluster.State`. This change is another one of the changes on the path to fully migrating the repository over to the new v1beta1 APIs.

chore: Add `v1beta1/NodeClaim` informer for cluster state

---

pkg/operator/operator.go

Fixes #N/A 
This adds in a endpoint slice cache so that we can list/watch endpoints in the default namespace.

feat: index default namespace endpoints for discovery

---

pkg/controllers/nodepool/hash/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/informer/nodeclaim.go
pkg/controllers/state/informer/nodepool.go
pkg/controllers/state/suite_test.go
pkg/controllers/termination/suite_test.go

Fixes #N/A 
This PR adds the `v1beta1/NodePool` informer to trigger consolidation updates anytime there is a change in the NodePool spec

chore: Add nodepool informer for triggering consolidation updates

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
This PR updates the scheduling benchmarker code to use the v1beta1 APIs instead of the v1alpha5 APIs

test: Update scheduling benchmarker to use `v1beta1` APIs

---

pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodeclaim.go

Fixes #N/A 
This PR drops the `spec.kubelet.containerRuntime` field from the `v1beta1` APIs

chore: Drop the `containerRuntime` field from the `v1beta1` kubeletConfig

---

pkg/test/nodeclaim.go

Fixes #N/A 
This PR removes the defaulting logic for the `v1.NodeSelectorRequirements` for the `NodeClaim`, similar to the removal for the `v1beta1.NodePool`

test: Don't constrain the NodeClaim if no test requirements are specified by default

---

pkg/controllers/provisioning/scheduling/nodepool_instance_selection_test.go
pkg/controllers/provisioning/scheduling/provisioner_instance_selection_test.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
This PR adds `v1beta1/NodePool` testing to duplicate the topology testing code in the current `instance_selection_test.go` file for scheduling with `v1alpha5/Provisioners`

test: Add `v1beta1` testing for instance type selection testing

---

pkg/controllers/provisioning/scheduling/nodepool_topology_test.go
pkg/controllers/provisioning/scheduling/provisioner_topology_test.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
This PR adds `v1beta1/NodePool` testing to duplicate the topology testing code in the current `topology_test.go` file for scheduling with `v1alpha5/Provisioners`

test: Add `v1beta1` testing for NodePool topology

---

.github/actions/install-deps/action.yaml
Makefile
hack/toolchain.sh

Fixes #N/A 
This PR updates the installation path for kubebuilder to change it from a path in your home directory to the default expected installation path `/usr/local/kubebuilder/bin`. This means that you no longer need to set the `KUBEBUILDER_ASSETS` variable in testing

ci: Set the toolchain kubebuilder install path to be the default one

---

pkg/cloudprovider/metrics/cloudprovider.go
pkg/cloudprovider/metrics/cloudprovider_test.go
pkg/cloudprovider/types.go
pkg/controllers/nodeclaim/lifecycle/events.go
pkg/controllers/nodeclaim/lifecycle/launch.go
pkg/controllers/nodeclaim/lifecycle/machine_launch_test.go
pkg/controllers/nodeclaim/lifecycle/nodeclaim_launch_test.go

Fixes #N/A 
- Creates a `NodeClassNotReadyError` into the `NodeClaim` launch for handling cases where you want to declare that the launch should wait due to `NodeClass` readiness. The thinking is that this _may_ turn into a `statusCondition` on the `NodeClass` down the line.

chore: Create custom `NodeClassNotReady` error for nodeClaim launch

---

pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodepool.go

Fixes #N/A 
This change drops the shortnames for `v1beta1/NodeClaims` and `v1beta1/NodePools`. These were dropped since these would have to be supported long-term and they had some potential to conflict with other shortnames from other K8s resources.

chore: Drop short names for NodeClaims and NodePools

---

pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/nodeclaim_drift_test.go

Fixes #N/A 
This change adds `NodePoolDrifted` as one of the `Drifted` reasons within the `v1beta1/NodeClaim` API

chore: Add `v1beta1/NodePool` drifted reason

---

.github/actions/install-deps/action.yaml

Fixes #N/A 
This change fixes the `actions/cache` step which was broken due to directory permissions on restore
Running the CI jobs

ci: Fix caching on `install-deps`

---

pkg/controllers/provisioning/nodepool_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/provisioner_test.go

Fixes #532  
Change getDaemonSetPods method to merge in daemon set template pod spec affinities with existing pod affinities to retain this information during scheduling. This would allow scheduler to not include daemonsets that would not be scheduled on a provisioner within their calculations of daemonset overhead
Unit tests included in the PR

fix getDaemonSet to preserve pod affinity in daemonset template pod spec.

---

.github/workflows/presubmit.yaml

Fixes #N/A 
Adds kubernetes 1.28 to CI tests.

test: add k8s 1.28 to CI

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/deprovisioning/helpers.go
pkg/controllers/deprovisioning/machine_consolidation_test.go
pkg/controllers/deprovisioning/nodeclaim_consolidation_test.go

Fixes https://github.com/aws/karpenter/issues/4723
If you misconfigure a provisioner (e.g. delete its node template), we
- should log and let you know (fixed earlier)
- still be able to deprovision any nodes that were not created by that provisioner

fix: don't allow a single bad provisioner to stop deprovisioning

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/nodepool_topology_test.go
pkg/controllers/provisioning/scheduling/provisioner_topology_test.go

Fixes #N/A 
Topology Domains [currently observe the constraints of the Provisioner they are under](https://github.com/aws/karpenter-core/blob/main/pkg/controllers/provisioning/provisioner.go#L249) so that the scheduler uses as much spread as is possible within the full set of topology options that are available on the cluster and within the set of options that Provisioners offer. 
Prior to this change, we were not respecting labels for constraining the domain set. This meant that if there was a label on a NodePool that also had a topologyConstraint on a pod and you didn't have Provisioners that covered the full set of domains that were returned by the instance types, scheduling would hang. 
This change ensures that the domain values are constrained by NodePool labels as …

fix: Topology domains should be constrained on labels

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/provisioning/nodepool_test.go
pkg/controllers/provisioning/provisioner_test.go
pkg/controllers/provisioning/scheduling/nodepool_test.go
pkg/controllers/provisioning/scheduling/nodepool_topology_test.go
pkg/controllers/provisioning/scheduling/provisioner_test.go
pkg/controllers/provisioning/scheduling/provisioner_topology_test.go
pkg/controllers/provisioning/suite_test.go
pkg/test/expectations/expectations.go

Fixes #N/A 
This PR adds provisioning testing for validating that scheduling and provisioning together with `v1alpha5/Provisioner` and `v1beta1/NodePool` and that the scheduling logic won't consider them as separate entities but will consider all possibilities when scheduling pods to nodes.

test: Add testing to handle Provisioner/NodePool combined provisioning

---

pkg/controllers/nodepool/counter/nodepool_test.go
pkg/controllers/nodepool/counter/provisioner_test.go
pkg/controllers/nodepool/counter/suite_test.go
pkg/utils/nodepool/nodepool.go
pkg/utils/nodepool/suite_test.go
pkg/utils/provisioner/suite_test.go

Fixes https://github.com/aws/karpenter/issues/4628
Fixes the conversion logic converting from `v1beta1/NodePool` -> `v1alpha5/Provisioner` to retain the status information so that patch operations that remove details can properly handle this operation.
`make apply` (manual validation)

fix: Fix patching `nil` resources when converting Provisioner to NodePool

---

pkg/controllers/deprovisioning/machine_consolidation_test.go
pkg/controllers/deprovisioning/machine_drift_test.go
pkg/controllers/deprovisioning/machine_emptiness_test.go
pkg/controllers/deprovisioning/machine_expiration_test.go
pkg/controllers/deprovisioning/nodeclaim_consolidation_test.go
pkg/controllers/deprovisioning/nodeclaim_drift_test.go
pkg/controllers/deprovisioning/nodeclaim_emptiness_test.go
pkg/controllers/deprovisioning/nodeclaim_expiration_test.go

Fixes #N/A 
This PR adds testing for both `v1alpha5` and `v1beta1` components to validate that both APIs respect the `do-not-consolidate`, `do-not-disrupt`, and `do-not-evict` annotation keys across all deprovisioning mechanisms.

test: Add testing to validate `do-not-disrupt` and `do-not-evict`

---

pkg/controllers/deprovisioning/machine_drift_test.go
pkg/controllers/deprovisioning/suite_test.go

Fixes #N/A 
This change adds deprovisioning testing for handling `v1alpha5/Machines` and `v1beta1/NodeClaims` together to ensure that we treat them as similar entities and can parallelize them when we are deprovisioning for our different disruption conditions.

test: Add combined deprovisioning testing for `v1beta1` and `v1alpha5`

---

.github/workflows/presubmit.yaml

Fixes #N/A 
- Remove k8s 1.22 from unit testing.
- karpenter does not support 1.22
- N/A

ci: Remove 1.22 from our testing

---

pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation_test.go
pkg/apis/v1beta1/zz_generated.deepcopy.go
pkg/cloudprovider/types.go
pkg/controllers/deprovisioning/nodeclaim_consolidation_test.go
pkg/controllers/metrics/nodepool/suite_test.go
pkg/controllers/provisioning/nodepool_test.go
pkg/controllers/provisioning/provisioner_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
pkg/controllers/state/suite_test.go
pkg/test/nodeclaim.go
pkg/test/nodepool.go
pkg/utils/machine/machine.go
pkg/utils/machine/suite_test.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/suite_test.go
pkg/utils/nodepool/nodepool.go
pkg/utils/nodepool/suite_test.go
pkg/utils/provisioner/provisioner.go
pkg/utils/provisioner/suite_test.go

Fixes #N/A 
Update NodeClassReference to have fieldname `nodeClassRef` instead of `nodeClass` to show the field is a reference field

chore: Update NodeClassReference to have fieldname `nodeClassRef`

---

pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodeclaim_validation_test.go
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_webhook_test.go
pkg/apis/v1beta1/suite_test.go
pkg/test/environment.go

feat: Adding CEL validation for the `nodepool.spec.disruption`

---

pkg/operator/logging/logging.go
pkg/operator/options/options.go

Fixes #N/A 
This PR deprecates the `karpenter/config-logging` ConfigMap for configuring the logger, in favor of an opinionated approach to how the logger is configured. Now, Karpenter will configure the logger by default and will surface the `LOG_LEVEL` environment variable and `--log-level` CLI argument to allow changing the log level for the controller. This is the recommended way to configure Karpenter logging if log level changes are needed.
Alternatively, Karpenter will support a soon-to-be-deprecated form of configuring the logger through the filesystem. This method is introduced as an alternative to Karpenter discovering the ConfigMap through API discovery and, instead, uses the container-native filesystem mechanism of loading in the configuration.
1. Global Zap …

chore: Enable configuring logger through volume mount and environment variable

---

pkg/controllers/controllers.go
pkg/controllers/deprovisioning/controller.go
pkg/controllers/termination/suite_test.go
pkg/controllers/termination/terminator/eviction.go
pkg/controllers/termination/terminator/suite_test.go
pkg/controllers/termination/terminator/terminator.go
pkg/events/suite_test.go
pkg/operator/controller/singleton.go
pkg/operator/operator.go

Fixes #N/A 
This makes the termination controller into a singleton controller. This removes the goroutine from the constructor and allow the underlying controller manager to start/cancel the context so that this goroutine cleans up with Karpenter is shutting down.
- applied to local cluster

chore: move termination queue to singleton controller

---

pkg/controllers/termination/suite_test.go

Fixes #N/A 
Fixes a flake in termination tests. The ordering of pods aren't consistent across critical pods. This makes it so that we check if both critical pods are deleted after the queue processes both of them.

test: fix termination test flake

---

pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/suite_test.go

Fixes #N/A 
- To improve testing speed, the environment set-up should be create an the beginning of the suite for the v1bata1 test suite.
- N/A

test: Move `env` to be created at the beginning of suite for `v1beta1`

---

pkg/controllers/deprovisioning/controller.go
pkg/controllers/deprovisioning/emptynodeconsolidation.go

Fixes #N/A 
This change updates the filename and constructor for `emptynodeclaimconsolidation` to be `emptynodeconsolidation`

chore: Rename filename for empty node consolidation

---

pkg/controllers/deprovisioning/emptynodeconsolidation.go
pkg/controllers/deprovisioning/machine_consolidation_test.go
pkg/controllers/deprovisioning/nodeclaim_consolidation_test.go
pkg/controllers/deprovisioning/validation.go

Fixes https://github.com/aws/karpenter/issues/4310, https://github.com/aws/karpenter/issues/4758
This PR correctly validates that the candidates that we are attempting to deprovision are still eligible to be deprovisioned. It does this by mapping the old candidates onto the new candidates that we pull from state and checking that all of those candidates are still valid for deprovisioning based on PDB criteria, `do-not-evict` annotations, and scheduling criteria.
This PR also removes the caching mechanism for `validationCandidates` since we weren't calling `IsValid` multiple times in code, meaning that storing the candidates like this wasn't necessary for our usage.
https://github.com/aws/karpenter-core/pull/247 had originally intended to fix this issue, but uses the wrong …

fix: Fix using the wrong pods when validating `do-not-evict` pods

---

pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/test/environment.go

Fixes #N/A 
- Since k8s 1.25 will be the only version of karpenter that will support CEL, remove the testing for earlier versions 

test: Remove CEL unit testing for 1.23 and 1.24

---

pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go
pkg/test/expectations/expectations.go

Fixes #567 
- Provisioning can hang when AWSNodeTemplate doesn't exist and Karpenter is restart, this will block karpenter from provisioning and deprovisioning nodes 
- Manually tested

fix: Sync nodes that are Initialized from cluster state

---

pkg/operator/logging/logging.go

Fixes #N/A 
This PR fixes calling named on logger twice which would result in logs that contained `controller.controller` and `webhook.webhook` as a prefix
```bash
2023-10-12T19:38:19.004Z        DEBUG   controller      loaded log configuration from file "/etc/karpenter/logging/zap-logger-config"   {"commit": "fae826c"}
2023-10-12T19:38:21.658Z        DEBUG   controller.controller   discovered region       {"commit": "fae826c", "region": "us-west-2"}
2023-10-12T19:38:21.664Z        DEBUG   controller.controller   discovered kube dns     {"commit": "fae826c", "kube-dns-ip": "10.100.0.10"}
2023-10-12T19:38:21.665Z        DEBUG   controller.controller   discovered version      {"commit": "fae826c", "version": "v0.31.0-67-gfae826cc7"}
2023-10-12T19:38:21.666Z        INFO …
```

chore: Fix calling the named function on the logger twice

---

pkg/controllers/termination/terminator/eviction.go

Fixes #598 
Adds a check into the termination queue before calling `rateLimitingInterface.Get()` so that Karpenter can only call the rateLimitingInterface.Get() call if there's items in the queue. Calling Get() will wait until there's items in the queue, where it'll block Karpenter from shutting down until the shut down times out.
- make apply
- Ran `kubectl rollout restart deployment karpenter -n karpenter` a couple of times to see it not time out. 

fix: allow queue to clean up if not evict pods

---

pkg/operator/logging/logging.go

Fixes #N/A 
This PR ensures that the controller-runtime logger is configured so that logs properly appear from controller runtime
```console
{"commit": "be86a6f-dirty"}
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 2291 [running]:
>  runtime/debug.Stack()
>       runtime/debug/stack.go:24 +0x5e
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>       sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/log.go:60 +0xcd
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc0002bd400, 0x10?)
>       sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/deleg.go:111 +0x32
>  github.com/go-logr/logr.Logger.Enabled(...)
>       github.com/go-logr/logr@v1.2.4/logr.go:261
> …
```

chore: Ensure controller-runtime logger is configured

---

pkg/controllers/deprovisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go
pkg/utils/nodeclaim/nodeclaim.go

Fixes #N/A 
This PR makes a change so that reconciliations do not fail if you create some NodePools and NodeClaims with v1beta1 and then choose to rollback to an earlier version of Karpenter where these concepts are not understood.
`make apply`

fix: Handle NodeClaims existing but being unknown in earlier versions

---

pkg/controllers/controllers.go
pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/drift.go
pkg/controllers/disruption/emptiness.go
pkg/controllers/disruption/emptynodeconsolidation.go
pkg/controllers/disruption/events/events.go
pkg/controllers/disruption/expiration.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/machine_consolidation_test.go
pkg/controllers/disruption/machine_drift_test.go
pkg/controllers/disruption/machine_emptiness_test.go
pkg/controllers/disruption/machine_expiration_test.go
pkg/controllers/disruption/metrics.go
pkg/controllers/disruption/multinodeconsolidation.go
pkg/controllers/disruption/nodeclaim_consolidation_test.go
pkg/controllers/disruption/nodeclaim_drift_test.go
pkg/controllers/disruption/nodeclaim_emptiness_test.go
pkg/controllers/disruption/nodeclaim_expiration_test.go
pkg/controllers/disruption/pdblimits.go
pkg/controllers/disruption/singlenodeconsolidation.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/types.go
pkg/controllers/disruption/validation.go
pkg/controllers/nodeclaim/consistency/termination.go

Fixes #N/A 
This PR changes the name of the deprovisioning controller to the disruption controller to match the `spec.disruption` block in the NodePool and aligns metrics with this naming convention:
1. `disruption_evaluation_duration_seconds`
2. `disruption_replacement_nodeclaim_initialized_seconds`
3. `disruption_replacement_nodeclaim_failures_total`
4. `disruption_actions_performed_total`
5. `disruption_eligible_nodes`
6. `disruption_consolidation_timeouts_total`

chore: Change deprovisioning to disruption controller and add metrics

---

pkg/controllers/disruption/controller.go

Fixes #N/A 
This PR fixes a couple of places in the disruption code where the entire method struct was printed out rather than just the type of the method

chore: Fix a couple misses where the entire disruption method was printed

---

pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/metrics.go

Fixes #N/A 
Adds in the node pool name label key into the termination metric that was left out of the previous metrics migration PRs.

fix: add in v1beta1 termination metrics label

---

pkg/apis/settings/settings.go
pkg/operator/injection/injection.go
pkg/operator/options/options.go

Fixes #N/A 
This PR changes the injection behavior such that `settings` are always injected into the context, even when the `karpenter-global-settings` configmap is not present. In that case, the default settings are injected.

chore: always inject settings

---

pkg/controllers/disruption/machine_consolidation_test.go
pkg/controllers/disruption/machine_emptiness_test.go
pkg/controllers/disruption/nodeclaim_consolidation_test.go
pkg/controllers/disruption/nodeclaim_emptiness_test.go
pkg/controllers/disruption/suite_test.go

Fixes #N/A 
Some parts of the test were missing mistakenly ```wg.wait()```  after adding ```wg.add()``` this might not be the case we want in terms of concurrency.
This pr attempts to fix that
```make presubmit```

test: Handling concurrency for disruption controller tests

---

pkg/operator/injection/injection.go
pkg/operator/options/injectable.go
pkg/operator/options/options.go
pkg/operator/options/suite_test.go

Fixes #N/A 
This PR adds a wrapper to `BoolFunc` which enables merging CLI flags with environment variables correctly. With the previous implementation, the following is possible:
```
DISABLE_WEBHOOK=true ./karpenter --disable-webhook
```
This is because of the way that `flag` handles default values for booleans. 
`make test`

chore: correctly parse boolean CLI flags

---

pkg/operator/operator.go

Fixes #N/A 
This PR enables version to be specified and injected during the binary build to log the version and add the version to the userAgent that is stored in the metadata information when Karpenter makes calls to the apiserver.
You can inject the version when you build the binary by running the following:
```bash
go build cmd/controller/main.go GOFLAGS="-ldflags=-X=github.com/aws/karpenter-core/pkg/operator.Version=$(shell git describe --tags --always)"
```
`make apply`

chore: Enable userAgent version specification in operator

---

pkg/controllers/node/termination/controller.go
pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/garbagecollection/controller.go
pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/state/informer/daemonset.go

Fixes #N/A 
Since controller-runtime https://github.com/kubernetes-sigs/controller-runtime/pull/2451, a warning will be logged if a controller returns an error and a non-zero result (i.e. a result with a RequeueAfter).
This PR changes the logic of our current controllers to not return both a non-zero result and an error at the same time to prevent warnings from being fired.
```bash
2023-10-20T01:28:53.2764885Z     logger.go:130: 2023-10-20T01:28:53.275Z	INFO	common/expectations.go:573	2023-10-20T01:28:49.102Z	DEBUG	controller.awsnodetemplate	discovered security groups	{"commit": "dce7385", "awsnodetemplate": "serpentsunset-29-ahjs7gn4mu", "security-groups": ["sg-0273da947dae25bb0", "sg-09513f2623d9d9b79"]}
2023-10-20T01:28:53.2773218Z         2023-10-20T01:28:49.158Z	INFO …
```

chore: Fix returning non-empty reconcile result and error

---

pkg/apis/v1beta1/nodeclaim_validation.go
pkg/controllers/provisioning/nodepool_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/provisioner_test.go

Fixes #N/A 
This PR adds the ability to use the `karpenter.sh/nodepool` on nodeSelectors and nodeAffinities. This change also validates the `nodeSelector` alongside the node affinities that we already validate

chore: Allow the `karpenter.sh/nodepool` labelSelector and validate nodeSelector on pods

---

pkg/controllers/metrics/nodepool/controller.go
pkg/controllers/metrics/nodepool/suite_test.go

Fixes #N/A 
This change drops the usage percentage metric for NodePools since this metric can be formed by combining the `nodepool_usage` and `nodepool_limits` metrics today
`make presubmit

chore: Drop usage pct metric for nodepool

---

pkg/controllers/nodeclaim/consistency/machine_test.go
pkg/controllers/nodeclaim/consistency/nodeclaim_test.go
pkg/controllers/nodeclaim/consistency/nodeshape.go

Fixes #N/A 
- Only consider the node shape for requested resources. This means that we will only do resource checks when we know that a node's pods have specifically asked for certain resources during scheduling. This ensures that extended resources are only checked if the pod specifically asks for these resources.

chore: Only consider node shape for requested resources

---

.github/actionlint-matcher.json
.github/workflows/presubmit.yaml
.golangci.yaml
Makefile
hack/toolchain.sh

Fixes #N/A 
Add linting for GHA workflows
`actionlint` does not currently support composite action checking but this feature appears to be in the works (https://github.com/rhysd/actionlint/pull/366). When that feature is implemented, we could also add that feature to our CI
`actionlint -oneline`

Add GHA linting

---

pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodepool.go

Fixes #N/A 
- Require `nodepool.spec.template` to exist  
- Manually tested 

fix: Require `nodepool.spec.template`

---

.github/workflows/presubmit.yaml
hack/toolchain.sh

Fixes #N/A 
- Update to use https://github.com/mattn/goveralls directly

ci: Use `mattn/goveralls` instead of `shogo821/goveralls`

---

.github/workflows/presubmit.yaml

Fixes #N/A 
Description
- Due the multiple runs of the CI-test goveralls was failing to send reports.
How was this change tested?
- N/A

ci: Scope goveralls to one k8s version of `presubmit` 

---

pkg/apis/v1beta1/nodeclaim_validation.go

Fixes https://github.com/aws/karpenter/issues/5051
This removes the `Delete` verb that was currently being used for the NodeClaim mutating webhook

chore: Remove delete from supported verbs in NodeClaims

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/cluster.go
pkg/controllers/state/informer/nodeclaim.go
pkg/test/expectations/expectations.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/suite_test.go

Fixes #N/A 
This PR drops the `nodeclaim.Key` concept from provisioner, disruption, and state in favor of the NodeClaim name

chore: Drop `nodeclaim.Key` from provisioner, disruption, and state

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/suite_test.go

Fixes #N/A 
This limits the queue depth of the orchestration controller to 1 until budgets is released to properly gate disruption.
make presubmit

chore: limit queue depth to 1

---

.golangci.yaml
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/provisioner_test.go

Releated to https://github.com/aws/karpenter/issues/5055
This PR ensures that `RuntimeValidate()` calls only run against NodePools since Provisioners should be validated using the webhooks and we shouldn't have the same validation logic that we use against NodePools happening against Provisioners
`make apply`

fix: Fix `RuntimeValidate` check to only check NodePools

---

.github/workflows/presubmit.yaml
.github/workflows/release.yaml

Fixes #N/A 
This PR assumes that the default permissions for the `GITHUB_TOKEN` is read-only for all permission in the account. Outside of that, we specify the constrained set of permissions that are required for each job to execute against the repo. This includes `issues: write` permissions for the Presubmit task for writing the coveralls output to the PR and `contents: write` permission for the Release task for creating the release.
- Opening a PR against the `karpenter-core` repo

ci: Constrain action permissions

---

.github/actions/install-deps/action.yaml
.github/workflows/presubmit.yaml
.github/workflows/release.yaml
.github/workflows/stale.yaml

Fixes #N/A 
This PR pins all of our third-party actions to a full-length SHA to ensure they are not vulnerable to a supply-chain attack. This is the best practice for third-party GHA as described here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

ci: Pin Github Action versions to hashes

---

.github/workflows/release.yaml

Fixes #N/A 
This PR adds the last version pin to pin the `action-automatic-releases` action to the latest static hash version pin

ci: Pin `action-automatic-releases` action

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
OWNERS
OWNERS_ALIASES
README.md
SECURITY.md
SECURITY_CONTACTS
code-of-conduct.md

Fixes #N/A 
Add Kubernetes template files from https://github.com/kubernetes/kubernetes-template-project inline with the requirements for https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories as part of the issue for Karpenter to migrate to the `kubernetes-sigs` organization: https://github.com/kubernetes/org/issues/4562

docs: Add kubernetes template files

---

pkg/apis/v1beta1/nodepool.go
pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/types.go
pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/garbagecollection/controller.go
pkg/controllers/nodepool/counter/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/statenode.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/suite_test.go
pkg/utils/nodepool/nodepool.go

Fixes #N/A 
This PR drops the `nodepool.Key` that was used to differentiate NodePools from Provisioners when they were modeled as the same entity in memory. Now that they are no longer modeled together, we can drop this key concept

chore: Drop NodePool Owner Key from codebase

---

OWNERS_ALIASES

Fixes #N/A 
The following contributors were originally part of the original approvers list but did not have membership in `kubernetes-sigs`. These contributors now have membership and can be added back to the `OWNERS_ALIASES` file:
1. @engedaam - https://github.com/kubernetes/org/issues/4595
2. @jmdeal  - https://github.com/kubernetes/org/issues/4593

chore: Add back approvers with `kubernetes-sigs` membership

---

pkg/operator/injection/injection.go
pkg/operator/injection/suite_test.go
pkg/operator/logging/suite_test.go

Fixes #827
This PR fixes the ConfigMap waiter so that it's using the correct context (the cancelContext) when it's checking for the existence of the `karpenter-global-settings` ConfigMap. This should allow timeout so that we can proceed to run Karpenter without the existence of this ConfigMap.
`make apply`

chore: Fix configmap waiter for `karpenter-global-settings`

---

pkg/operator/options/options.go

Fixes #N/A 
This drops the unneeded `setFlags` parameter from the options parsing now
`make apply`

chore: Drop `setFlags` from options parsing

---

hack/toolchain.sh

Fixes #803  
This PR downloads kube-apiserver v1.25.16 for use with envtest when running CI jobs for k8s 1.25. 
Running GitHub actions after opening the PR.

ci: use kube-apiserver v1.25.16 for k8s 1.25 CI

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature.yaml

Fixes #N/A 
Updates the issue templates to use the `kind/*` labels and add the `needs-triage` label by default.
N/A

ci: update issue templates

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/scheduling/volumetopology.go
pkg/controllers/provisioning/suite_test.go
pkg/scheduling/volumeusage.go
pkg/test/storage.go
pkg/utils/volume/volume.go

Fixes #664 
Karpenter doesn't correctly handle two StorageClass cases: when the StorageClass is **explicitly** `""` and when the StorageClass does not exist. A pod with a PVC that falls into one of these cases should be able to successfully schedule if the PVC is already bound to a PV. Additionally, currently Karpenter treats both a `nil` StorageClass and `""` StorageClass as the default StorageClass. This should only be the case when the StorageClass is `nil`.
`make test`

fix: correctly handle non-existent / empty StorageClasses

---

pkg/utils/volume/volume.go

Fixes #N/A 
Update the license callout in `pkg/utils/volume/volume.go` to reflect repo migration to kubernetes-sigs.
N/A

chore: update license notice for volume util

---

pkg/operator/operator.go
pkg/operator/suite_test.go

Fixes #N/A 
This change moves a merged PR from `aws/karpenter-provider-aws` into the common `karpenter` code. This change exposes build information through a Prometheus metric. The change was originally merged with: https://github.com/aws/karpenter-provider-aws/pull/5213 and is being transported into the common surface.
`make apply` on AWS with Prometheus

chore: Move the `karpenter_build_info` metric to karpenter

---

pkg/operator/operator.go
pkg/operator/suite_test.go

Fixes #665
This is an improvement to **karpenter_build_info** Prometheus metric, added recently in https://github.com/aws/karpenter-provider-aws/pull/5213 and then moved to common Karpenter code https://github.com/kubernetes-sigs/karpenter/pull/851
I think it's convenient to also have arch of the node on which Karpenter runs.
Ran go test in pkg/operator, all passed.

chore: Add goarch label to karpenter_build_info Prometheus metric

---

.github/workflows/codeql-analysis.yaml
.github/workflows/stale.yaml

Fixes #N/A 
This change adds CodeQL scanning for Github Actions specified in this repo to check for things like Github Action pinning and script injection. More details here: https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure/#2-enable-code-scanning-for-workflows
Create script injection vulnerabilities on fork and test that CodeQL can catch these

ci: Enable codeql for github actions

---

pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/suite_test.go
pkg/controllers/provisioning/suite_test.go

Fixes #N/A 
This changes the ordering of NodePools and their sorting so that NodePools of equal weight are always moved in front of Provisioners. This particularly helps with the migration story, where we want the same NodePool that has the same weight as Provisioner to always come first

chore: Fix consistent ordering of NodePools and Provisioners

---

pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/emptiness.go
pkg/controllers/disruption/emptiness_test.go

Fixes #N/A 
This drops the "Consolidation disabled" event when we have `consolidationPolicy: WhenEmpty`. This error is confusing for users since (from their perspective), consolidation is in fact enabled with the `consolidationPolicy`

chore: Drop events for consolidation disabled when we have a different policy

---

pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodepool/hash/controller.go

Fixes #N/A 
If a user removes the hash from the nodepool, the hash won't be added again until another event occurs, this could prevent drift from happening
There are four other controllers that filter out update events that don't modify the spec, which are all the correct behavior. One difference is we'll now enqueue for the nodeclaim/disruption controller so that if a user removes the status condition on a nodeclaim, we'll add it back in if necessary.
tested manually

fix: remove event filter for nodepool hash controller

---

pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/disruption/expiration.go
pkg/controllers/nodeclaim/disruption/expiration_test.go

Fixes #N/A 
This changes the expiration to refer to the nodeclaim creation timestamp rather than conditionally referring to the node if it exists. This follows the model of emptiness and drift, where we only reason about the nodeclaim as the source of truth for the node for the purpose of disruption conditions.
make presubmit

chore: remove nodeclaim disruption controller node watcher

---

pkg/controllers/disruption/controller.go

Fixes #N/A 
On shutdown, we were getting panics since we weren't returning after a failed nodePool.List call.
make presubmit

fix: don't panic on shutdown for nil nodepools for logging budgets

---

RELEASE.md

Fixes #841
This change adds the `RELEASE.md` file as called-out by the migration requirements for the K8s template project here: https://github.com/kubernetes/org/issues/4562#issuecomment-1841983174.

docs: Add `RELEASE.md` documentation

---

pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodeclaim/disruption/emptiness_test.go
pkg/controllers/nodeclaim/disruption/expiration_test.go
pkg/utils/nodeclaim/nodeclaim.go

Fixes #N/A 
The `karpenter_nodeclaims_drifted` metric was coming through the `karpenter_nodeclaims_disrupted` metric due to a typo and a lack of testing around these metrics.
This change adds testing around the disruption metrics and ensures that we correctly fire the `karpenter_nodeclaims_drifted` metric

chore: Fix `karpenter_nodeclaims_drifted` metric

---

.github/workflows/codeql-analysis.yaml
.github/workflows/presubmit.yaml
.github/workflows/release.yaml
.github/workflows/stale.yaml

Fixes #N/A 
Ref. https://github.com/kubernetes-sigs/karpenter/issues/876
The `GITHUB_TOKEN` is an automatically generated secret to make authenticated calls to the GitHub API. GitHub recommends setting minimum token permissions for the `GITHUB_TOKEN`. Current configuration seems to be secure, but there is a chance that when a new job is added to one of the workflows, its job permissions could be left undefined because of human error. We can prevent that by setting permissions definitions in each workflow's yaml file as read-only at the [top level](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions).
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a- …

ci(workflows): least privileged token permissions

---

pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodeclaim/disruption/emptiness_test.go
pkg/controllers/nodeclaim/disruption/expiration_test.go
pkg/utils/nodeclaim/nodeclaim.go

Fixes #N/A 
This cherry-picks #875 into `v0.33.x`

fix: Fix `karpenter_nodeclaims_drifted` metric for `v0.33.x`

---

pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/suite_test.go

Fixes #N/A 
This cherry-picks over #860 into `HEAD`

chore: Fix consistent ordering of NodePools and Provisioners (#860) into `HEAD`

---

pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/suite_test.go

Fixes #N/A 
This cherry-picks over #860 into `v0.33.x`

chore: Fix consistent ordering of NodePools and Provisioners (#860) for `v0.33.x`

---

pkg/operator/operator.go

Fixes #N/A 
This change updates the leader election to actively release the lease when it is shutting down using controller-runtime's `LeaderElectionReleaseOnCancel`. This ensures that if one of the Karpenter pods ever dies, as long as the pods is able to still communicate with the apiserver, the lease hand-off is dropped down to milliseconds.
```
{"level":"INFO","time":"2023-12-20T05:13:18.270Z","logger":"controller","message":"Wait completed, proceeding to shutdown the manager","commit":"403f1ad"}
```
```
{"level":"INFO","time":"2023-12-20T05:20:11.608Z","logger":"controller","message":"successfully acquired lease kube-system/karpenter-leader-election","commit":"403f1ad"}
```
__Total Time Between Handoff__: ~7s
``` …
```

chore: Release leader election in manager config

---

.github/workflows/release.yaml

Fixes #876 `Task-4` - Security Slam
This PR ensure SLSA Attestations are Generated when Possible. Checkout this [doc](https://docs.google.com/document/d/1TLahqW6OpWQXbaVJ-SR8z-o0yLSoGKYTHxPU0PyyjXo/edit?pli=1) for reference.
// @jonathan-innis 

Ensure SLSA Attestations are Generated when Possible

---

.github/workflows/release.yaml

Fixes #N/A 
Fixes a failure generated by the release attestation added here: #889 by ensuring that we generate the attestation for the release after we have created the release.
Manually tagging and generate attestation in fork

ci: Fix tejolote release attestation step

---

pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/drift_test.go
pkg/controllers/disruption/emptiness_test.go
pkg/controllers/disruption/expiration_test.go
pkg/controllers/disruption/metrics.go

Fixes #N/A 
Adds metric to track how many disruptions are allowed for each disruption loop. 
make presubmit

feat: add metric for disruption budgets

---

.github/workflows/stale.yaml

Fixes #N/A 
Drops `kind/support` from the set of exempt labels to close-out stale questions and use only `kind/*` labels for staleness categorization

ci: Drop `kind/support` from exempt and only use kind labels for exemption

---

Makefile
hack/install-kwok.sh

Fixes #N/A 
This adds in a hack/kwok-install.sh script that will allow users to install Kwok with 10 partitions in their cluster. 10 partitions are needed as Kwok has [scalability limitations](https://github.com/kubernetes-sigs/kwok#:~:text=Lightweight%3A%20You%20can%20simulate%20thousands%20of%20nodes%20on%20your%20laptop%20without%20significant%20consumption%20of%20CPU%20or%20memory%20resources.%20Currently%2C%20KWOK%20can%20reliably%20maintain%201k%20nodes%20and%20100k%20pods%20easily.)
This kwok-install.sh script can be improved by doing kustomization to only apply 10 different deployments, rather than 10 copies of all objects associated with the manifest. 
Related: https://github.com/kubernetes-sigs/karpenter/issues/895
`make …

feat: add kwok install hack script

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
This calls `clusterState.UpdateNodeClaim` when Karpenter creates new node claims to ensure that Karpenter is aware of nodes that are being created immediately, avoiding eventual consistency delay races with the controller-runtime cache. 
make presubmit

fix: add manual nodeclaim update into cluster state for new nodes

---

pkg/controllers/disruption/helpers.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go
pkg/scheduling/taints.go

Fixes #N/A 
This PR changes the ephemeral taints logic that we use for removing certain taints for consideration when nodes managed by Karpenter haven't yet initialized. This changes the logic so that this logic doesn't also apply to unmanaged nodes as well as ensuring that we only consider these taints _up_ to the point that the node initializes. Once a node has reached its initialization point, we will begin considering these taints.
This PR drops an additional check that is unneeded now that we are no longer on a migration path. Nodes that would fall under the additional check (that is -- nodes that would have the `karpenter.sh/nodepool` label but don't have an associated NodeClaim) will only exist when the NodeClaim is deleted _immediately_ after creation (since the …

chore: Update ephemeral taints logic and drop unmanaged check on nodes

---

designs/kwok-provider.md

Fixes #N/A 
Adds in the docs guide that will be referenced for the kwok cloud provider. Goes into the ideas of why the specific instance types were picked. 
Related: https://github.com/kubernetes-sigs/karpenter/issues/895

RFC: add in kwok design living doc

---

Makefile
hack/validation/resources.sh
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodepool_validation_cel_test.go

Fixes #955  
- The NodePool field `spec.template.spec.resources` was unintentionally allowed to be set by users on the NodePool. The correct validation is captured by the webhook validation, but was missed for OpenAPI validation. This PR adds the correct validation for the OpenAPI validation
-  Currently, the field is an undocumented and not utilized by the `NodePool` 
- Unit testing

BREAKING CHANGE: Disallow resources to be in the `NodePool`

---

pkg/controllers/provisioning/scheduling/topology.go
pkg/utils/pretty/pretty.go

Fixes #N/A 
This particularly helps with pod anti-affinities. I modified the benchmark to have 500 self anti-affinity pods and this improves the performance by 1000% at 500 pods/nodes. The more nodes, the better the improvement.
name              old pods/sec  new pods/sec  delta
Scheduling500-12     15.3 ±10%    171.3 ± 7%  +1022.36%  (p=0.008 n=5+5)
Benchmarking

perf: improve scheduling with large numbers of nodes using hostname topologies

---

pkg/controllers/provisioning/scheduling/topologygroup.go

Fixes #N/A 
Tracking empty domains separately allows for more efficient anti-affinity checks when there are no empty domains.  This is a frequent operation when doing a large scale up of a deployment with self anti-affinity.
Using benchmarks with anti-affinity pods only, scheduling performance increases greatly:
```
name               old pods/sec  new pods/sec  delta
Scheduling1-12        71.4 ±62%    304.0 ±13%  +326.11%  (p=0.008 n=5+5)
Scheduling50-12       49.2 ±12%    295.2 ± 3%  +499.63%  (p=0.008 n=5+5)
Scheduling250-12       236 ± 4%      455 ± 3%   +92.83%  (p=0.008 n=5+5)
Scheduling500-12       226 ± 7%      364 ± 1%   +61.51%  (p=0.008 n=5+5)
Scheduling1000-12     74.4 ± 4%    349.6 ± 1%  +370.05%  (p=0.008 n=5+5)
Scheduling2000-12     21.7 ± 1%    186.8 ± 1% …
```

perf: track empty domains separately in topology

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/emptynodeconsolidation.go
pkg/controllers/disruption/events/events.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/validation.go

Fixes #N/A 
This adds an event that is emitted for a NodePool whenever there are currently 0 allowed disruptions. This is to allow users to monitor kube-events on their cluster to see if Karpenter thinks their budget is reached.
make presubmit

feat: add disruption event for a fully blocking budget

---

pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/controllers/provisioning/scheduling/topologynodefilter.go
pkg/scheduling/requirements.go

Fixes #N/A 
AKS provider had a [pr](https://github.com/Azure/karpenter-provider-azure/pull/112) raised outlining some typos in the repo. Since then we added a typo linter but still will see the upstream typo show up so adding small pr to fix.
- go test in target repo

chore: typo in compatibility

---

pkg/controllers/disruption/orchestration/queue.go

Fixes #N/A 
This adds the nodeclaim name into the log. Previously this error could return something like the following, which gives no information about which node claims it was expecting to be initialized.
```
failed to disrupt nodes, command reached timeout after {duration}; waiting for replacement initialization, node claim not initialized; node claim not initialized; node claim not initialized; node claim not initialized
```
make presubmit

feat: add nodeclaim name into orchestration initialization failures

---

Makefile
pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/emptynodeconsolidation.go
pkg/controllers/disruption/multinodeconsolidation.go
pkg/controllers/disruption/singlenodeconsolidation.go

Fixes #N/A 
Fixes a bug where we would mark the cluster as consolidated if budgets caused Consolidation to not occur. We only want to mark a cluster as consolidated if budgets aren't restricting the candidate set. 
make presubmit

fix: don't mark cluster consolidated if constrained by budgets

---

pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/suite_test.go
pkg/test/expectations/expectations.go

Fixes #N/A 
Karpenter will now consider unhealthy nodes when consider budgets, decrementing the total allowed disruptions if the node is Not Ready.
make presubmit

feat: consider not ready nodes for budgets

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/orchestration/suite_test.go

Fixes #N/A 
Adds a types.UID that's attached to a command in memory. This allows us to log this uid on command creation, and track it when the command eventually fails or succeeds.
make apply

feat: add uid for orchestration queue for logs

---

pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/drift.go
pkg/controllers/disruption/emptiness.go
pkg/controllers/disruption/emptynodeconsolidation.go
pkg/controllers/disruption/expiration.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/multinodeconsolidation.go
pkg/controllers/disruption/pdblimits.go
pkg/controllers/disruption/singlenodeconsolidation.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/types.go
pkg/controllers/disruption/validation.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/terminator.go
pkg/controllers/nodeclaim/consistency/controller.go
pkg/controllers/nodeclaim/consistency/suite_test.go
pkg/controllers/nodeclaim/consistency/termination.go
pkg/controllers/nodeclaim/disruption/emptiness.go
pkg/controllers/nodeclaim/disruption/emptiness_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/statenode.go
pkg/test/expectations/expectations.go
pkg/test/statefulsets.go
pkg/utils/node/node.go
pkg/utils/pod/scheduling.go

Fixes #643
Fixes #863
This PR creates the following node helper functions to grab the pods on the cluster or attached to nodes:
1. `IsActive()` - This filtering function is used for PDBs and `karpenter.sh/do-not-disrupt` checking to evaluate if a node can be determined based on the active pods that are running on it
2. `IsReschedulable()` - This filtering function is used by the provisioner to determine the pods that we should attempt to reschedule based on the pods that are currently scheduled to the existing node
3. `IsEvictable()` - This filtering function is used by the node terminator and for PDB evaluation to determine the pods that can be evicted based on whether the pod is a mirror pod, is terminating, is already completed, or tolerates the disruption taint such …

fix: Create Generic Pod Filtering in Utils and Collapse Disruption Filtering

---

pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/drift.go
pkg/controllers/disruption/expiration.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/validation.go
pkg/test/expectations/expectations.go

Fixes #N/A 
When considering deleting pods for scheduling simulations, we won't fail to disrupt if the pods that scheduled to uninitialized nodes were from an already deleting node. This is because they'll either be a node from a previous disruption command or a manually deleted node, either one of which we should assume is being disrupted and getting a replacement node as needed from the disruption or provisioning controller.
make presubmit

fix: allow disruption when considering past disruption commands

---

go.mod
go.sum
kwok/main.go
pkg/controllers/controllers.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go

Fixes #N/A 
This change ensures that when we attempt to evict a pod, we don't accidentally evict a pod with a namespaced name that was recently re-created and shifted onto another node. This is particularly critical for StatefulSets, where pods can be re-created quickly with the same name. 

fix: Use UUID as a precondition when calling the eviction API

---

pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_webhook_test.go

Fixes #1003
Budget validation for CEL wasn't properly catching the case where one budget had properly set the schedule and duration together but another hadn't. This change ensures that _every_ budget has set a valid combination of schedule and duration

fix: Fix budget validation through CEL

---

designs/nodepool-requirement-flexibility.md

Fixes #N/A 
This RFC proposes a change where users can pass through `minValues` into their different requirement block keys to ensure that Karpenter maintains their request minimum flexibility requirements as it is scheduling pods to nodes. This is useful to maintain spot flexibility when Karpenter is launching new nodes.

RFC: Propose `minValues` to enforce Flexibility on NodeClaim Requests

---

go.mod
go.sum
pkg/controllers/controllers.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go

Fixes #N/A 
Cherry-pick over https://github.com/kubernetes-sigs/karpenter/pull/998 onto release-v0.32.x branch

fix: Use UUID as a precondition when calling the eviction API (#998)

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/scheduling/requirements.go
pkg/scheduling/requirements_test.go
pkg/utils/resources/resources.go

Fixes #N/A 
A few changes that overall increase performance 10-60% depending on the number of pods/nodes. Its around a ~34% overall improvement:
```
name               old pods/sec  new pods/sec  delta
Scheduling1-12       3.89k ± 2%    4.36k ± 4%  +12.10%  (p=0.000 n=10+9)
Scheduling50-12      1.44k ±11%    1.70k ± 5%  +18.29%  (p=0.000 n=9+9)
Scheduling100-12     1.30k ±10%    2.09k ± 3%  +60.63%  (p=0.000 n=9+9)
Scheduling500-12     1.47k ± 3%    2.06k ± 1%  +40.65%  (p=0.000 n=8+9)
Scheduling1000-12    1.42k ± 5%    1.99k ± 1%  +39.32%  (p=0.000 n=10+10)
Scheduling2000-12    1.43k ± 1%    1.83k ± 2%  +28.36%  (p=0.000 n=9+9)
Scheduling5000-12    1.09k ± 6%    1.67k ± 2%  +53.75%  (p=0.000 n=9+10)
```
Benchmarking and unit testing/
By …

perf: increase scheduler performance

---

pkg/controllers/state/cluster.go
pkg/controllers/state/metrics.go
pkg/controllers/state/suite_test.go
pkg/metrics/metrics.go
pkg/test/expectations/expectations.go

Fixes #276 
Adding gauge metrics of the cluster state node total that are updated on each UpdateNode, and DeleteNode request, alongside a is_synced metric that is updated in each Synced call. 
- Unit tests 
- Validated metrics work on AKS + KWOK Cluster

 feat: adding karpenter_state_nodes_total metric and karpenter_state_synced

---

Makefile
pkg/controllers/leasegarbagecollection/controller.go
pkg/controllers/leasegarbagecollection/metrics.go
pkg/controllers/leasegarbagecollection/suite_test.go
pkg/controllers/nodeclaim/disruption/suite_test.go
pkg/operator/options/suite_test.go

Fixes #N/A 
From reviewing the code and testing, it isn't necessary to specify both of `--ginkgo.timeout` and `--timeout`. This drops the former to prefer the suite-based timeout with `go test`
This change also adds the `--ginkgo.randomize-all` CLI flag to ensure that we aren't missing any test flakiness due to implicit ordering in our testing.

ci: Drop `--ginkgo.timeout` and add `--ginkgo.randomize-all` CLI arg for Makefile target

---

pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/consolidation_test.go

Fix an issue where the instanceTypes aren't sorted before truncating it for spot-to-spot consolidation.
As part of spot-to-spot consolidation algorithm (ref: [here](https://github.com/kubernetes-sigs/karpenter/pull/768/files)), we check for minimum flexibility of the instance types and if it is greater than 15, we allow spot-to-spot consolidation. To avoid continual consolidation, we were supposed to sort the spot instance types by prices and truncate the list to 15 instance types to be sent to launch API.
The sorting of spot instance types by prices was missed and this fixes the issue.
Added a functional test. Tested with and without the fix. It fails when the sorting is not place. …

fix: Fix an issue where the instanceTypes aren't sorted before truncating it for spot-to-spot consolidation.

---

pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/suite_test.go

Fixes #N/A 
`Add()`, `Delete()`, and `Reset()` weren't gated by a mutex after we changed the package that we were using for sets to align with our other set packages

fix: Add locking/unlocking to set `Add()`, `Delete()`, and `Reset()`

---

pkg/controllers/node/termination/terminator/suite_test.go

Fixes #N/A 
Because we were running an async flow to try to force a DATA RACE if the locking/unlocking wasn't working properly for the set, we were now causing a Reconcile() to happen while we were calling `Reset()` since we weren't waiting for the goroutine to finish 

test: Fix data race while calling `Reset()` in CI testing

---

pkg/controllers/nodeclaim/disruption/expiration_test.go

Fixes #N/A 
This fixes a flake in the `requeueAfter` returned from a test in the NodeClaim Disruption controller. This ensures that the expiry time is always 100 seconds away from the current time.

test: Fix flake in requeueAfter returned from expiration disruption

---

pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/registration.go

Fixes #N/A 
Ensure that we report the actual node allocatable in our "initialized nodeclaim" call. This also bumps the "registered nodeclaim" call to the Info level since it's a critical point in the NodeClaim's lifecycle
This also makes it a bit clearer from looking at the log data on the difference between what Karpenter thinks is going to be the allocatable of the node after it launches and what it actually is
```
{"level":"INFO","time":"2024-02-16T23:28:55.484Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"ccbc1b0-dirty","nodeclaim":"default-gmsh2","provider-id":"aws:///us-west-2b/i-02ce789377dd5fe6f","instance-type":"m6a.2xlarge","zone":"us-west-2b","capacity-type":"on-demand","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi" …
```

chore: Report node allocatable capacity as part of log on register/initialize

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/drift.go
pkg/controllers/disruption/emptiness.go
pkg/controllers/disruption/emptynodeconsolidation.go
pkg/controllers/disruption/expiration.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/metrics.go
pkg/controllers/disruption/multinodeconsolidation.go
pkg/controllers/disruption/singlenodeconsolidation.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/types.go
pkg/test/expectations/expectations.go

Fixes #N/A 
This adds a disrupted reschedulable pod count metric along with a disrupted node count metric. This also adds a pod count to the log that is printed when we disrupt nodes. This would help in debugging issues like in #1014 where it's tough to tell if a node is terminated with nodes bound or not. 

chore: Add pod/node count to metrics and logs for disruption

---

pkg/controllers/node/termination/suite_test.go

Fixes #N/A 
This fixes a missed `BeTrue()` that should have been present in our testing

test: Fix missed `BeTrue()` in testing

---

pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
This change updates the scheduler testing to ensure that `maxInstanceTypes` is reset at the beginning of each test so that changing this value throughout a single test doesn't affect subsequent tests.

test: Ensure that MaxInstanceTypes is reset at the beginning of each test

---

pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodepool.go

Fixes #N/A 
We've seen some Karpenter users running into issues with NodePool or NodeClaim applies, specifically when the spec isn't present. If you apply the NodePool or NodeClaim without a spec, you can circumvent the other checking, we should just require the spec.
One example issue that we hit in the AWS provider repo is here: https://github.com/aws/karpenter-provider-aws/issues/5689
`kubectl apply -f pkg/apis/crds && kubectl apply -f nodepool.yaml` and validate failure with no `spec` specified

chore: Reject NodePools and NodeClaims if they don't have spec

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/helpers.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/operator/logging/logging.go

Fixes #N/A 
This change drops `scheduling.SimulationMode` from the code in favor of using a NopLogger for ignoring log messages and recording the scheduling results outside the context of the `Solve` method. Ideally, solve is just a common library that any component can use without having to reason about options.

chore: Drop simulation mode in favor of NopLogger and Recording scheduling results

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

This PR adds minValues to the NodePool requirements for benchmark testing. This is added conditionally through a flag. So, to add minValues to the scheduling benchmark tests, you will have to run the below command:
```
go test -tags=test_performance -run=SchedulingProfile -minValues=true
```
By default, this is false since this is an optional field provided by the customer and is currently an ALPHA field.
`make presumbit`
Ran default command:
```
go test -tags=test_performance -run=SchedulingProfile
scheduled 10110 against 1690 nodes in total in 9.76606419s with minValues included false 1035.2174431079588 pods/sec
400 instances 10 pods    2 nodes    3.057932ms per scheduling    305.793µs per pod
400 instances 100 pods   17 nodes …
```

test: Add minValues to the NodePool requirements for benchmark testing.

---

Makefile
hack/toolchain.sh
kwok/charts/Chart.yaml
kwok/charts/README.md
kwok/charts/README.md.gotmpl
kwok/charts/values.yaml

Fixes #N/A 
This updates the documented stability level for `SpotToSpotConsolidation` feature to be marked as ALPHA since it is disabled by default
This also adds `helm-docs` generation for the kwok cloudprovider chart that is shipped in this repo.

docs: Update documented stability level for spot-to-spot consolidation

---

pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_budgets_test.go

Fixes #943 
Karpenter releases are built with UTC, but this adds a "TZ=UTC" prefix to valid schedules for budgets to ensure that the underlying cron library always parses the schedule in UTC time.
make apply with kwok and test different schedules.

fix: add hardcoded utc prefix to crontab

---

pkg/controllers/leasegarbagecollection/controller.go
pkg/controllers/leasegarbagecollection/suite_test.go
pkg/controllers/node/termination/metrics.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/metrics.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/metrics.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/operator/controller/singleton.go

Fixes #N/A 
This changes adds the `karpenter_nodes_eviction_queue_depth` and `karpenter_provisioner_scheduling_queue_depth` to give metrics on the number of items that are currently in these queues. This will allow us to get better insight into how quickly we are processing through items and also to know if we are making progress.

chore: Add queue depth metrics for provisioning and termination

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
Drops the need for having two separate arguments in the scheduler, one for NodePools and the other for NodeClaimTemplates

chore: Reason only in terms of NodePools in the scheduler

---

pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go

Fixes: https://github.com/aws/karpenter-provider-aws/issues/5776
`MaxInstanceTypes` was changed from 60 to 100 in version `0.35.0` in order to send more instance types to launch API but that resulted in the request size to be too large for the cases where the requests are highly flexible with multiple zones in large regions leading to validation error from the launch API. This caused unscheduled pods in the cluster. So, we have reverted this particular value back to 60.

cherrypick: fix: Changing the MaxInstanceTypes back to original value of 60 in order to reduce the request size to be sent to launch APIs.order t

---

designs/drift-hash-versioning.md

Fixes #N/A 
The purpose of this RFC is to Propose option around ways to preform CRD changes to Karpenter and have all nodes in a cluster considered drifted. Related issue: https://github.com/kubernetes-sigs/karpenter/issues/957

RFC: Propose Drift Hash Versioning

---

hack/install-kwok.sh

Fixes #N/A
Ensure successful execution of `install-kwok` target in Makefile by adding shebang line to `install-kwok.sh` script.
Otherwise, you get the following error when running the target:
```command
$ make install-kwok 
UNINSTALL_KWOK=false ./hack/install-kwok.sh
./hack/install-kwok.sh: 9: set: Illegal option -o pipefail
make: *** [Makefile:17: install-kwok] Error 2
```

fix: add shebang line in install-kwok.sh to execute commands with bash

---

pkg/scheduling/volumeusage.go

Fixes #1069
Today, if we fail to resolve a CSI driver from a bound PV, we attempt to resolve it from the storage class on the PVC. This can lead to spurious error logs when the volume is not managed by a CSI driver or supported in-tree equivalent (currently only EBS). What we should do is bail early if the PVC is bound and no volume could be discovered. 
Some notes on logging:
- The bound PVC + no driver case isn't logged to avoid repetitive logging for a non-issue, I'd consider logging it if we had a `trace` log level but it feels too verbose even for debug.
- Logs that were previously errors have been reduced to debug messages. Neither of the cases are fatal errors that disrupt Karpenter's ability to schedule but they should still be surfaced because they could indicate …

fix: fix spurious logging for non-CSI volumes

---

pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodepool.go
pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodepool/hash/controller.go
pkg/controllers/nodepool/hash/suite_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go

Fixes #N/A 
Add versioned NodePool Hash to prevent Drift from occurring under these scenario:
1. A `NodePool` adds default values to existing fields that are included in the hash calculations
2. A `NodePool` field is added to the hash calculation with an already-set value
3. A `NodePool` field is removed from the hash calculations
RFC: https://github.com/kubernetes-sigs/karpenter/pull/1015
Related Issue: https://github.com/kubernetes-sigs/karpenter/issues/957

feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade 

---

pkg/controllers/disruption/suite_test.go
pkg/controllers/provisioning/scheduling/volumetopology.go
pkg/controllers/provisioning/suite_test.go
pkg/test/storage.go

Fixes #N/A 
This solves one of the problems called out in: #545

feat: Drop the hostname requirement when handling PV topology

---

.github/actions/install-deps/action.yaml

Fixes #N/A 
Adds the go version to the dependency cache key. This is to address an issue with govulncheck, where the same version of govulncheck built with 1.21 crashes when run against a 1.22 project: https://github.com/golang/go/issues/65590
- Run against github actions

ci: add go version to dep cache key

---

pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/terminator/terminator.go
pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/state/statenode.go

Fixes #N/A 
Core APIs support [strategic merge patching](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/). This provides a more advanced way to patch together lists from standard merge patching, where lists can be merged if they have a `strategic-merge-patch-key` to denote them. For instance, this is true for the status conditions API.
[CRDs do not support strategic merge patching out of the box](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility:~:text=Yes-,strategic%2Dmerge%2Dpatch,-The%20new%20endpoints) so we cannot get rid of standard merge patching for them. This will resolve some errors in AWS E2E testing, where we are seeing errors like `patching node, …

chore: Use strategic merge patching for Core APIs

---

pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodepool/hash/controller.go

Fixes #N/A 
- Add a test for when the `karpenter.sh/nodepool-hash-version` is not present on the NodeClaims
- Clean-up on wording 

chore: Adding a drift test and cleanup on wording

---

hack/install-kwok.sh

kustomize `patchesStrategicMerge` is deprecated, use `patches` instead.
By running the hack/install-kwok.sh script locally.

kustomize patchesStrategicMerge is deprecated, use patches instead.

---

pkg/controllers/disruption/suite_test.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/nodeclaim/garbagecollection/controller.go
pkg/controllers/nodeclaim/garbagecollection/suite_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/test/expectations/expectations.go

Fixes #1100
This change gates deletion of the NodeClaim and the force deletion of the Node based on the readiness of the Node. Today, we blindly delete the NodeClaim and Node if we get NotExists from the CloudProvider; however, we should also gate this based on the Node readiness and kubelet heartbeat to deal with potential inconsistency issues on the List() CloudProvider call.
This also lets the Registration liveness controller cleanup any NodeClaims that don't register in time, but allows the full 15m timeout to occur before terminating a NodeClaim that doesn't exist being returned from the CloudProvider List() call.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix: Check node readiness before force terminating

---

pkg/controllers/node/termination/controller.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/suite_test.go

Fixes #N/A 
Removes the call to `cloudProvider.Delete()` from the node termination controller. This hands-off responsibility of deleting the instance solely to the NodeClaim termination controller. This delete call was only in there for legacy reasons during the machine migration that could have occurred prior to v0.32.0

chore: Drop CloudProvider delete call from Node termination

---

pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodepool.go
pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodepool/hash/controller.go
pkg/controllers/nodepool/hash/suite_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go

Fixes #N/A 
- Add a cherry pick of https://github.com/kubernetes-sigs/karpenter/pull/1016

cherrypick(v0.34.x): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade

---

pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodepool.go
pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodepool/hash/controller.go
pkg/controllers/nodepool/hash/suite_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go

Fixes #N/A 
- Add a cherry pick of https://github.com/kubernetes-sigs/karpenter/pull/1016

cherrypick(v0.33.x): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade

---

pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodepool.go
pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodepool/hash/controller.go
pkg/controllers/nodepool/hash/suite_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go

Fixes #N/A 
- Add a cherry pick of https://github.com/kubernetes-sigs/karpenter/pull/1016

cherrypick(v0.35.x): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade

---

pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_webhook_test.go

Fixes https://github.com/aws/karpenter-provider-aws/issues/5913
- We should be able to create a budget with a duration format of  `1h10m`
- N/A

fix: Adjust duration validation to include format for `1h10m`

---

pkg/apis/v1beta1/nodepool_validation.go

Fixes #N/A 
- Removing web hook validation as openAPI validation will be evaluated by the APIServer for all version of supposed k8s 
- https://github.com/kubernetes-sigs/karpenter/blob/066cc4cb70fc09031cee4c54f9acca5c557db0d7/pkg/apis/v1beta1/nodepool.go#L127

chore: Remove validation as covered by OpenAPI validation

---

pkg/test/deployment.go
pkg/test/pods.go

Fixes #N/A 
When running E2E tests on private cluster, we can't pull the pod image from the internet. But currently the default pod image is a constant. Changing it to variable so that the value can be configured in case the tests are running on private cluster.

chore: Changes to run e2e for private cluster

---

pkg/apis/v1beta1/labels.go
pkg/apis/v1beta1/nodepool.go
pkg/controllers/nodeclaim/disruption/drift.go
pkg/controllers/nodeclaim/disruption/nodeclaim_drift_test.go
pkg/controllers/nodepool/hash/controller.go
pkg/controllers/nodepool/hash/nodepool_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
pkg/utils/nodepool/nodepool.go

Fixes #N/A 
- Add a cherry pick of feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade  #1016

cherrypick(v0.32): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade

---

pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_webhook_test.go

Fixes #N/A 
- Add a cherry pick of https://github.com/kubernetes-sigs/karpenter/pull/1125

cherrypick(v0.34): fix: Adjust duration validation to include format for `1h10m` 

---

pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodepool.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_webhook_test.go

Fixes #N/A 
- Add a cherry pick of https://github.com/kubernetes-sigs/karpenter/pull/1125

cherrypick(v0.35): fix: Adjust duration validation to include format for `1h10m`

---

pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/termination/controller.go

Fixes #N/A 
Add some additional comments on locations that we call `kubeClient.Update()`

chore: Add comments on calls to kubeClient Update()

---

kwok/cloudprovider/cloudprovider.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/types.go

Fixes #N/A 
- For Karpenter to be able to query the APIServer for NodeClass, we will need to know the Kind, Version and Group of the nodeclass supported by the cloudprovider. 
- Adding `GetSupportedNodeClasses` to get all the NodeClasses used by a cloudprovider
- N/A

feat: Get the GVK of the supported NodeClasses as part of the CloudProvider interface

---

hack/validation/kubelet.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodeclaim_validation.go
pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
pkg/apis/v1beta1/nodeclaim_validation_webhook_test.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_webhook_test.go
pkg/apis/v1beta1/zz_generated.deepcopy.go
pkg/controllers/nodeclaim/disruption/drift_test.go

Fixes #1080 
- To allow drift to happen on the on KubeReserved and SystemReserved, we need to update the type to be a map[string]string so that we can hash on the values 

fix: Change type to hash on KubeReserved and SystemReserved 

---

pkg/apis/v1beta1/nodepool.go

Fixes #N/A 
- Due to PR https://github.com/kubernetes-sigs/karpenter/pull/1141, we need to bump the hash version 

chore: Bump `NodePoolHashVersion`

---

contributing-guidelines.md

Fixes #N/A 
This adds in contributor ladder guidelines as an RFC. This is a proposal from the maintainers on how users can become reviewers and approvers in the project. Let us know what you think.

docs: RFC for contributor ladder guidelines

---

go.mod

Fixes #N/A 
- Accidentally published incomplete patch release for v0.34.4 and v0.35.3
- N/A

chore: Retract the Karpenter version due to a bad release

---

.github/workflows/release.yaml

Fixes #N/A 
- We are seeing failure for v0.32.x on creating a release, so we will be pinning the version to v1.2.1
- https://github.com/kubernetes-sigs/karpenter/actions/runs/8512485503
- https://github.com/kubernetes-sigs/karpenter/blob/3d493b30f2464833a6482b99c80117dc20a23a44/.github/workflows/release.yaml#L27
- N/A

chore: Pin the release action for v0.32.x 

---

go.mod

Fixes #N/A 
- Retract Karpenter v0.35.3 and v0.34.4
- N/A

chore: Retract v0.35.3 and v0.34.4 

---

pkg/controllers/nodeclaim/disruption/controller.go
pkg/operator/operator.go
pkg/utils/nodeclaim/nodeclaim.go

Fixes #337 
- Detect drift on NodeClaims from when NodeClass get updated.

feat: Detect Drift on NodeClaims on changes to NodeClass

---

pkg/cloudprovider/types.go
pkg/controllers/nodeclaim/termination/controller.go

Fixes #947
The termination controller calls `cloudProvider.Delete(nodeClaim)` which tries to terminate the underlying instance. It will remove the finalizer once the cloudProvider.Delete() call succeeds. However, the current implementation in AWS does not wait until the instance state is actually `terminated` and proceeds to remove the finalizer once the `ec2.TerminateInstance()` call has succeeded. 
The change in this PR adds a retryable error to cloudprovider which will allow Karpenter to parse instance state that has been successfully called terminate, but wasn't fully terminated. This effectively re-enqueues the node into the reconciliation loop of the termination controller. …

chore: Add retryable error to cloud provider

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/nodeclaim/termination/controller.go
pkg/controllers/nodeclaim/termination/suite_test.go

Fixes #N/A 
1. Re-enqueue nodeClaim termination after 10s when we see an error. 
2. Added test for retryable error.

chore: Re-enqueue nodeclaim termination after 10s in case of retryable error

---

pkg/controllers/controllers.go
pkg/controllers/nodeclaim/consistency/controller.go
pkg/controllers/nodeclaim/consistency/nodeshape.go
pkg/controllers/nodeclaim/consistency/suite_test.go

Fixes #N/A 
- Remove cloudprovider interface from NodeClaim Consistency controller , since it's not used in the provider

chore: Remove Cloudprovider from Consistency controller

---

pkg/controllers/node/termination/controller.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/suite_test.go

Reverting https://github.com/kubernetes-sigs/karpenter/pull/1103
This change meant that the node could be deleted before the instance termination was completed. This doesn't have significant impact -- because we weren't waiting for EC2 to fully terminate the node before -- however, we are planning to wait for instance termination before the node gets deregistered and we will need this delete call to be in the finalization flow

Revert "chore: Drop CloudProvider delete call from Node termination"

---

pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/nodeclaim/termination/suite_test.go

Fixes #N/A 
Add retryable error handling during the node termination handling

chore: Add retryable error handling to node termination

---

pkg/controllers/nodeclaim/lifecycle/liveness.go

Fixes #N/A 
We have a system that allow us to raise alerts based on logs. Liveness probe is a useful signal for greater node registration problems on the cluster.
We log at the Info level verbosity. Registration TTL should be more than just debug. I can figure out the nodeclaim is being deleted at 15 minutes but not why. Having this explicit log would be useful for alerting on logs. 
- it wasn't

chore: bump registration ttl log

---

pkg/controllers/provisioning/provisioner.go

Fixes #N/A 
This change fixes a regression where we were logging `found provisionable pod(s)` more frequently than we should have been

fix: Only log found provisionable pods with new nodeclaims

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature.yaml

Fixes #910
The bot should now auto-add this label with: https://github.com/kubernetes/test-infra/blob/63c23493ceefcfdedc7571fa42504b0ba94d7a5b/config/prow/plugins.yaml#L831

ci: Remove needs-triage auto-add

---

pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/drift.go
pkg/controllers/disruption/expiration.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/validation.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
This change updates the eventing to be more specific about why not all pods were able to schedule, similar to how Consolidation gives this information back through eventing right now.
```
Type    Reason             Age    From       Message
----    ------             ----   ----       -------
Normal  DisruptionBlocked  2s     karpenter  Cannot disrupt NodeClaim: Scheduling simulation failed to schedule all pods
```
```
Type    Reason             Age    From       Message
----    ------             ----   ----       -------
Normal  Unconsolidatable            62s   karpenter  not all pods would schedule, default/inflate-6f56784d74-cqzdj => would schedule against uninitialized nodeclaim/default-lkv5s
```
By …

chore: Clarify failed scheduling error on all disruption methods

---

go.mod

Fixes #N/A 
Unpins the go version from 1.22.2 so that we can always be on the latest go version when vulnerabilities + fixes are introduced

chore: unpin go version in go mod

---

pkg/cloudprovider/types.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/nodeclaim/termination/controller.go
pkg/controllers/nodeclaim/termination/suite_test.go

Fixes #N/A 
This PR reverts the changes that were made in #1164, #1170 and #1172. We don't want to make use of retryable error to drive nodeClaim termination. When this approach was tested for AWS provider we found that some instances could take too long to delete. We do not want to use retryable error to trigger multiple `cloudProvider.Delete()` calls.
NA

revert changes made in #1164, #1170 and #1172

---

.golangci.yaml

Fixes #N/A 
Update golangci-lint config to the latest, removing deprecating settings `run.skip-dirs` and `govet.check-shadowing`. This also enables more strict checking on `govet`

ci: Update golangci-lint config to latest

---

Makefile
hack/validation/status.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml

Fixes #N/A 
This change ensures that our use of `metav1.Condition` doesn't cause validation failures when making updates to the NodeClaim. We can drop this injected removal of these required fields when we get to v1, where we can use conversion to automatically set these values.

chore: Don't require message or reason to be set for NodeClaim status conditions

---

go.mod
go.sum

Fixes #N/A 
This bumps Operator PKG to latest. Also changing the SetFalse() handling in testing to set message to an empty string

chore: Bump operatorpkg to latest

---

pkg/cloudprovider/types.go
pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/multinodeconsolidation.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
This refactors the minValues code to be reusable by other places were instance types are used and truncated (like in https://github.com/aws/karpenter-provider-aws/pull/6182). It also clarifies some of the usages and checking of minValues.

chore: Factor minValues requirements checking into the InstanceTypes methods

---

pkg/controllers/leasegarbagecollection/controller.go
pkg/controllers/metrics/nodepool/controller.go
pkg/controllers/metrics/pod/controller.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/nodeclaim/consistency/controller.go
pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/garbagecollection/controller.go
pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/nodeclaim/termination/controller.go
pkg/controllers/nodepool/counter/controller.go
pkg/controllers/nodepool/hash/controller.go
pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/preferences.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/volumetopology.go
pkg/controllers/state/informer/daemonset.go
pkg/controllers/state/informer/node.go
pkg/controllers/state/informer/nodeclaim.go
pkg/controllers/state/informer/nodepool.go
pkg/controllers/state/informer/pod.go
pkg/operator/controller/controller.go
pkg/scheduling/volumeusage.go

Fixes #N/A 
Drop logger name injection at the top of controllers and add consistent formatting for K8s objects
```
{"level":"INFO","time":"2024-05-22T18:36:18.697Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"d39fdb5","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"arm64-kt2kk"},"namespace":"","name":"arm64-kt2kk","reconcileID":"20941b16-c9ac-4d9d-92a8-5f06022a5fc2","nodeclaim":"arm64-kt2kk","provider-id":"aws:///us-west-2b/i-075ceb3922cf96cec","instance-type":"c6g.medium","zone":"us-west-2b","capacity-type":"on-demand","allocatable":{"cpu":"940m","ephemeral-storage":"17Gi","memory":"1392Mi","pods":"8","vpc.amazonaws.com/pod-eni":"4"}}
```
``` …
```

BREAKING: Drop logger name injection and add consistent formatting for K8s objects

---

kwok/apis/v1alpha1/labels.go
kwok/cloudprovider/cloudprovider.go
kwok/cloudprovider/helpers.go
kwok/main.go

Fixes #N/A 
Moves the kwok based labels from inside the cloudprovider implementation code to the api directory where the kwok specific details now live
make verify

chore: move kwok labels to api based directory

---

hack/validation/status.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml

Fixes #N/A 
Allows empty strings for status condition reasons in the nodeclaims. This is a gap in the #1254 where we still fail validation when the reason is set to an empty string.
Manual validation: installed v0.36.2, spun up nodes, upgraded to HEAD, expired existing nodes

fix: allow empty string for condition reason

---

hack/validation/status.sh
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml

Fixes #N/A 
This updates the regex validation for the status condition reason on `NodeClaims`. A previous PR (https://github.com/kubernetes-sigs/karpenter/pull/1285) updated this regex to allow empty strings and unblock migration from previous versions to v0.37. It also inadvertently changed the regex such that if a string is provided it must be at least two characters. This doesn't have any immediate impact since none of the status conditions are a single character, but this PR corrects the regex.
Manual validation

fix: allow single character status condition reason

---

go.mod
pkg/utils/pretty/pretty.go

fix: Sort deterministically and fix the issue where we printed the wrong counts.
Fixes #N/A 
Fixes bug in printing truncated maps for logs.
Unit tests

fix bug in printing truncated maps

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
The `context.Context` value was not being used by the scheduler. This change removes it.

chore: Drop unused scheduler context argument

---

kwok/cloudprovider/helpers.go
kwok/cloudprovider/instance_types.json
kwok/tools/gen_instance_types.go

Fixes #N/A 
We changed offerings to use requirements rather than hard-coded strings for capacity type and zone. This made kwok offerings incompatible. 
make apply and scale up and scale down

chore: fix kwok offerings to use new requirements

---

.github/workflows/presubmit.yaml

Fixes #N/A 
Adds 1.30 into the presubmit versions to test and changes the goveralls version to 1.30.x
make presubmit 

chore: add 1.30 into presubmit versions

---

pkg/apis/v1beta1/nodeclaim_status.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/nodeclaim/termination/controller.go
pkg/controllers/nodeclaim/termination/metrics.go
pkg/controllers/nodeclaim/termination/suite_test.go
pkg/metrics/metrics.go
pkg/test/expectations/expectations.go
pkg/utils/node/node.go
pkg/utils/node/suite_test.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/suite_test.go
pkg/utils/termination/suite_test.go
pkg/utils/termination/termination.go

Fixes #N/A 
Finalizers on nodeClaim and node should not be removed until the underlying instance is deleted to avoid leaking any resources. The current approach relies on retryable error being emitted by cloudProvider.Delete() and continues reconciliation until this error is received. However, that is not an ideal approach. When this approach was tested for AWS provider we found that some instances could take too long to delete.Hence in this PR, instead a status condition `terminating` is added on nodeclaim and if the status exists then we call cloudProvider.Get() to check if the instance is terminated. If it is terminated, then we can remove finalizer from the nodeClaim.
Tested on my local cluster and ran unit tests
By submitting this pull …

chore: Wait for instance termination before deleting nodeclaim

---

kwok/cloudprovider/helpers.go

Fixes #N/A 
The kwok instance types use a differently typed requirements. The instance types have the right requirements, but the offerings don't have any requirements. This fixes that bug and adds them in
make apply

fix: kwok offerings to use correct requirements

---

kwok/cloudprovider/cloudprovider.go

Fixes #N/A 
Karpenter now waits for the nodeclaim to be not found with the cloudprovider.Get() call, which this implements the fix for the kwok cloud provider
make apply 

fix: add deletiontimestamp check for kwok termination

---

pkg/controllers/node/termination/suite_test.go

Fixes #N/A 
Updates the node/termination test suite to properly model eventual removal now that it may take multiple reconciliations.
`make test`

test: update node termination test to model eventual removal

---

kwok/README.md
kwok/apis/apis.go
kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/apis/v1alpha1/doc.go
kwok/apis/v1alpha1/labels.go
kwok/apis/v1alpha1/register.go
kwok/charts/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/charts/crds/kwok.karpenter.sh_kwoknodeclasses.yaml
kwok/charts/templates/clusterrole-kwok.yaml
kwok/cloudprovider/helpers.go
kwok/main.go

Fixes #N/A 
This fixes the api group of the kwok node class, and by association its labels. It was incorrectly ordered, and should now match the validation. 
make presubmit

chore: fix kwok api version group

---

test/pkg/debug/collector.go
test/pkg/environment/common/environment.go
test/suites/perf/scheduling_test.go
test/suites/perf/suite_test.go

Fixes #N/A 
Adds the ability to set OUTPUT_DIR with testing framework for timestamp exports
OUTPUT_DIR=$(mktemp -d) make e2etests

test: add output_dir env variable for timestamp exports

---

pkg/operator/operator.go

Fixes #N/A 
Moved logger forward, fixed that no prompts are output when KubeConfig is incorrect.
Before: no KubeConfig, no output.
```bash
/xxxx/___kwok
Process finished with exit code 1
```
After: no KubeConfig, has output.
```bash
/xxxx/___kwok
{"level":"ERROR","time":"2024-06-23T12:04:30.034+0000","logger":"controller.controller-runtime.client.config","message":"unable to load in-cluster config","commit":"9ddd790","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"}
{"level":"ERROR","time":"2024-06-23T12:04:30.035+0000","logger":"controller.controller-runtime.client.config","message":"unable to get kubeconfig","commit":"9ddd790","error":"invalid configuration: no …
```

fix: logger print KubeConfig error

---

pkg/controllers/controllers.go
pkg/controllers/provisioning/controller.go

Fixes #N/A 
Drop unused event recorder from provisioning controllers

chore: Drop event recorder from provisioning controllers

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodeclaim.go
pkg/apis/v1/nodepool.go
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodepool.go

Fixes #N/A 
- Update storage version of the Karpenter CRDs, since v1 APIs are not currently being used in code
- N/A

chore: Update storage version to v1beta1 APIs

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/v1/nodeclaim.go

Fixes #N/A 
- Make NodeClaim Immutable on v1 API
- V1 RFC: https://github.com/kubernetes-sigs/karpenter/pull/1222

chore: Make NodeClaim Spec Immutable on v1 API

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/v1/nodeclaim.go

Fixes #N/A 
- Old Printer Column 
```
NAME            TYPE         ZONE         NODE                                            READY   AGE    CAPACITY   NODEPOOL   NODECLASS
default-7lh6k   c6gn.large   us-west-2b   ip-192-168-183-234.us-west-2.compute.internal   True    2d7h   spot       default    default
```
- New Printer Column 
```
NAME               TYPE       CAPACITY   ZONE         NODE                                            READY   AGE   ID                                      NODEPOOL     NODECLASS
default-v1-2z2h5   t3.small   spot       us-west-2b   ip-192-168-42-3.us-west-2.compute.internal      True    29m   aws:///us-west-2b/i-0805c4361a70ee3fb   default-v1   default
```
- v1 RFC: https://github.com/kubernetes-sigs/karpenter/pull/1222
**How was this …

feat: Adding printer columns on v1 NodeClaims

---

go.mod
go.sum
pkg/operator/operator.go

Fixes #N/A 
Add client-go metrics to Karpenter for storing the number of API calls generated from each container to the apiserver
```
client_go_request_duration_seconds_count{group="",kind="events",subresource="",verb="PATCH",version="v1"} 10
client_go_request_duration_seconds_count{group="",kind="nodes",subresource="",verb="DELETE",version="v1"} 12
client_go_request_duration_seconds_count{group="",kind="nodes",subresource="",verb="LIST",version="v1"} 1
client_go_request_duration_seconds_count{group="",kind="nodes",subresource="",verb="PATCH",version="v1"} 12
client_go_request_duration_seconds_count{group="",kind="pods",subresource="",verb="LIST",version="v1"} 1
client_go_request_duration_seconds_count{group="",kind="pods",subresource="eviction",verb="CREATE",version="v1"} …
```

feat: Add karpenter client-go metrics

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodeclaim.go

Fixes #909 
- Change apiVersion -> Group 
- Require Kind and Group for NodeClassRef
- V1 RFC: https://github.com/kubernetes-sigs/karpenter/pull/1222

chore: Update `nodeClassRef` to be Group instead of APIVersion

---

hack/install-kwok.sh
kwok/cloudprovider/cloudprovider.go
kwok/cloudprovider/const.go
kwok/cloudprovider/instance_types.json

Fixes #N/A 
Upgrades kwok to the latest version, and scales back the number of partitions to 1, so that multiple kwok controllers aren't competing for a kind cluster's limited control plane resources.
Note: if you were using kwok before this PR, you'll need to `make uninstall-kwok` on a commit before this to fully clean up all kwok controllers/resources.
make install-kwok && make apply 

chore: update kwok to v0.5.2 and scale back replicas

---

pkg/controllers/provisioning/provisioner.go

Fixes #N/A 
Warnings for consolidation are useful for users to be aware that their consolidations can be blocked by preferences, but the number of warnings can be extremely verbose when there are a large number of replica pods that have the same configuration. This groups the logging messages together so there is only a single log line for a given set of pending pods during the provisioning loop.
```
{"level":"INFO","time":"2024-06-30T21:41:03.143Z","logger":"controller","message":"pod default/underwater-57bc5b9958-fk7d6 has a preferred Anti-Affinity which can prevent consolidation","commit":"490ef94","controller":"provisioner"}
{"level":"INFO","time":"2024-06-30T21:41:03.143Z","logger":"controller","message":"pod …
```

chore: Group consolidation warning log lines together

---

pkg/apis/v1/suite_test.go
pkg/controllers/metrics/pod/controller.go
pkg/controllers/nodeclaim/termination/controller.go
pkg/utils/disruption/disruption.go
pkg/utils/node/suite_test.go
pkg/utils/termination/suite_test.go

Fixes #N/A 
Remove spurious log line for `terminated nodeclaim` that was causing the following log line with the fallback logger
```
{"level":"info","ts":1719908125.4508243,"logger":"fallback","caller":"termination/controller.go:139","msg":"deleted nodeclaim"}
```
This also replaces the usage of the `logging.FromContext(ctx).Error()` call that was being made in the disruption controller

chore: Remove usage of `knative.dev` logger

---

test/suites/perf/scheduling_test.go

Fixes #N/A 
Fixes a test assertion due to rounding errors
make e2etests with a kwok cluster

test: fix e2e tests assertion

---

.github/workflows/kind-e2e.yaml
.github/workflows/presubmit.yaml
test/suites/perf/scheduling_test.go

Fixes #N/A 
At v1, we'll only need to support 1.25 as we'll rely on CEL for CRD validation which is only available 1.25+. 
make presubmit

test: remove k8s 1.23 and 1.24 tests

---

hack/install-kwok.sh
test/pkg/environment/common/setup.go

Fixes #N/A 
Fix test flakes that were preventing kind clusters from cleaning up. Resources were stuck in a foreground deleting, where these resources are all fake, so we don't need to wait for all resources to be cleaned up. 
make presubmit

test: fix kind cluster test cleanup flakes

---

pkg/controllers/nodepool/readiness/controller.go
pkg/controllers/nodepool/readiness/suite_test.go
pkg/controllers/provisioning/provisioner.go

Fixes #N/A 
Nodepool readiness condition should rely on nodeClass. If nodeClass has a deletion timestamp set then nodepool will become non-ready.
Also removed duplicate check for nodePool readiness.
Tested on local cluster. Added functional tests.

chore: update nodepool readiness to rely on nodeClass deletion timestamp

---

kwok/main.go
pkg/controllers/controllers.go
pkg/operator/operator.go

Fixes #N/A 
Add `operator_status_condition_count` and `operator_status_condition_transition_seconds` from operatorpkg for NodePool and NodeClaim

chore: Add operator status condition metrics

---

pkg/controllers/nodeclaim/lifecycle/registration.go

Fixes #N/A 
Add check for conflict error during registration flow to reduce errors fired by the NodeClaim lifecycle controller
```console
{"level":"INFO","time":"2024-07-10T07:03:08.041Z","logger":"controller","message":"registered nodeclaim","commit":"ff0dc7d","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-64wj8"},"namespace":"","name":"default-64wj8","reconcileID":"c4f8281e-21b2-41bb-b120-a63f06483da8","provider-id":"aws:///us-west-2c/i-0b692de472e2796ea","Node":{"name":"ip-192-168-126-131.us-west-2.compute.internal"}}
{"level":"ERROR","time":"2024-07-10T07:03:08.616Z","logger":"controller","message":"Reconciler error","commit":"ff0dc7d","controller":"nodeclaim.lifecycle","controllerGroup":"kar …
```

chore: Add check for conflict during registration flow

---

pkg/controllers/disruption/drift_test.go
pkg/controllers/state/statenode.go

Fixes #1323
Currently we don't validate if `do-not-disrupt` annotation on a node is set to `true` and only check if the annotation exists. This PR adds a change to add the validation.
Tested on local cluster. Added a functional test for the change.

chore: Validate do not disrupt annotation on node is true

---

pkg/operator/operator.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodepool/nodepool.go

Fixes #N/A 
Update previous refs to `nodeClassRef.apiVersion` to properly refer to `nodeClassRef.group`. This was causing NodePool readiness failures since we were trying to match against a NodeClass with a group that matches the apiVersion. 
Tested against the AWS provider

fix: update nodeClassRef.apiVersion refs to group

---

pkg/test/pods.go
test/suites/perf/scheduling_test.go
test/suites/perf/suite_test.go

Fixes #N/A 
Bumps up the replica count and uses a different set of requirments for complex scale tests for kwok e2es
testing locally

test: upgrade tests and change to preferred pod affinity

---

.github/workflows/kind-e2e.yaml
test/suites/perf/scheduling_test.go

Fixes #N/A 
Adds the kwok e2es to the presubmit
https://github.com/kubernetes-sigs/karpenter/actions/runs/9899349157

test: add kind kwok e2es to presubmit

---

pkg/apis/apis.go
pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go
pkg/apis/v1beta1/labels.go

Fixes #N/A 
- Added checking for conversion webhook to only include kubelet annotation, when sublet struct is present

chore: Only Include the kubelet annotation when present in v1beta1

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodeclaim.go
pkg/apis/v1/nodeclaim_validation_cel_test.go
pkg/apis/v1/nodepool_validation_cel_test.go
pkg/apis/v1beta1/nodeclaim.go
pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
pkg/apis/v1beta1/nodepool_validation_cel_test.go

Implements CEL tests for the new `terminationGracePeriod` field on NodeClaim.

test: implement nodeclaim.spec.terminationGracePeriod CEL tests

---

pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/drift_test.go
pkg/controllers/disruption/emptiness_test.go
pkg/controllers/disruption/suite_test.go

Fixes #1434
I ran a script in the linked issue to identify the slowest tests in the Karpenter codebase. This brought me to one of the `SimulateScheduling` tests, which called `ExpectTriggerVerifyAction` multiple times. I discovered that this test was not exercising code paths that waited in the clock (e.g `time.Sleep`), so this test helper was looping and sleeping for 8 seconds before bailing. Since the test didn't rely on any sleep, I removed the helper and saw an 8 * 4 second gain for each time this helper was called in the `SimulateScheduling` test. 
I then rewrote `ExpectTriggerVerifyAction` using expectations to assert that the sleep was actually used, and I broke dozens of tests. It seems as if we've been (understandably) writing our tests in this package with a lot …

test: Improved Disruption Test Suite duration from 527 seconds to 38 seconds

---

.github/workflows/kind-e2e.yaml

This version update makes consuming the results from e2e tests in github actions easier. 
Running the affected github action.

ci: Updated Karpenter Evaluate version for e2e tests action

---

pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/drift_test.go
pkg/controllers/disruption/emptiness_test.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/metrics.go
pkg/controllers/disruption/orchestration/metrics.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/metrics/nodepool/controller.go
pkg/controllers/metrics/pod/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/nodeclaim/expiration/suite_test.go
pkg/metrics/metrics.go

Fixes #N/A 
Reconfigured Karpenter metrics that are duplicated (workqueue metrics, renames of existing metrics).
1. Changed the name of `karpenter_disruption_budgets_allowed_disruptions` to the NodePool subsystem so that it is `karpenter_nodepools_allowed_disruptions`
2. Changed `karpenter_disruption_actions_performed_total` to `karpenter_disruption_decisions_total`
3. Changed `karpenter_disruption_replacement_nodeclaim_failures_total` to `karpenter_disruption_queue_failures_total`
4. Convert `karpenter_nodeclaims_terminated` to `karpenter_nodeclaims_terminated_total` and convert `karpenter_nodes_terminated` to `karpenter_nodes_terminated_total`
5. Remove `karpenter_disruption_nodes_disrupted_total` since this is already captured by `karpenter_nodeclaims_terminated_total` …

chore: Reconfigure metrics that are duplicated

---

pkg/operator/operator.go

Fixes #N/A 
Temporarily removes the readiness check on cache sync ahead of v1. This check was introduced by #401, but has an unexpected consequence for the upgrade path to v1. Consider the following scenario:
- A cluster is upgraded from v0.37.0 to a version with the v1 APIs / conversion webhooks
- The newly deployed Karpenter pods must list all resources before going ready
- This list call is going to attempt to invoke the conversion webhook
- Karpenter's endpoint is not ready since the pod is not ready, and the webhook can't be called through the service
In this scenario, Karpenter will be stuck in an unready state and be unable to progress.
manual validation
By submitting this pull request, I confirm that my contribution is made under the …

chore: remove readiness check on cache sync

---

.github/workflows/kind-e2e.yaml

Fixes #N/A 
Removes kind e2es from presubmit so that we don't have flakes blocking PRs. Keeps it on push so that we can still have it run whenever a PR is merged.
Testing here

test: remove kind due to flakes

---

pkg/controllers/metrics/pod/controller.go

Fixes #N/A 
Update pod startup metric.
Change `karpenter_pods_startup_time_seconds` to `karpenter_pods_startup_duration_seconds`

chore: reconfigure pod startup metric

---

pkg/apis/v1/labels.go
pkg/apis/v1beta1/labels.go

Fixes #N/A 
Dropping `karpenter.sh/managed-by` as it is an artifact of a migration path and not something needed in the future. Adding `eks:eks-cluster-name` to support pod identity sessions.
make test

feat: Remove karpenter.sh/managed-by var

---

pkg/apis/v1/taints.go
pkg/controllers/disruption/drift_test.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/provisioning/controller.go
pkg/controllers/state/statenode.go
pkg/utils/pod/scheduling.go
test/pkg/environment/common/environment.go
test/pkg/environment/common/expectations.go

Fixes #N/A 
Replaces the disruption taint as per https://github.com/kubernetes-sigs/karpenter/pull/1222.
`karpenter.sh/disruption=disrupting:NoSchedule` -> `karpenter.sh/disrupted:NoSchedule`
When the taint is removed by the orchestration queue or disruption controller, we'll also remove the v1beta1 equivalent version of the taint. This ensures we don't leave nodes tainted if Karpenter is upgraded after they've been disrupted but before they've been terminated.
`make presubmit` and validation against the AWS provider (TODO)

chore: rename disruption taint

---

kwok/README.md

Fixes #N/A 
When run the kwoks examples, I found that I had to configure the webhook to convert versions. So change example NodePool in kwok readme from v1beta to v1 to run the example directly.
Only docs.

docs: Change example NodePool in kwok readme from v1beta to v1.

---

go.mod
go.sum

Fixes #N/A 
Bump `github.com/awslabs/operatorpkg` to latest to contain changes for `operator_status_condition_transitions_total` and `operator_status_condition_current_status_seconds` metrics

chore: Bump operatorpkg with latest metrics

---

go.mod
go.sum

Fixes #N/A 
Bump `github.com/awslabs/operatorpkg` to latest to fix race condition on concurrent reconciles (see https://github.com/awslabs/operatorpkg/pull/63)

fix: Bump `github.com/awslabs/operatorpkg` to fix race condition

---

hack/validation/status.sh
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml

Fixes #N/A 
- Add status validation for both v1 and v1beta1. Since `metav1.Condation` is being aliased, `operatorpkg.Status` will need to update the `status.Condition` for us to remove the injected vaildation  
- Manually Tested

chore: Add status validation to v1

---

kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodepool.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go
pkg/apis/v1/nodepool_validation_cel_test.go
pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/emptiness.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/nodeclaim/disruption/consolidation_test.go

Fixes #N/A 
This changes WhenUnderutilized to WhenEmptyOrUnderutilized so that it's clear that emptiness and underutilized are mutually exclusive methods of disrupting nodes, and that WhenEmptyOrUnderutilized applies to both.
make presubmit

chore: rename whenUnderutilized to WhenEmptyOrUnderutilized

---

go.mod
go.sum
pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/initialization_test.go
pkg/controllers/nodeclaim/lifecycle/launch.go
pkg/controllers/nodeclaim/lifecycle/launch_test.go
pkg/controllers/nodeclaim/lifecycle/registration.go

Fixes #N/A 
This PR updates our handling of NodeClaims to leave them in an Unknown state for Launched, Registered, and Initialized status conditions until they have reached a terminal state. This aligns with the thinking around terminal status conditions that's detailed in: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties.
This now means that Karpenter will hold NodeClaims in an Unknown state (also Ready Unknown state) for a longer period of time before it either transitions them into a False or True state. Once it enters this False or True state, it will not leave its False or True state.  …

chore: Ensure that NodeClaims are held in Unknown until they reach a terminal state

---

.github/workflows/kind-e2e.yaml
.github/workflows/presubmit.yaml

/kind cleanup
Fixes #N/A 
let matrix do not fail fast, In order to easily know whether the error is related to the K8S version.

ci: let matrix do not fail fast.

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodeclaim.go
pkg/apis/v1/nodeclaim_validation_cel_test.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/provisioning/suite_test.go
pkg/utils/node/suite_test.go

Fixes #N/A 
If a user creates a nodePool with nodeClassRef as shown below, nodePool fails to watch the nodeClass and nodePool remains stuck in not ready condition if EC2NodeClass is created before nodePool.
```
nodeClassRef:
group: karpenter.k8s.aws/v1
kind: EC2NodeClass
name: default
```
A check has been added for the field `group` such that it will not allow slash.
Added test for the change. Tested on local cluster.

chore: Add pattern check for group in nodeClassRef

---

pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/nodeclaim/lifecycle/registration_test.go
pkg/scheduling/taints.go

Fixes #N/A 
This change updates Karpenter so that we mark the Unregistered status condition as False when the node exists but doesn't have the `karpenter.sh/unregistered` taint as well as ensures that the Node can't be marked as initialized while it doesn't have that taint

chore: Mark the status condition as false when unregistered taint isn't present and block initialized

---

Makefile
hack/validation/status.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml

Fixes #N/A 
- Add in validation for when controller edit v1 version of the resource

chore: Include status validation for v1 NodeClaim in v0.35.x

---

pkg/apis/v1/nodeclaim_conversion.go

Fixes #N/A 
- Remove the minValue filed when converting from v1 -> v1beta1
- `make presubmit` 

chore: Remove min-Value from being set on conversion v1 -> v1beta1 

---

pkg/controllers/nodepool/readiness/controller.go

Fixes #N/A 
Change failure reason for NodeClassReadiness from `UnresolvedNodeClass` to `NodeClassNotFound`

chore: Change reason to `NodeClassNotFound` to match `NodeNotFound`

---

pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodepool_conversion.go

Fixes #N/A 
When converting nodeClassRef from v1beta1 to v1, group would be empty if apiVersion is of the type `karpenter.k8s.aws` i.e. it does not contain the version. This PR adds the fix for it.
Tested on local cluster

chore: fix nodeClassRef conversion

---

pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodepool_conversion.go

Fixes #N/A 
- Backport nodeClassRef fix

fix: Backport nodeClassRef conversion fix for v0.34.x 

---

pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodepool_conversion.go

Fixes #N/A 
- Backport nodeClassRef fix 

fix: Backport nodeClassRef conversion fix for v0.33.x

---

pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodepool_conversion.go

Fixes #N/A 
- Backport nodeClassRef fix

fix: Backport nodeClassRef conversion fix for v0.35.x

---

pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodepool_conversion.go

Fixes #N/A 
- Backport nodeClassRef fix

fix: Backport nodeClassRef conversion fix for v0.36.x 

---

pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodepool_conversion.go

Fixes #N/A 
- Backport nodeClassRef fix

fix: Backport nodeClassRef conversion fix for v0.37.x

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

Fixes #N/A 
Ensure that our EC2NodeClassReference information is retained during conversion from v1beta1 to v1 and back. This is to ensure that we don't drift when Karpenter starts reasoning in terms of the v1 version.

chore: Retain EC2NodeClass reference information during the conversion

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

…n (#1544)
Fixes #N/A 
- Backport PRs

chore: Backport conversion webhooks changes for v0.37.x

---

kwok/README.md
test/pkg/environment/common/environment.go

Fixes #N/A 
/kind failing-test 
/kind cleanup
Now, e2e testing always failing, the reason is the `NodeClassRef` is not allow slash and kwok provider still using it.
so,this is follow up https://github.com/kubernetes-sigs/karpenter/pull/1516 , update NodeClassRef  for kwok provider.
/cc @jigisha620 @jonathan-innis
`.github/workflows/kind-e2e.yaml`

chore: do not set version to NodeClassRef on test environment.

---

pkg/controllers/nodeclaim/lifecycle/controller.go

Fixes #N/A 
Updates the max delay of the NodeClaim lifecycle controller such that the request exponentially backs off through NodeClaim expiration if the NodeClaim fails to register.

chore: update max delay for NodeClaim lifecycle controller

---

designs/nodeclaim-termination-grace-period.md

Design for #743 
Implementation PR: https://github.com/kubernetes-sigs/karpenter/pull/916
RFC for support for `NodeClaim.spec.terminationGracePeriod` (nodeDrainTimeout)

docs: RFC for disruption.terminationGracePeriod feature

---

pkg/controllers/disruption/validation.go
pkg/controllers/nodeclaim/consistency/controller.go

Fixes #N/A 
fix golangci-lint check error
```bash
❯ make verify
go mod tidy
go generate ./...
hack/validation/kubelet.sh
hack/validation/taint.sh
hack/validation/requirements.sh
hack/validation/labels.sh
hack/validation/resources.sh
hack/validation/status.sh
cp -r pkg/apis/crds kwok/charts
hack/kwok/requirements.sh
hack/kwok/conversion.sh
hack/dependabot.sh
hack/boilerplate.sh
go vet ./...
cd kwok/charts && helm-docs
INFO[2024-08-17T22:48:35+08:00] Found Chart directories [.]                  
INFO[2024-08-17T22:48:35+08:00] Generating README Documentation for chart .  
golangci-lint run
pkg/controllers/nodeclaim/consistency/controller.go:125:42: printf: non-constant format string in call to fmt.Errorf (govet)
log.FromContext(ctx).Error(fmt.Errorf(string(issue)), …
```

chore: non-constant format string in call to fmt.Errorf

---

go.mod
kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
This bumps the `go.mod` to use the `1.23` toolchain so that we can start leveraging go 1.23 with iterators!

chore: Bump go to use 1.23

---

.golangci.yaml
test/pkg/environment/common/monitor.go

Fixes #N/A 
Replace `exportloopref` with `copyloopvar` (see https://go.dev/blog/loopvar-preview for more detail)
```console
cd . && golangci-lint run 
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
```
**Does this change impact docs?**

ci: Enable `copyloopvar` in linter

---

pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/terminator.go
pkg/test/daemonsets.go
pkg/test/expectations/expectations.go

Fixes https://github.com/kubernetes-sigs/karpenter/issues/1133
Fixes https://github.com/aws/karpenter-provider-aws/issues/5858
This change updates the pod drain logic so that we fully wait for a pod group termination to complete before we proceed to the next eviction group

fix: Wait for pods to be fully terminated in groups

---

Makefile
hack/mutation/conversion_webhook_injection.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
Fixes an issue where k8s expects a conversion webhook is enabled (but it isn't) due to applying CRDs from the repo but the webhook.
Make presubmit

fix: enable webhooks by default v34

---

Makefile
hack/mutation/conversion_webhook_injection.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
Fixes an issue where k8s expects a conversion webhook is enabled (but it isn't) due to applying CRDs from the repo but the webhook.
Make presubmit

fix: enable webhooks by default v36

---

Makefile
hack/mutation/conversion_webhook_injection.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
Fixes an issue where k8s expects a conversion webhook is enabled (but it isn't) due to applying CRDs from the repo but the webhook.
Make presubmit

fix: enable webhooks by default v35

---

Makefile
hack/mutation/conversion_webhook_injection.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
Fixes an issue where k8s expects a conversion webhook is enabled (but it isn't) due to applying CRDs from the repo but the webhook.
Make presubmit

fix: enable webhooks by default v33

---

pkg/operator/operator.go
pkg/webhooks/webhooks.go

Fixes #N/A 
Now that webhooks are enabled by default, if a user has a network policy that blocks the webhook port and the webhook is enabled then Karpenter will crash.
make presubmit

fix: handle webhook inability to connect error v35

---

pkg/operator/operator.go
pkg/webhooks/webhooks.go

Fixes #N/A 
Now that webhooks are enabled by default, if a user has a network policy that blocks the webhook port and the webhook is enabled then Karpenter will crash.
make presubmit

fix: handle webhook inability to connect error v36

---

pkg/operator/operator.go
pkg/webhooks/webhooks.go

Fixes #N/A 
Now that webhooks are enabled by default, if a user has a network policy that blocks the webhook port and the webhook is enabled then Karpenter will crash.
make presubmit

fix: handle webhook inability to connect error v33

---

pkg/operator/operator.go
pkg/webhooks/webhooks.go

Fixes #N/A 
Now that webhooks are enabled by default, if a user has a network policy that blocks the webhook port and the webhook is enabled then Karpenter will crash.
make presubmit

fix: handle webhook inability to connect error v34

---

pkg/webhooks/webhooks.go

fix: Fix spurious transport errors (v0.36.x)

---

pkg/webhooks/webhooks.go

fix: Fix spurious transport errors (v0.34.x)

---

pkg/webhooks/webhooks.go

fix: Fix spurious transport errors (v0.33.x)

---

pkg/webhooks/webhooks.go

fix: Fix spurious transport errors (v0.37.x)

---

pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/types.go
pkg/controllers/state/statenode.go

Fixes #N/A 
Removes eventing for state nodes that don't have NodeClaims (non-Karpenter managed nodes)
make presubmit

chore: don't emit disruption events for non-karpenter nodes

---

pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/disruption/suite_test.go

Fixes #N/A 
Fix unintentionally importing envtest in our main code path. This was causing us to import `sigs.k8s.io/controller-runtime/envtest` which was causing startup to fail with
```
panic: mkdir /tmp/kubebuilder-envtest: read-only file system
goroutine 1 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/testing/addr.init.0()
sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/testing/addr/manager.go:57 +0x15c
```

fix: Fix unintentionally importing envtest when running NewTestingQueue

---

kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodepool.go
pkg/apis/v1/nodepool_default_test.go

Fixes #N/A 
Adds default disruption stanza in for v1 NodePools that was erroneously removed prior to v1. Users who applied the `v1` version of the nodepool without the disruption stanza will have Consolidation disabled. This fixes it so that applying the v1beta1 or v1 version of the same nodepool will return the same nodepool.
make test

fix: add default disruption stanza

---

kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/terminator/terminator.go
pkg/controllers/nodeclaim/consistency/controller.go
pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/nodeclaim/podevents/controller.go
pkg/controllers/nodeclaim/termination/controller.go
pkg/controllers/nodeclaim/termination/suite_test.go
pkg/controllers/nodepool/readiness/controller.go
pkg/controllers/nodepool/validation/controller.go
pkg/controllers/state/statenode.go
pkg/scheduling/taints.go
pkg/utils/pretty/pretty.go
pkg/utils/termination/termination.go

Fixes #1578
This change ensures that calls to Patch that would fully replace portions of the spec like lists continue to conflict if the resource has changed since the controller first retrieved the resource.
This fixes the issue in #1578 where resource quantities are converted to different strings during deserialization and then re-serialization back by ensuring that the request that we send to the apiserver only represents the parts of the resource that we intend to change.
This allows us to keep the NodeClaim immutability checks that we have.

fix: Ensure all patch calls can conflict when resource version doesn't match

---

pkg/controllers/nodeclaim/lifecycle/liveness.go

Fixes #N/A 
The current liveness TTL has a small race condition. It's possible that the first condition check `l.clock.Since(registered.LastTransitionTime.Time) < registrationTTL` can return a `true` value where `registrationTTL - l.clock.Since(registered.LastTransitionTime.Time) > 0`; however, since the clock can advance while we are in this conditional statement, by the time we get to the line `return reconcile.Result{RequeueAfter: registrationTTL - l.clock.Since(registered.LastTransitionTime.Time)}, nil`, `registrationTTL - l.clock.Since(registered.LastTransitionTime.Time)` is no longer greater than 0 and is now either equal to 0 or negative.
In either case, `controller-runtime` does not respect any `RequeueAfter` value that is equal to or less than 0. Thus, this …

chore: Fix possible Registration TTL race condition

---

pkg/apis/v1/nodepool_conversion.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
pkg/controllers/provisioning/suite_test.go

Fixes https://github.com/aws/karpenter-provider-aws/issues/6987
Ensure that we add the `compatability.karpenter.sh/v1beta1-kubelet-conversion` is propagated onto NodeClaims when NodePool's use the kubelet configuration conversion during scheduling. 
Prior to this change, it was possible for the scheduler to call the GetInstanceTypes() API with one kubelet configuration (parsed by the the `compatability.karpenter.sh/v1beta1-kubelet-conversion` annotation) which results in higher capacity/allocatable values to be passed to the scheduler. The NodeClaim wouldn't contain this annotation, though; so, when a CloudProvider goes to launch the NodeClaim or when the NodeClaim is considered later for capacity/allocatable, it might use a completely different set of values.
This change …

fix: Add compat annotation key when using NodePool's kubelet config compat annotation

---

kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
pkg/controllers/provisioning/suite_test.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
Fix hash annotation being generated from a newer NodePool than used during scheduling. This new code guarantees that the NodePool that is used during scheduling is what will be used to generate the hash annotation.
This ensures that if the NodePool changes while we are scheduling, we won't use the new configuration to generate the hash, which could lead to use putting a hash on the NodeClaim that doesn't actually represent the configuration that the NodeClaim was generated from.

fix: Fix race condition with using newer NodePool for hash annotation

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

chore: Drop stored version annotation

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

chore: Drop stored version annotation 36

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

chore: Drop stored version annotation 35

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

chore: Drop stored version annotation 34

---

pkg/apis/v1/labels.go
pkg/apis/v1/nodeclaim_conversion.go
pkg/apis/v1/nodeclaim_conversion_test.go
pkg/apis/v1/nodepool_conversion.go
pkg/apis/v1/nodepool_conversion_test.go

chore: Drop stored version annotation 33

---

pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/metrics.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/metrics.go
pkg/controllers/node/termination/terminator/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/metrics.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/metrics.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
Adding new metrics.
1. karpenter_nodes_drained_total
2. karpenter_ignored_pod_count
3. karpenter_pods_current_unbound_duration_seconds
4. karpenter_pods_bound_duration_seconds
5. karpenter_pods_unstarted_time_seconds
6. karpenter_cluster_state_unsynced_time_seconds
7. karpenter_nodes_eviction_requests_total
Added tests and tested on local cluster

chore: Additional upstream metrics

---

go.mod
go.sum
pkg/controllers/nodepool/readiness/suite_test.go
pkg/controllers/nodepool/validation/suite_test.go

Fixes #N/A 
Bump operatorpkg version

chore: Bump operatorpkg

---

kwok/main.go
pkg/controllers/controllers.go

Fixes #N/A 
Conditionally enable migration controllers when webhooks are also enabled.
Make presubmit.

fix: conditionally enable migration controllers based on webhook enablement

---

pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/state/statenode.go

Fixes #N/A 
Nodes that have the `InstanceTerminating` status condition have had cloudprovider.Delete() succeed. In cases where this delete happens asynchronously in the cloud provider (transitions from Running -> Terminating in AWS), Karpenter will wait to remove the finalizer until the cloud provider machine no longer exists (transitions from Terminating -> Terminated in AWS). Instance termination can vary from seconds to minutes, and counting these against the budget (when there's no pods on the nodes) only impacts expected performance of the disruption controller.
make presubmit and testing locally

perf: don't include terminated nodes in budget

---

pkg/controllers/migration/crd/controller.go
pkg/controllers/migration/crd/suite_test.go
pkg/controllers/migration/resource/controller.go

Fixes #N/A 
Suppresses conflict errors on custom resources by no longer using optimistic locking for an annotation we own and suppresses not found errors.

fix: spurious logging from migration controller

---

pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/state/statenode.go

cherry-pick: don't include terminated nodes in budget (#1735)

---

pkg/utils/node/node.go

Fixes #N/A 
This corrects the error type returned for the `NodeClaimForNode` utility function. Additionally, corrects some of the comments. The only reference to this utility function already correctly handled both error types so no update is needed there.
https://github.com/kubernetes-sigs/karpenter/blob/8101424eeecb2b6d82fe956f64136091cd6ce939/pkg/controllers/nodeclaim/podevents/controller.go#L71-L76

fix: correct error type for NodeClaim helpers

---

kwok/README.md

Fixes #N/A 
doc: make kwok docs better for local development 
no code change

doc: make kwok docs better for local development

---

kwok/charts/templates/clusterrole.yaml

Fixes #N/A 
Scope role permissions down to needed permissions. This includes dropping the CRD update permission that is no longer needed now that webhooks have been dropped.

chore: Scope role down to needed permissions

---

pkg/controllers/disruption/multinodeconsolidation.go

Fixes https://github.com/aws/karpenter-provider-aws/issues/7184 
Fixes a nil pointer dereference where we attempt to access a slice on nil.
make presubmit

fix: check for nil pointer dereference

---

designs/capacity-reservations.md

Fixes #N/A 
This Capacity Reservation RFC proposes upstream changes for proposals initially made in the [`aws/karpenter-provider-aws` ODCR RFC](https://github.com/aws/karpenter-provider-aws/blob/main/designs/odcr.md). It describes changes to the scheduler, the CloudProvider interface, and consolidation that need to be made to ensure that capacity reservations work properly across all clouds.
It also proposes the introduction of the `CapacityReservations` feature flag in `ALPHA`. 

RFC: Capacity Reservations

---

pkg/controllers/nodeclaim/expiration/controller.go
pkg/controllers/nodeclaim/expiration/suite_test.go

Fixes #N/A 
Currently, the expiration controller reconciles against all NodeClaim updates, and doesn't have a check to ensure that the NodeClaim hasn't already been terminated. This can result in duplicate expiration attempts against the same NodeClaim. The main problem with this (other than unnecessary deletes) is that we increment the expiration metric each time.
This change ensures we don't double count expirations through two mechanisms:
a. Check that the NodeClaim's deletion timestamp is zero before proceeding with expiration.
b. Only enqueue requests for NodeClaims when they are first added to the informer cache.
`make test`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix: dedupe expiration reconciliations

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go

Fixes #N/A 
When a pod gets deleted, `karpenter_pods_current_unbound_time_seconds` and `karpenter_pods_unstarted_time_seconds` should also get deleted.
`manually tested`

Fix pod metrics that don't get deleted when the pod is deleted

---

designs/node-repair.md

Fixes #N/A 
The purpose of this RFC is to Propose option around the best ways to support node auto repair for unhealthy Karpenter provisioned nodes. Related issue: https://github.com/kubernetes-sigs/karpenter/issues/1659
- N/A

RFC: Node Auto Repair

---

pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/initialization_test.go
pkg/controllers/nodeclaim/lifecycle/termination_test.go

Fixes #N/A 
This PR makes two changes to the NodeClaim lifecycle controller to ensure node leases aren't leaked:
- The NodeClaim must be registered before being initialized. This ensures NodeClaims aren't candidates for voluntary disruption mechanisms if the Node hasn't had the termination finalizer added by the registration sub-reconciler.
- When terminating a NodeClaim, only delete the associated Nodes if the NodeClaim is registered. Similar to the first change, this ensures we don't delete Nodes which don't have Karpenter's termination finalizer. These Nodes should be removed out-of-band by CCM once the underlying instance has terminated.
`make test`
By submitting this pull request, I confirm that my contribution is made under the terms …

fix: ensure node leases aren't leaked

---

go.mod
go.sum
pkg/controllers/controllers.go

Fixes #N/A 
- Adding status controller to provide metrics on node status conditions 
- Operatorpkg now supports firing metrics from client objects https://github.com/awslabs/operatorpkg/pull/89
- N/A

feat: Add status conition controller for node objects

---

pkg/controllers/provisioning/scheduling/metrics.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
Add metric for karpenter_scheduler_unfinished_work_seconds.
`manually tested`

chore: Add unfinished_work_seconds metric

---

go.mod
go.sum
pkg/controllers/controllers.go

Fixes #N/A 
- Bump operatorpkg package to include object based metrics. The new auto generated metrics will look as such:
```
operator_<object kind>_status_condition_transitions_total
operator_<object kind>_status_condition_transition_seconds
operator_<object kind>_status_condition_current_status_seconds
operator_<object kind>_status_condition_count
operator_<object kind>_termination_current_time_seconds
operator_<object kind>_termination_duration_seconds
```
- N/A

chore: Bump operatorpkg to include object based metrics

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/state/metrics.go

Fixes #N/A 
Buckets were too small (maxed out at 10) for metrics that normally reach above 10s.
make presubmit

chore: increase bucket sizes for pod scheduling metrics

---

pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topologygroup.go

Fixes #N/A 
Unregister the topology domain when failing to create a NodeClaim so that we don't hold topology domains around for hostname. Prior to this change, we weren't removing a mock domain that we would create for a topology on NewNodeClaim(). As a result, we would continually expand the number of hostname domains, making hostnmae topology spread and hostname anti-affinity way more inefficient than it should have.
__Example: Debug Image showing ~53,000 domains after only a few seconds iterating in the scheduling loop__
__Example: Debug Image showing only a single domain after only a few seconds iterating in the scheduling loop__
By submitting this pull request, I confirm that my contribution is made under the terms of …

perf: Unregister the topology domain when failing NodeClaim creation

---

pkg/controllers/provisioning/scheduling/existingnode.go
pkg/utils/resources/resources.go

Fixes #N/A 
We were recalculating `n.Available()` every time we were running through a scheduling loop which didn't end up being a cheap check when we were calculating pods for existing nodes

perf: Drop unneeded recalculation for resources and available

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
Prefilter instance types when constructing NodePools to reduce the amount of work used to compute the remaining instance types based on the NodeClaim requirements within pod scheduling in the scheduling loop

perf: Pre-filter instance types on nodepool requirements

---

pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topologygroup.go

Fixes #N/A 
Don't reparse the selector on the TopologyGroup each time we validate whether a pod matches a selector. The call to `metav1.LabelSelectorAsSelector` causes a regex parse of the selector which is expensive to compute during the scheduling loop

perf: Don't reparse selector on each toplogy select check

---

pkg/controllers/provisioning/scheduling/topology_test.go
pkg/controllers/provisioning/scheduling/topologygroup.go

Fixes #N/A 
This change updates our iteration over domains for TSC, affinity, and anti-affinity. Often, we have cases where we have available domains across the cluster, but those domains aren't available for the node we are currently on. This is specifically true with hostname requirements where there is only one option that the node can carry. 
Rather than looping through all domain options and adding those as possibilities when they were never really possible because the node doesn't support it, this change adds an optimization to only loop through the available node domains if it's shorter than all available domains. 
For hostname, this turns our O(node) operation into an O(1) operation to validate whether the pod can fit on the node.  …

perf: Improve TopologyGroup node domain iteration

---

pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/queue.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
Cache pod request calculations in memory during scheduling -- this prevents us from calling requests.RequestsForPods a ton of times during the scheduling simulation which causes us to reconstruct the requests. We can calculate this once at the beginning of the scheduling simulation and then just reached for the pre-computed cached value anytime we are trying to use a pod's requests

perf: Cache the pod request calculation in memory

---

kwok/cloudprovider/cloudprovider.go
kwok/main.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/controllers.go
pkg/controllers/node/health/controller.go
pkg/controllers/node/health/suite_test.go
pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/metrics/constants.go
pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/options.go

Fixes #N/A 
- RFC: https://github.com/kubernetes-sigs/karpenter/pull/1768
- This PR is the implementation of the recommend solution defined in the node repair RFC 
- Defining a cloud provider interface `RepairPolicy` that will support node conditions that Karpenter will forcefully terminate nodes. The cloud provider policies will be unhealthy conditions a node can enter and the duration for Karpenter to react. 
- `make resubmit`

feat: Node Repair implementation

---

pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
Cache taints when checking pod tolerations for existing nodes. We were reconstructing these taints each time we attempted to schedule a pod, but we can realistically calculate this once and then re-use this calculated value

perf: Cache taints for existing nodes

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go

Fixes #N/A 
Fix changing name from `karpenter_provisioning_scheduling_undecided_time_seconds` to `karpenter_scheduling_undecided_time_seconds` 

chore: Fix undecided time naming

---

.github/workflows/kind-e2e.yaml

Fixes #N/A 
Drop running Kind E2Es on our main push until we get a better signal from these jobs

ci: Drop running kind jobs on main until they are green

---

pkg/utils/termination/termination.go

Fixes #N/A 
This fixes an issue where during deletion, the generation of an object is incremented and then the status condition controller we use transitions the root condition of the object to `Unknown` due to a mismatch in `lastSeenGeneration` and `currentGeneration` for other status conditions.
Unit tests.

chore: fix nodeclaim going unknown during instance termination

---

pkg/controllers/metrics/pod/controller.go

Fixes #N/A 
Add `scheduled` prometheus label for the `pod_state` metrics

chore: Add pod scheduled prometheus label

---

go.mod
go.sum
pkg/test/metadata.go

Fixes #N/A 
Bumps operatorpkg to include https://github.com/awslabs/operatorpkg/pull/106. This improves the metrics produced by the status controller by setting the LastTransitionTime to the creation timestamp (if it was previously unset, transitioning to unknown).
Tested in operatorpkg

deps: bump operatorpkg

---

pkg/controllers/disruption/helpers.go

Fixes #N/A 
Updates the disruption budget eventing to only report budgets as blocked if there are zero allowed disruptions, and a non-zero number of nodes. Otherwise, this event is always reported NodePools with zero nodes.

fix: spurious disruption budget eventing

---

go.mod
go.sum
pkg/controllers/controllers.go

Fixes #N/A 
This bumps operatorpkg to the latest which allows us to inject additional labels into status condition metrics
```
➜  karpenter-provider-aws git:(main) curl localhost:8080/metrics | grep operator_nodeclaim
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  858k    0  858k    0     0   936k      0 --:--:-- --:--:-- --:--:--  935k# HELP operator_nodeclaim_status_condition_count The number of an condition for a given object, type and status. e.g. Alarm := Available=False > 0
operator_nodeclaim_status_condition_count{karpenter_k8s_aws_ec2nodeclass="default",karpenter_sh_nodepool="default",name="default-2d4jt",namespace="",reason="AwaitingReconciliation",status="Unknown",type="Initialized"} …
```

chore: Bump operatorpkg with adding additional labels to status condition controllers

---

pkg/controllers/provisioning/scheduling/preferences.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/suite_test.go

Fixes https://github.com/kubernetes-sigs/karpenter/issues/1337
This change ensures that we consider _all_ nodeAffinity terms when determining if the DS is going to schedule to the node.

fix: Fix handling for multiple Daemonset nodeAffinity selectorTerms

---

pkg/controllers/controllers.go

Fixes #N/A 
Add the `karpenter_sh_initialized` label key to our metric label dimensions for nodes

chore: Add initialized label key to metric labels

---

pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/launch.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/nodeclaim/lifecycle/suite_test.go

Fixes https://github.com/aws/karpenter-provider-aws/issues/7494
This ensures that we always set the `observedGeneration` for the status condition to the latest generation even for status conditions on NodeClaims that have already been marked as `True`.
```
➜  karpenter-provider-aws git:(main) k get nodeclaims
NAME            TYPE         CAPACITY    ZONE         NODE                                            READY   AGE
default-5x87w   c6gd.large   on-demand   us-west-2d   ip-192-168-98-14.us-west-2.compute.internal     True    83s
default-cmsrt   c6gd.large   on-demand   us-west-2a   ip-192-168-55-87.us-west-2.compute.internal     True    83s
default-hl8xp   c6gd.large   on-demand   us-west-2a   ip-192-168-142-174.us-west-2.compute.internal   True    83s
default-mfkxj …
```

fix: Ensure we keep observedGeneration up-to-date even when resource has completed

---

pkg/controllers/controllers.go
pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
This change includes the time a pod spent waiting for batching in pod scheduling duration.
Unit test.
Example in metrics change for single pod:
```
before moving ackPods
karpenter_pods_scheduling_decision_duration_seconds_bucket{le="0.05"} 0
karpenter_pods_scheduling_decision_duration_seconds_bucket{le="0.1"} 1
after moving ackPods
karpenter_pods_scheduling_decision_duration_seconds_bucket{le="1"} 0
karpenter_pods_scheduling_decision_duration_seconds_bucket{le="1.25"} 1
```
Moving `ackPods` has added the 1 second coming from `maxIdleBatching` to the total time it takes to schedule.

fix: move pod ack to when pod is first seen by Karpenter

---

.github/workflows/stale.yaml

Fixes #N/A 
This change updates the issue stale-bot to change our triage flow so that we have the following flow for removing issues quicker with the bot:
1. Issues that are marked as `triage/needs-information` but are not updated within 14d are automatically staled. These are then automatically closed within 14d.
2. Issues that are marked as `triage/solved` but are not updated within 7d are automatically staled. These are then automatically closed within 7d.

chore: Update issue stale-out to use triage flow

---

hack/kwok/requirements.sh
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml

Fixes #N/A 
Updates the validation logic for the kwok CRDs to allow the `karpenter.kwok.sh/kwoknodeclass` label.

fix: nodeclass label validation for kwok CRDs

---

pkg/controllers/node/health/controller.go
pkg/controllers/node/health/suite_test.go

Fixes #N/A 
- Avoid creating multiple log message on a repair action for an unhealthy node

chore: Avoid multiple logs messages for the node health controller

---

pkg/controllers/provisioning/scheduling/events.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
Creates an event any time a nodepool isn't considered because it has no instance types at the time of provisioning that can be used
make presubmit

feat: add event for prefiltered instance types

---

kwok/README.md
kwok/cloudprovider/helpers.go
kwok/main.go
kwok/options/options.go

Implements #1848
Adds a new flag and environment variable to the KWOK cloud-provider to provide a way to use custom instance-types at runtime (currently requires recompiling). The main use-case is not having to maintain a unique image for each combination of instance-types.
Included some boiler-plate for options; can remove if preferred
Locally tested with default and custom instance-types
---

feat: allow custom kwok instance-types at runtime

---

pkg/apis/v1/nodeclaim_status.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/events/events.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/suite_test.go
pkg/controllers/node/termination/terminator/terminator.go
pkg/controllers/state/statenode.go
pkg/events/suite_test.go

Fixes #N/A 
Add's a new nodeclaim condition `DisruptionCandidate` which is set when a nodeclaim is being disrupted, and is applied after the disruption taint is set. The `DisruptionCandidate` nodeclaim condition contains the reason why the nodeclaim is being terminated (e.g `node worker-mgn6n/ip-10-115-200-242.us-east-2.compute.internal  was single node consolidated`).
The motivation for this new nodeclaim condition is so that when evicting pods, we can look up this condition and use the condition's message in the pod event.
Example of what the pod events look like now from testing in our clusters:
```
keda                                          85s         Normal    Evicted                           pod/keda-admission-webhooks-5bd6b554ff-tn25h …
```

feat: expose nodeclaim disruption through new disruption condition, improves pod eviction event message

---

pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/drift.go
pkg/controllers/disruption/events/events.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/types.go
pkg/controllers/state/statenode.go
pkg/utils/pretty/pretty.go

Fixes #N/A 
This change removes the usage of the wording `state node` throughout our logging, eventing since this means little when it comes to exposing this out to a user. This just removes the word `state` so that it's clear that it's just about the Node on the cluster

chore: Remove usage of 'state node' in eventing, logging, and errors

---

kwok/main.go
pkg/controllers/controllers.go

Fixes #N/A 
- Exposing clusters to allow cloud provider to be able to pull data on cluster state and scheduling simulation 
- N/A

chore: Expose cluster state to allow provider to view the state of the cluster

---

kwok/apis/crds/kwok.karpenter.sh_kwoknodeclasses.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/operator/operator.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
pkg/webhooks/webhooks.go

Fixes #N/A 
This change updates the conversion webhook check that we added to the latest pre-v1.0 patch versions so that we crash when we have an issue calling the v1 conversion endpoint converting from v1beta1, not when we get any error -- this allows the v1 CRD to be deployed after the application is deployed.
This also logs errors if we get any unknown errors when calling this API just in case there are errors that we are getting in this health check that are unexpected and we don't see.
This also ensures that this health check will continually fire throughout the lifetime of the process so that if the CRD is updated and deployed later after the application is deployed or if the NodePools aren't deployed until after the process is started, the check continues to be …

fix: Modify conversion webhook check to check for v1 version existence

---

pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/operator/operator.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
pkg/webhooks/webhooks.go

Fixes #N/A 
Pulls in changes from #1914 as a cherry-pick

fix: Modify conversion webhook check to check for v1 version existence (cherry-pick v0.33.x) 

---

pkg/controllers/node/health/controller.go

Fixes #N/A 
- Add an ignore duplicate nodeclaim check for the repair controller to avoid re-queuing on a miss configured state 

chore: Ignore duplicate nodeclaim error in the repair controller

---

pkg/cloudprovider/types.go
pkg/controllers/nodeclaim/lifecycle/launch.go
pkg/controllers/nodeclaim/lifecycle/launch_test.go

Fixes #N/A 
This change allows CloudProviders to not just affect the condition message when the Create returns an error but also to affect the condition reason. 
This change is a breaking change since any CloudProvider that uses the CreateError type now needs to specify a "reason" value with the CreateError or will get errors when trying to assign the reason to the Launched status condition.
We were already supporting adding a custom error message but we'd like to start allowing classification of "error codes" back from CloudProviders but specifying well-structured custom reasons. We may be able to build on this for metrics and when considering things like #1910 which may propagate similar information down into the degraded condition based on the failure code that …

BREAKING: Allow custom condition reasons to be returned from Create

---

pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/events/events.go
pkg/controllers/node/health/events.go
pkg/controllers/node/termination/terminator/events/events.go
pkg/controllers/node/termination/terminator/suite_test.go
pkg/controllers/nodeclaim/consistency/events.go
pkg/controllers/nodeclaim/lifecycle/events.go
pkg/controllers/provisioning/scheduling/events.go
pkg/events/reason.go

Fixes #1897  
1. converts string literals as reasons of event to constant
2. pull up them to the package `events`
- i think `events` is enough over `apis` or under that 
- test or e2etest not yet, cannot run tests and more details would be written in a thread.
- when finding double quoted strings, they are only exist in the `events` package.
-  except, `"InsufficientCapacityError"` which also is in `cloudprovider/metrics` package.

chore: move event reasons to the package and as constants

---

pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/disruption/suite_test.go
pkg/test/ratelimitinginterface.go

Fixes #N/A 
Use the `TypedRateLimitingQueue` and other Typed structs/interfaces as opposed to their non-typed deprecated forms

chore: Use non-deprecated TypedRateLimitingQueue

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
This change fixes the scheduling benchmarking so that it accurately validates the actual scheduling function by making some modifications to the NodePools and pods that are input into the scheduling function so that it provisions nodes for all of the pods and doesn't bail early.
NOTE: We still have an issue where not all pods will schedule when going through these benchmarks due to the randomness generated from the pods -- we should resolve this so we ensure that all pods schedule and that we get more accurate benchmarking results.
```
scheduled 10110 against 32 nodes in total in 89.520585ms with minValues included false 112934.91882341921 pods/sec
400 instances 10 pods    2 nodes  930.06µs per scheduling     93.006µs per pod
400 …
```

fix: Fix scheduling benchmarking to not bail due to limits or same UUID

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
Use self-affinity to ensure that all pods schedule when executing the scheduling benchmark. This also expands the test case to run up to 20,000 pods since the tests are executing quicker now
```
scheduled 40151 against 8031 nodes in total in 59.075917891s 679.6508870853593 pods/sec
400 instances 1 pods      1 nodes     183.429µs per scheduling      183.429µs per pod
400 instances 50 pods     10 nodes    42.179802ms per scheduling    843.596µs per pod
400 instances 100 pods    20 nodes    93.097613ms per scheduling    930.976µs per pod
400 instances 500 pods    100 nodes   415.767736ms per scheduling   831.535µs per pod
400 instances 1000 pods   200 nodes   890.825521ms per scheduling   890.825µs per pod
400 instances 1500 pods …
```

chore: Use self-affinity to ensure all pods schedule

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A 
The heap profile wasn't actually capturing the full run on the scheduling benchmark 

fix: Fix heap profile benchmarking

---

pkg/cloudprovider/types.go

Fixes #N/A 
DeepCopying this field wasn't necessary and was resulting in the garbage collector having to do more work than necessary to clean-up the copying
```
scheduled 40151 against 8031 nodes in total in 53.357417524s 752.4914409873793 pods/sec
400 instances 1 pods      1 nodes     128.608µs per scheduling      128.608µs per pod
400 instances 50 pods     10 nodes    43.255586ms per scheduling    865.111µs per pod
400 instances 100 pods    20 nodes    88.47598ms per scheduling     884.759µs per pod
400 instances 500 pods    100 nodes   347.842527ms per scheduling   695.685µs per pod
400 instances 1000 pods   200 nodes   701.784041ms per scheduling   701.784µs per pod
400 instances 1500 pods   300 nodes   1.212005917s per scheduling …
```

perf: Remove deep-copying the allocatable resource list

---

README.md

Fixes #N/A 
Updates the README to include both Working Group and Issue Triage meeting information. This change:
- Adds the new Issue Triage meeting schedule
- Reorganizes the community meeting section for better clarity
- Maintains existing Working Group meeting information
- Consolidates meeting resources and links
N/A

chore: Update the README with update community meetings times

---

pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
Fix test flakes coming from the `ConsolidationState()` and DataRace checks inside of the test suite. Resetting the cluster state without using a wait group to complete the goroutine was causing the data race during the Data Race test and not properly resetting all of the details inside of cluster state was causing the `ConsolidationState()` test to fail.

test: Fix `ConsolidationState()` test failure in state testing

---

pkg/controllers/node/health/controller.go
pkg/controllers/node/health/metrics.go
pkg/controllers/node/health/suite_test.go
pkg/metrics/constants.go

Fixes #N/A 
Add dedicated metrics for tracking unhealthy disrupted nodeclaims
This PR introduces a new of metric specifically for tracking nodeclaims that were disrupted due to unhealthy states, separate from other disruption types. This separation enables:
- More precise monitoring of repair-related disruptions
- Better alerting capabilities for node health issues
- Distinct label sets optimized for repaired node scenarios
This change improves observability by distinguishing between health-related node disruptions and other forms of disruption 

feat: Create Unhealthy Disrupted Nodeclaim Metric

---

pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
This change ensures that we don't perform expensive operations that show-up in the CPU profile and show-up in our heap analysis to print the nodeClaimRequirements and performing resources.Merge. 
These changes were executed against the scheduling benchmark (which showed negligible performance changes) and a live test that deploys 20,000 pods to the cluster and generates 10,000 nodes (with two pods per node constrained by the size of the instance types on NodePools). Prior to the change, this test took __31m49s__. After the change, the same test case takes __26m34s__ (a 5m15s improvement).
```
scheduled 40151 against 8031 nodes in total in 59.198867831s 678.2393223232317 pods/sec
400 instances 1 pods      1 nodes     183.666µs per …
```

perf: Capture InstanceTypeFilterErrors in error structs and don't print them until the end

---

pkg/scheduling/requirement.go
pkg/scheduling/requirements.go

Fixes #N/A 
This change adds the `HasIntersection` method which allows the `Intersects` check to validate whether two keys have an intersection with their values without creating new sets under the hood -- greatly reducing the number of allocations that we do for sets and reducing the amount of time that the garbage collector needs to spend cleaning them up.
These changes were executed against the scheduling benchmark (which showed negligible performance changes) and a live test that deploys 20,000 pods to the cluster and generates 10,000 nodes (with two pods per node constrained by the size of the instance types on NodePools). Prior to the change, this test took __27m17s__. After the change, the same test case takes __21m36s__ (a 5m41s improvement).
```
=== RUN …
```

perf: Don't create new sets when checking compatibility

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
Add more scheduling logging to capture progress on creating nodeclaims in the cluster for long scheduling loops and add details on how many pods are in a terminating state in the debug logs

chore: Add more scheduler logging for pods

---

pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/queue.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
Cache requirements for pods alongside requests so we don't have to spend memory continually re-creating the pod requirements when we are iterating through the pods in our scheduling loops. This also prevents the garbage collector from having to run as frequently since there will be more live memory that is being used in the scheduling loop
These changes were executed against the scheduling benchmark (which showed negligible performance changes) and a live test that deploys 20,000 pods to the cluster and generates 10,000 nodes (with two pods per node constrained by the size of the instance types on NodePools). Prior to the change, this test took __27m17s__. After the change, the same test case takes __25m24s__ (a 1m53s improvement).
```
=== RUN …
```

perf: Cache requirements for pods alongside requests

---

pkg/controllers/provisioning/suite_test.go

Fixes #N/A 
This ensures that we don't trigger a 5s move on the batcher during testing since this is exactly the same as the idle duration and was causing flakes in testing like in https://github.com/kubernetes-sigs/karpenter/actions/runs/13143439974/attempts/1?pr=1950

test: Ensure that we don't step the idle duration since this can cause the batcher to exit

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
This change updates our cluster state `Synced()` logic so that we only wait for the Nodes and NodeClaims to match at the controller startup and then only check the providerID after that point.
This allows us to save on allocations that we were spending on DeepCopying NodeClaims and Nodes as well as saving CPU time on checking this
(Note the portions of the heap that are used by the NodeClaim and Node deep copies)
(Note how there are no longer any nodes in the heap that are dedicated toward the Node and NodeClaim deep copies)

perf: Reduce the memory overhead on cluster state `Synced()`

---

pkg/controllers/nodepool/counter/controller.go

Fixes #N/A 
Add an event filter for the counter controller so that NodeClaims that do not have a providerID don't trigger reconciliation on the controller (since they won't have resolved resources yet and can't impact the resource count calculation anyways)

perf: Add event filter for NodeClaims that have resolved providerIDs

---

pkg/controllers/state/cluster.go

Fixes #N/A 
When hydrating DaemonSet pod data to handle resource quotas and mutating webhooks, we can reduce the number of pods that we list by using the same labelSelector that the DaemonSet does to perform the list against the cache

perf: Don't DeepCopy DaemonSet Pods

---

pkg/cloudprovider/types.go
pkg/controllers/nodeclaim/lifecycle/termination_test.go
pkg/utils/termination/suite_test.go
pkg/utils/termination/termination.go

Fixes #N/A 
With karpenter aws-provider we saw an issue where eventual consistency with EC2 can cause the underlying instance to be still around even when cloudProvider.Delete() call is made once against it. To tackle this in this PR, we remove `InstanceTerminating` status condition if, on cloudProvider.Get() we don't see deletion timestamp on the nodeClaim.
Added test for it.

chore: Update nodeclaim finalization flow to not depend on cloudProvider.Get()

---

pkg/scheduling/requirements.go

Fixes #N/A 
Using the `Difference` function results in us creating a new set when we could have just iterated through the map and read the existing values

perf: Remove using `Difference()` from set creation

---

pkg/cloudprovider/suite_test.go
pkg/cloudprovider/types.go

Fixes #N/A 
Support error unwrapping with our custom error types -- our current error types wouldn't recognize the inner error types because they didn't implement `Unwrap()`

chore: Ensure that we implement `Unwrap` to support `errors.As`

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topology_test.go
pkg/controllers/provisioning/scheduling/topologydomaingroup.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/controllers/provisioning/scheduling/topologynodefilter.go
pkg/scheduling/taints.go
pkg/utils/pod/scheduling.go
test/pkg/environment/common/expectations.go

Fixes #430 
This PR adds support for the following topology spread constraint fields:
- `matchLabelKeys`
- `nodeAffinityPolicy`
- `nodeTaintsPolicy`
`make test`

feat: support new topologySpread scheduling constraints

---

go.mod
test/pkg/environment/common/default_kowknodeclass.yaml
test/pkg/environment/common/default_nodepool.yaml
test/pkg/environment/common/environment.go
test/pkg/environment/common/setup.go
test/suites/perf/scheduling_test.go
test/suites/perf/suite_test.go

Fixes #N/A 
##Description**
This PR extends the current KowkNodeClass implementation in the E2Es to support cloudprovider defined NodeClass, allowing for more flexible and reusable test management across different cloud providers integration testing.
- Added abstraction layer for provider-specific implementations
- Updated node lifecycle handlers for generic support

test: Expand KOWKNodeClass to Support Generic NodeClass for E2E tests

---

kwok/cloudprovider/cloudprovider.go

Fixes #N/A
In order to delete a Node or NodeClaim by termination, the current behaviour is that Karpenter calls [`EnsureTerminated`](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/utils/termination/termination.go#L34) which calls the cloudProvider's implementation of `Delete` in order to "ensure" the underlying instance is actually deleted from the infra before removing the k8s resources. Using KWOK, there is no real backing infra, but the KWOK provider `Delete` implementation currently tries to delete the actual NodeClaim from the kubernetes api. So this becomes a chicken and egg problem because `EnsureTerminated` is expecting an `NodeClaimNotFound` error to be returned in order to proceed with the deletion (removing finalizers), but the KWOK provider cannot …

test: allow kwok provider deletion to terminate instance

---

Makefile
pkg/controllers/nodeclaim/disruption/drift_test.go

Fixes #1986 
1. change Offering.Requirements of InstanceType over Requirements for setup test; ofs.HasCompatible compare Offering.Requirements with the argument(NodeClaim.Labels in this case) -> so i don't know how the test was passed sometimes
2. fix the key for changing value to Offering.Requirements concerns since a return of lo.Keys is not sorted, the previous key was random.
a. just one changing is enough so commented another  
chore: remove trailing whitespaces in Makefile
check the test case is passed on make deflake FOCUS="should detect stale instance type drift if the instance type offerings aren't compatible with the nodeclaim"
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

ci: fix flaky test for stale instance type drift

---

pkg/controllers/provisioning/scheduling/existingnode.go

When checking if a Pod will work on an existing Node, we validate in several ways including
checking the Pods requirements vs the Node's requirements. If it fails at any step, 
we need to leave the Node's requirements unchanged. Previously we were:
1) Creating set of temporary requirements from the current node's requirements
2) Check if the Pod is compatible with them
3) Assigning those back to the Node if all compatibility checks passed
This changes the order so that we check for compatibility with the Pod first so that 
in the case of a Pod not being compatible, we can avoid the allocation that occurs when
creating the temporary set of requirements.
Unit testing & deployed
By submitting this pull request, I confirm that my contribution is …

perf: check validity before constructing a new set of requirements

---

pkg/scheduling/requirements.go
pkg/scheduling/requirements_test.go

Fixes #N/A 
Its not worth the CPU cost that it uses when there are large numbers of values for a given key.
Deployed & unit testing.

perf: remove the edit distance helper for identifying typos

---

pkg/scheduling/requirements.go

Fixes #N/A 
Returning the first error we find is both faster and allocates less. There is a tradeoff here in that we'll only report one of the reasons that a Pod won't schedule, but I think the tradeoff for faster speed & fewer allocations is worth it.
Unit testing & deployed

perf: trade off less verbose errors for faster execution

---

.github/workflows/semantic-pr.yaml

Fixes #1978 
add a workflow [sematic-pull-request](https://github.com/marketplace/actions/semantic-pull-request) to validate for each pr title would follow the conventional commits -- most of default value of parameters of the action are for this.
a write permission is required to use `wip` option, skip PRs the title is started with `[WIP]`.
no, [the limitation of trigger `pull_request_target`](https://github.com/marketplace/actions/semantic-pull-request#event-triggers)

ci: add a workflow semantic-pr

---

test/pkg/environment/common/environment.go

Fixes #2007
For now, this PR bumps up the default `Eventually` timeout to 10 minutes. E2E tests may fail if the cloud provider cannot finish provisioning an instance within the previous low 5 minute default.
Running the e2e tests in a local kind cluster.

test: increase Eventually timeout in e2e tests

---

pkg/controllers/node/health/controller.go
pkg/controllers/node/hydration/controller.go
pkg/controllers/node/termination/controller.go
pkg/controllers/nodeclaim/consistency/controller.go
pkg/controllers/nodeclaim/disruption/controller.go
pkg/controllers/nodeclaim/expiration/controller.go
pkg/controllers/nodeclaim/garbagecollection/controller.go
pkg/controllers/nodeclaim/hydration/controller.go
pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/nodeclaim/lifecycle/initialization.go
pkg/controllers/nodeclaim/lifecycle/registration.go

Fixes #N/A 
We had a number of controllers where the `Node` was not logged with `NodeClaim` or vice-versa, which makes it difficult to correlate logs across controllers

chore: Ensure that NodeClaim is always logged with Node

---

pkg/controllers/provisioning/scheduling/metrics.go

Fixes #1992
Put `karpenter_ignored_pod_count` metric under `scheduler` subsystem, new metric name is: `karpenter_scheduler_ignored_pod_count`.
1 . Made temporary changes:
```diff
diff --git a/Makefile b/Makefile
index 3029f80..ffe428d 100644
--- a/Makefile
+++ b/Makefile
@@ -67,13 +67,11 @@ delete: ## Delete the controller from your ~/.kube/config cluster
helm uninstall karpenter --namespace $(KARPENTER_NAMESPACE)
test: ## Run tests
-	go test ./pkg/... \
+	go test ./pkg/controllers/provisioning \
-race \
-timeout 20m \
-		--ginkgo.focus="${FOCUS}" \
--ginkgo.randomize-all \
-		--ginkgo.v \
-		-cover -coverprofile=coverage.out -outputdir=. -coverpkg=./...
+		--ginkgo.v
deflake: ## Run randomized, racing tests until the test fails to catch …
```

fix: BREAKING put karpenter_ignored_pod_count metric under scheduler subsystem

---

pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/nodeclaim/disruption/drift_test.go
pkg/controllers/nodeclaim/disruption/suite_test.go

Fixes #N/A 
This change ensures that the `Reset()` call doesn't set the Drifted reason each time to remove test flakes

test: Remove drifted reason on Reset() for `fake.CloudProvider`

---

hack/toolchain.sh

Fixes #N/A
This allows the installation of toolchain files to an arbitrary path by setting the `KUBEBUILDER_ASSETS` environment variable.  This was done in order to avoid the use of sudo in order to create and use a system path.  Backward compatibility with the original method is preserved.
I ran `make toolchain` both with and without setting the `KUBEBUILDER_ASSETS` environment variable.  Without it set, the default location of `/usr/local/kubebuilder/bin` was used and I was prompted for my password by sudo.  With it set to a path under my home directory, the indicated path was created without needing sudo, and all toolchain content was copied into place.
I then ran `make test` with `KUBEBUILDER_ASSETS` set to the path in my home directory …

chore: Install toolchain files to location provided in KUBEBUILDER_ASSETS if set

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go

Fixes #N/A 
- Update metric from `karpenter_pods_scheduling_undecided_time_seconds` to be `karpenter_pods_provisioning_scheduling_undecided_time_seconds`

chore: Update the scheduling metric name to be `karpenter_pods_provisioning_scheduling_undecided_time_seconds`

---

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go

Fixes #N/A
The recent ODCR PR [#1911](https://github.com/kubernetes-sigs/karpenter/pull/1911) broke the scheduling benchmarking test by adding a requirement for scheduling to have options in its context. 
This change introduces the standard `test.Options()` into the context prior to the benchmarking test,
I ran both `make test` and the actual scheduling test and both passed:
```
go test -tags=test_performance -run=SchedulingProfile
scheduled 40151 against 8031 nodes in total in 40.306934825s 996.1313152270939 pods/sec
400 instances 1 pods      1 nodes     96.906µs per scheduling      96.906µs per pod
400 instances 50 pods     10 nodes    27.13001ms per scheduling    542.6µs per pod
400 instances 100 pods    20 nodes    60.294949ms per …
```

test: Including test options into the scheduling benchmark context

---

.github/actions/install-deps/action.yaml
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go

Fixes #N/A 
https://github.com/kubernetes-sigs/karpenter/pull/1957

test: Fix `ConsolidationState()` test failure in state testing (#1957)

---

.github/actions/install-deps/action.yaml
kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

test: Fix `ConsolidationState()` test failure in state testing (#1957) 1.1.x

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodeclaim.go
pkg/apis/v1/nodeclaim_validation_cel_test.go
pkg/apis/v1/nodepool.go
pkg/apis/v1/nodepool_validation_cel_test.go

Fixes #N/A 
Current CEL validation allows values like `1hr` to be set in the spec which causes the resources to be stuck in a weird state.
Used this spec for nodepool:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
name: malformed
spec:
disruption:
budgets:
- nodes: 10%
consolidateAfter: 1hr
consolidationPolicy: WhenEmpty
template:
spec:
expireAfter: 12h
nodeClassRef:
group: karpenter.k8s.aws
kind: EC2NodeClass
name: default
requirements:
- key: karpenter.sh/capacity-type
operator: In
values:
- on-demand
terminationGracePeriod: 24h0m0s
```
**Before the change:** 
```
~ k apply -f malformed-nodepool.yaml
nodepool.karpenter.sh/malformed created
```
```
~ k get nodepool
NAME        NODECLASS   NODES   READY   AGE
default     default …
```

fix: update CEL validation for expireAfter and consolidateAfter fields to block invalid values like 1hr

---

kwok/charts/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/v1/nodeclaim.go

Fixes #1464
feat: Expose drifted nodeclaim condition status to printer column output. Updates the nodeclaim reconcile to not clear the condition, but set the drifted condition state to false. Tests were similarly updated for this change in behavior.

feat: Expose drifted nodeclaim condition status to printer column output

---

pkg/controllers/state/suite_test.go

fix: update range in test

---

contributing-guidelines.md

Fixes #N/A 
Adds a section to the contributor ladder doc on the process for removing reviewers and moving approvers to emiritus

docs: Add cleanup section to the contributor ladder doc

---

OWNERS_ALIASES

Fixes #N/A 
Moving @bwagner5 to emeritus since he's become less directly involved in maintaining the project
Brandon shows as < 10 contributions in the last year: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes-sigs%2Fkarpenter&var-country_name=All

chore: Move bwagner5 to emeritus maintainer

---

pkg/controllers/provisioning/scheduling/nodeclaim.go

Fixes #N/A 
Adds requirements to the InstanceTypeFilterError to ensure requirements are printed for scheduling errors.

fix: missing requirements in scheduling error log

---

kwok/cloudprovider/cloudprovider.go
kwok/cloudprovider/helpers.go

Adds the keys of all requirements for each instance-type offering to the list of Well Known Labels. 
This makes it easier to run simulations with non-KWOK NodePools (e.g. using KWOK to simulate how Karpenter would autoscale under certain circumstances in an AWS environment).
Issue: https://github.com/kubernetes-sigs/karpenter/issues/2045
Tested by running locally against a [KWOK all-in-one](https://kwok.sigs.k8s.io/docs/user/all-in-one-image) environment (pod). 
---

feat: add requirement keys of KWOK instance offerings to well-known labels

---

go.mod
go.sum
pkg/controllers/nodeclaim/lifecycle/controller.go

Fixes #N/A 
A change was made in operatorpkg upstream (https://github.com/awslabs/operatorpkg/pull/138) that means that anytime an object is deleting we will automatically update all of the status conditions to the latest generation to avoid automatically setting the Ready condition to Unknown

chore: Bump `github.com/awslabs/operatorpkg` to latest

---

pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
pkg/controllers/provisioning/suite_test.go

Fixes #N/A 
- Adding a global termination grace period to set on all NodeClaims that are owned by NodePools that don't add contain a termination grace period.
- This would be a mechanisms for cloud provider to enforce a termination grace period on all nodeClaims provided by Karpenter
- This would allow CloudProvider to avoid manipulating the nodeClaim validation rules prior to setting termination grace period 

feat: Add Global Default Termination Grace Period Variable 

---

pkg/operator/operator.go

Fixes #N/A 
This change fixes a bug in Karpenter where the leaderConfig and the regular config were sharing a token bucket for client-side rate limiting. This meant that in large scale-ups you would see logs like the log below which showed that the leader election client was getting client-side rate-limited by other requests that were made to the apiserver. This would result in leader election being lost and Karpenter would restart.
This was particularly annoying because often Karpenter was getting client-side rate limited after making a large scheduling decision, meaning that the scheduler would then have to re-calculate the decision again from the start (although it might have been able to launch some number of NodeClaims before leader election was lost).
``` …
```

fix: Create a separate leader config for different QPS/Burst

---

pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/suite_test.go

Fixes #2083
Fixes #2093 
When attempting to schedule a pending pod to existing capacity, host ports for all pods on that node are checked and influence scheduling decisions. When needing to make a new NodeClaim, there are no pods from which to get this information.
This change looks at daemon set pods that are compatible with the NodeClaimTemplate being used for the pending pods and then checks if required host ports will be available.
Unit test addition that shows pending pod does not schedule. Additionally, this log fires when run in my dev cluster:
>`
{"level":"ERROR","time":"2025-03-25T23:45:29.227Z","logger":"controller","caller":"provisioning/provisioner.go:357","message":"could not schedule …

fix: address nodeclaims being repeatedly created when host ports for a pending pod would conflict with daemons

---

pkg/controllers/nodeclaim/podevents/controller.go

Fixes #N/A 
we can deep copy nodeclaim when we need to change it. because deepcopy will not be executed if lastPodEvent has not been set before the timeout.

fix: don't need to deepcopy nodeclaim when lastPodEvent has not been set before the timeout

---

.github/dependabot.yaml
.github/workflows/run-bench-test.yaml
.github/workflows/scheduling-benchmarking.yaml

Fixes #N/A 
New CI to automatically run scheduling benchmark tests for both the existing code and proposed changes whenever a PR modifies a `.go` file. The new workflow will comment results into PR comments, and also store CPU and MEM profiles into a downloadable artifacts that reviewers and approvers can use to analyze any performance improvements or regressions. The current setup leverages the `matrix` functionality to make setting up new benchmark CI tests simple in the future. 
This is a first iteration of a CI suite for performance testing. There are a couple, sometimes contradictory natural extensions for the future:
* Automatically fail the test if performance regresses and remove performance results from PR comments
* Add Consolidation performance benchmark tests
* …

ci: Automating scheduling benchmarking testing for PRs

---

pkg/controllers/nodepool/counter/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/controllers/state/statenode.go
pkg/controllers/state/suite_test.go
pkg/controllers/state/zz_generated.deepcopy.go
pkg/utils/resources/resources.go

Fixes #N/A 
The counter controller is doing _a lot_ of repeated work by continually pulling nodes from cluster state to calculate the number of resources that a NodePool has deployed at any point in time. Rather than rebuilding the sum every time, we can use a diff-based approach where we just take the difference for resources as we make updates to the StateNodes. Likewise, when a StateNode is deleted, we just subtract the resources from the retained NodePool resources that is now stored in cluster state.
This makes our counter controller logic way more efficient and reduces CPU cycles that were given to it.

perf: Actively store NodePool resources in cluster state

---

.github/workflows/run-bench-test.yaml
.github/workflows/scheduling-benchmarking.yaml

Fixes #N/A 
The current CI is breaking with a 403: https://github.com/kubernetes-sigs/karpenter/actions/runs/13710441815
This change removes the github comment on the PR to unblock the CI while a solution can be worked on
https://github.com/DerekFrank/karpenter-testing-fork/actions/runs/14250780735

ci: Removing github comment to unblock CI

---

pkg/controllers/provisioning/scheduling/queue.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
This change ensures that we relax a pod's preferences all the way before we consider the next pod. This change will have us add the original pod back to the queue and attempt it later if we don't succeed on the first attempt. Handling preferences this way is important because we want to tee-up a scheduling timeout change to allow us to react faster to pending pods during provisioning.

perf: Relax preferences all the way per-pod

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go

Fixes #N/A 
Timeout the scheduling simulation after 1m during provisioning to ensure we make faster progress when scheduling pods/nodes. 
To validate this change, I ran simulations of large scale-ups with and without the timeout. I found that, when running the provisioning loops with the timeouts, we were significantly faster (2x) compared to running without it.
- Running scale testing with the Kwok cloudprovider

perf: Timeout scheduling simulation after 1m to schedule pods/nodes

---

Makefile
kwok/charts/README.md
kwok/charts/templates/deployment.yaml
kwok/charts/values.yaml
pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/helpers.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/suite_test.go
pkg/operator/options/options.go
pkg/test/options.go

Fixes #N/A 
This change adds an environment variable option called `PreferencePolicy` with the following definitions:
- `Respect`: Karpenter will attempt to respect all preferences as requirements. If Karpenter cannot simulate pods against the node given these requirements, it will begin removing preferences from the pod until it is able to schedule the pod. `Respect` can also block consolidation more frequently due to the way that the preference relaxation ordering is orchestrated.
- `Ignore`: Karpenter will ignore all preferences when it performs its scheduling simulations. In general, this is a more efficient way to run Karpenter because Karpenter will have to give less effort to satisfying all of the preferences on the application pods. In addition, it's currently not …

feat: Add `PreferencePolicy` as an environment variable option

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go

Fixes #N/A 
We emit pod scheduling undecided time metric when we have not made a pod scheduling decision gauge for it. If the pod gets bound to a node, we should delete this gauge.

fix: Fix pod scheduling undecided time metric

---

go.mod
go.sum
kwok/cloudprovider/cloudprovider.go
pkg/apis/v1/labels.go
pkg/apis/v1/nodepool.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/disruption/consolidation.go
pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/disruption/types.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/volumetopology.go
pkg/controllers/state/cluster.go
pkg/controllers/state/statenode.go
pkg/operator/logging/logging.go
pkg/operator/operator.go
pkg/scheduling/hostportusage.go
pkg/scheduling/taints.go
pkg/scheduling/volumeusage.go
pkg/utils/volume/volume.go

Fixes #N/A 
Add structured errors from the `serrors` package in operatorpkg. This registers the logger with anything using the operator so the logger unwraps values and prints the controller-runtime error with any structured values that were injected through the error stack.

chore: Use structured errors in logger

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/state/cluster.go
pkg/controllers/state/suite_test.go
pkg/utils/resources/resources.go

Fixes #N/A 
Is we successfully schedule a pod during a scheduling simulation but it doesn't get scheduled and after simulating again it is unschedulable, we should delete it's entry from `podsSchedulableTimes` map. We should also delete the gauge metrics emitted around this - 
1. provisioning_unstarted_time_seconds
2. provisioning_unbound_time_seconds
Added unit tests

chore: Delete podSchedulableTime and associated metric if pod can't be scheduled

---

Makefile
kwok/charts/templates/deployment.yaml
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/nodeclaim.go
pkg/controllers/provisioning/scheduling/reservationmanager.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/controllers/state/suite_test.go
pkg/operator/options/options.go
pkg/test/options.go

Fixes #N/A 
This change adds parallelism to the node filtering logic in the scheduler. It adds the `NumConcurrentReconciles` option to the scheduler to increase the number of worker threads that can do node filtering at any given point in time. This transforms the code to first validate whether the pod is eligible to schedule to the node with the `CanAdd` call and then, once it finds a successful decision, it bails out of the filtering code and calls `Add` for the decision that it found.
Since there are multiple threads that are running at a given point in time, it's possible that an element that is further down in the array may succeed before something that is earlier in the array -- to keep the same ordering, I add a check that validates that if something succeeds and …

perf: Parallelize node filtering

---

pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/metrics.go
pkg/controllers/node/termination/terminator/suite_test.go

Fixes #2021
Implements a new Prometheus metric to count pods drained during node termination, labeled by the reason for draining. This provides visibility into the number of pods affected by different termination scenarios.

feat: add karpenter_pods_drained_total metric to track pod draining by reason

---

test/pkg/environment/common/environment.go
test/suites/integration/chaos_test.go
test/suites/integration/perf_test.go
test/suites/integration/suite_test.go

Fixes #N/A 
- High Level Description: Validate that karpenter does not have any runaway scaling during provisioning or consolidation
- Source: https://github.com/aws/karpenter-provider-aws/tree/main/test/suites/chaos
- Test Cases:
* Should not produce a runaway scale-up when consolidation is enabled
* Should not produce a runaway scale-up when emptiness is enabled 

test: Migrate the Chaos suite test from the AWS Karpenter Provider

---

.github/workflows/kind-e2e.yaml

Fixes #N/A 
- Enable integration test to run on Kind clusters on PR merges
- N/A

ci: Enable Kind Cluster Testing on PR Merge

---

pkg/apis/v1/labels.go
pkg/controllers/nodeclaim/lifecycle/initialization_test.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/nodeclaim/lifecycle/registration_test.go

This commit removes the code that syncs the taints from nodeclaims to nodes. This changes the behaviour of Karpenter as it is now expected that the providers will be responsible for setting taints on nodes. By giving up control of taints to the Karpenter provider, taints can be set via the kubelet `--register-with-taints` field. This ensures that taints exist as soon as the node starts. The Karpenter node registration taint is still managed/removed by Karpenter and labels and annotations will still be synchronized here.
This commit is required to work around daemonsets, such as the EBS and EFS drivers, that do not continuously reconcile. It is common practice for these daemonsets to tolerate all taints, and thus they will race with this section of code to remove the taint. …

fix: Allow disabling syncing taints from nodeclaims to nodes (with node label)

---

pkg/controllers/node/termination/terminator/events/events.go

Fixes #N/A 
- Fix event log line pointer deference 
```
Normal    Disrupted                        pod/venomcyber-1-zsoyy2brdu                         Deleting the pod to accommodate the terminationTime 2025-05-05 15:00:39 +0000 UTC of the node. The pod was granted 29 seconds of grace-period of its 0xc00172cce8 terminationGracePeriodSeconds. This bypasses the PDB of the pod and the do-not-disrupt annotation.
```
```
Normal    Disrupted                        pod/eaterleaf-1-y93sz5tngb                          Deleting the pod to accommodate the terminationTime 2025-05-05 15:08:56 +0000 UTC of the node. The pod was granted 29 seconds of grace-period of its 30 terminationGracePeriodSeconds. This bypasses the PDB of the pod and the do-not-disrupt annotation.
```
**How was …

chore: Fix event log line for a pointer

---

.github/workflows/kind-e2e.yaml

Fixes #N/A 
- Temporarily disabling the Karpenter KPI analysis package due to test flakiness and incompatibility with recent metric changes. The package is designed to analyze key performance indicators during integration tests but requires updates to align with current Karpenter metric structures.
- Example: https://github.com/kubernetes-sigs/karpenter/actions/runs/14866169301/job/41743367742
- N/A

ci: Temporarily Disable Karpenter KPI Analysis Package

---

designs/karpenter-integration-testing.md
kwok/cloudprovider/cloudprovider.go
test/pkg/environment/common/expectations.go
test/suites/integration/nodeclaim_test.go

Fixes #N/A 
* High Level Description: Validate that action taken by the nodeclaim controllers. This validates standalone claims and the garbage collection mechanisms  
* Source: https://github.com/aws/karpenter-provider-aws/tree/main/test/suites/nodeclaim
* Test Cases: 
* Standalone NodeClaim  
* should create a standard NodeClaim based on resource requests
* should create a NodeClaim propagating all NodeClaim spec details
* should remove the cloudProvider NodeClaim when the cluster NodeClaim is deleted
* should delete a NodeClaim from the node termination finalizer 
* should delete a NodeClaim after the registration timeout when the node doesn’t register
* should delete a NodeClaim if it references a NodeClass that doesn’t exist
* should delete a NodeClaim if it …

test: Migrate the NodeClaim suite test from the AWS Karpenter Provider

---

.github/workflows/kind-e2e.yaml

Fixes #N/A 
- Removed make toolchain and to relay on `install-deps` GH action: https://github.com/kubernetes-sigs/karpenter/actions/runs/14914182759/job/41895626909
- N/A

chore: Remove mismatch with deps used for E2E tests

---

hack/install-kwok.sh
hack/kwok/stages/pod-unhealthy.yaml
test/pkg/environment/common/environment.go
test/pkg/environment/common/expectations.go
test/pkg/environment/common/setup.go
test/suites/integration/drift_test.go
test/suites/integration/suite_test.go

Fixes #N/A 
* High Level Description: Validate the expected drift functionality of each field and expected case to limit drift
* Source: https://github.com/aws/karpenter-provider-aws/tree/main/test/suites/drift
* Test Cases: 
* Budgets 
* should respect budgets for empty drift
* should respect budgets for non-empty delete drift 
* should respect budgets for non-empty replace drift 
* should not allow drift if the budgets is fully blocking 
* should not allow drift if te budget is fully blocking during a scheduled time 
* NodePool
* Static Drift 
* Annotations 
* Labels 
* Taints 
* Start-up Taints 
* Node Requirement
* Drift Failure 
* should not disrupt a drifted node if the replacement node never registers 
* should not disrupt a drifted node if the replacement node …

test: Migrate the Drift suite test from the AWS Karpenter Provider

---

test/pkg/environment/common/setup.go

Fixes #N/A 
- Use foreground deletion to make sure that all dependents are properly deleted before we move on the test next test run 
- N/A

test: Use Foreground deletion to cleanup our tests

---

test/suites/integration/drift_test.go

Fixes #N/A 
- Update `should not disrupt a drifted node if the replacement node registers but never initialized` 
- The test is designed to work off the default disruption budgets. To make the E2E tests faster we have allowed full disruption for the E2E test global nodepool. 

test: Add default disruption budgets for the drifted initialized failure tests

---

Makefile
test/pkg/environment/common/expectations.go
test/suites/integration/drift_test.go
test/suites/integration/nodeclaim_test.go

Fixes #N/A 
- Implements a ValidatingAdmissionPolicy to mock unauthorized node registration. This mechanism specifically blocks any node that attempts to join the cluster with the label 'registration: fail', providing a deterministic way to control node admission.

test: Block NodeClaim registration for E2E tests using validating admission policy 

---

test/README.md

Fixes #N/A 
- Update the Karpenter testing readme to outline the way Cloud provider can reuse the testing package defined in the in repository 
- N/A

chore: Update the testing README to define mechanism for cloud provider to run the integrated testing

---

hack/kwok/stages/pod-delete.yaml
pkg/test/pods.go
test/pkg/environment/common/expectations.go
test/suites/integration/termination_test.go

Fixes #N/A 
* High Level Description: Looks at forceful termination and termination grace period
* Source: https://github.com/aws/karpenter-provider-aws/tree/main/test/suites/termination
* Test Cases: 
* Emptiness 
* should not allow emptiness if the budget is fully blocking
* should not allow emptiness if the budget is fully blocking during a scheduled time
* should terminate an empty node
* Termination Grace Period 
* should delete pod with do-not-disrupt when it reaches its terminationGracePeriodSeconds
* Termination 
* should drain pods on a node in order

test: Migrate the Termination suite test from the AWS Karpenter Provider

---

pkg/test/daemonsets.go
pkg/test/deployment.go
pkg/test/statefulsets.go

Fixes #N/A 
- Use the objectMeta value provided from the generated pod object. It's possible to pass have conditional pod annotation, so opt for generated  pod objects 

test: Use Pod Metadata field for test objects

---

pkg/controllers/provisioning/scheduling/existingnode.go
pkg/utils/resources/resources.go

Fixes #N/A 
This change speeds-up our existing node check by doing a quick check on whether some set of resources fits rather than re-creating a new resource set every time

perf: Speed-up resource checking for existing nodes

---

pkg/controllers/state/informer/daemonset.go

Fixes #N/A 
This change ensures that we only re-poll for new DaemonSet pods every 1m so that we don't spend a ton of CPU time re-queuing this controller every time there is _any_ update to the DaemonSet

perf: Poll for DaemonSet resources rather than watching

---

go.mod
kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/controllers/disruption/drift_test.go
pkg/controllers/disruption/helpers.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/nodeclaim/consistency/termination.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/statenode.go
pkg/test/pods.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
pkg/utils/node/node.go
pkg/utils/pdb/pdb.go
pkg/utils/pdb/suite_test.go

fix: don't provision unnecessary capacity for pods which can't move to a new node (#2033)
Fixes #N/A 
Backporting https://github.com/kubernetes-sigs/karpenter/pull/2033
Unit testing only for the backport.

fix: don't provision unnecessary capacity for pods which can't move to a new node (#2033)

---

pkg/utils/nodeclaim/nodeclaim.go

Fixes #N/A 
These handler functions just read data and are extremely tightly scoped. Removing NodeClaim deep-copying from them to prevent a bunch of additional copying being done just for mapping

perf: Don't deepcopy inside of watch handler functions

---

test/pkg/environment/common/environment.go
test/pkg/environment/common/expectations.go
test/suites/integration/nodeclaim_test.go
test/suites/integration/suite_test.go

Fixes #N/A 
- Use a randomized name for NodePool and NodeClass objects

test: Add random name string for NodePool and NodeClass

---

pkg/controllers/disruption/types.go

Fixes #N/A 
cluster.Nodes() already deep copies all the nodes, NewCandidate() does not also need to do so

perf: Only deep copy nodes during GetCandidates once

---

pkg/controllers/provisioning/scheduling/existingnode.go

Fixes #N/A 
.Available allocates a whole new list into which to do the subtraction. Only calling it once saves on performance

perf: Only call .Available() once which prevents duplicate allocs

---

pkg/controllers/disruption/consolidation_test.go
pkg/controllers/disruption/validation_test.go
test/suites/regression/nodeclaim_test.go

Fixes #N/A 
The presubmit test was calling `cluster.Nodes()` which returns nodes based on a map. This adds a sort so the nodes are deterministically selected for churn.
Deflakes registration by adding time since it can take longer than 1 minute to move from TTL to deletion completing:
>          {"level":"DEBUG","time":"2025-05-21T19:04:08.017Z","logger":"controller","caller":"lifecycle/liveness.go:69","message":"terminating due to registration ttl","commit":"91d8ecc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"fighterribbon-23-rfpvpgytno"},"namespace":"","name":"fighterribbon-23-rfpvpgytno","reconcileID":"ea4d5c90-7f46-4f6b-80d6-3e3d38602624","provider-id":"aws:///us-east-2b/i-0349b1aa449d49a2d","ttl …

test: deflake NodeClaim and presubmit tests

---

pkg/cloudprovider/types.go

Fixes #N/A 
Improve `OrderByPrice` performance by not creating new slices of offerings and re-creating requirements sets when checking compatability

perf: Improve OrderByPrice performance

---

pkg/apis/v1/nodeclaim_status.go
pkg/controllers/node/termination/controller.go
pkg/controllers/node/termination/suite_test.go
pkg/controllers/node/termination/terminator/events/events.go
pkg/controllers/node/termination/terminator/suite_test.go
pkg/controllers/node/termination/terminator/terminator.go
pkg/events/reason.go
pkg/utils/node/node.go

Fixes #N/A 
Adds status conditions for node drain and volume detachment to improve observability for the individual termination stages. This is a scoped down version of #1837, which takes these changes along with splitting each termination stage into a separate controller. I will continue to work on that refactor, but I'm decoupling to work on higher priority work.
**Status Conditions:**
|Condition|Unknown|False|True|
|-|-|-|-|
|`Drained`|Karpenter hasn't attempted to drain the Node yet **or** the node is currently draining (marked with reason)|N/A|Karpenter has successfully drained the node and will proceed with the termination flow.|
|`VolumesDetached`|Karpenter hasn't checked for volume attachments yet or there are volume attachments which are currently blocking …

feat: drain and volume detachment status conditions

---

pkg/controllers/state/cluster.go

Fixes #N/A 
Avoid continually deep-copying Nodes and NodeClaims during `Synced` checks

perf: Don't deep-copy nodes and nodeclaims in our synced check

---

hack/install-kwok.sh

Fixes #N/A 
This changes fixes getting the correct directory for the location of the script using a bash one-liner.
`UNINSTALL_KWOK=false ./github/karpenter/hack/install-kwok.sh`

chore: Fix getting current script directory in install-kwok.sh

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go

Fixes #N/A 
At present Pod metrics controller continues to emit the `unstarted_time_metrics` when the pod is completed. This PR adds a fix that will stop emitting the `unstarted_time_metrics` when the pod is completed. 
Added tests.

chore: Update pod metrics when pod is completed

---

pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/test/expectations/expectations.go

Fixes #N/A 
Fixes some incorrect logic that doesn't map nodepools to pods correctly. Added unit test to verify the functionality.
Ran unit test against main:
```
Will run [1m1[0m of [1m99[0m specs
[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m
[38;5;243m------------------------------[0m
[38;5;9m• [FAILED] [4.859 seconds][0m
[0mProvisioning [38;5;9m[1m[It] Should provision nodes for multiple pods[0m
[38;5;243m/Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/suite_test.go:226[0m
[38;5;9m[FAILED] Metric karpenter_pods_scheduling_decision_duration_seconds should have the expected value
Expected
<uint64>: 5
to equal
<uint64>: 100[0m
[38;5;9mIn [1m[It][0m[38;5;9m at: …
```

fix: Correctly build nodepool mapping for complex clusters

---

pkg/controllers/disruption/controller.go
pkg/controllers/state/statenode.go

Fixes #N/A 
Parallelize disruption actions so that things like marking the NodeClaim status condition and tainting nodes can occur in parallel when the action is large

perf: Parallelize disruption execution actions

---

pkg/controllers/nodeclaim/lifecycle/registration_test.go
pkg/utils/nodeclaim/nodeclaim.go

Fixes #N/A 
Don't add the ownerReference from the NodeClaim to the Node if the NodeClaim ownerReference already exists

fix: Fix node owner reference update

---

pkg/controllers/disruption/controller.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/state/statenode.go

Fixes #N/A 
Be more resilient to single node failures during disruption deletion operations. Currently, if we have a single node failure while we are moving through `executeCommand`, it will stop the _whole_ command from executing. This is particularly problematic when you have a large emptiness command that you aren't able to make any progress on. This changes the code so that we can continue to make progress on deletion commands even if all of the nodes don't succeed.
It also adds retries for the apiserver actions to attempt to be more resilient to transient failures.

perf: Be more resilient to deletion failures in disruption controller

---

kwok/cloudprovider/cloudprovider.go
test/pkg/environment/common/expectations.go
test/suites/regression/nodeclaim_test.go

Fixes #N/A 
- Ensure validation policies are applied before NodeClass reconciliation to prevent race conditions
- Implement selective status condition updates instead of overwriting all NodeClass conditions
- `make upstream-e2etestss`

chore: Update NodeClaim E2E test to only replace one status condition

---

pkg/controllers/disruption/orchestration/queue.go

Fixes #N/A 
Only log `command succeeded` when the command actually succeeded in the orchestration queue

chore: Only log that the command succeeded when it actually did

---

README.md

Fixes #N/A
Description
We’ve just released the Bizfly Cloud provider: https://github.com/bizflycloud/karpenter-provider-bizflycloud/releases 
We only do internal testing but show very promising result, we will continuosly maintain and improve in the future
Our next step is to improve more feature for this solution. We’re confident we can improve upon it and deliver the best possible experience to the community users.
This marks a significant milestone for the Karpenter community in Vietnam Cloud providers - once Bizfly Cloud is supported
How was this change tested?
none

docs: Add Bizfly Cloud provider

---

pkg/controllers/disruption/drift_test.go
pkg/controllers/disruption/orchestration/queue.go
pkg/controllers/disruption/orchestration/suite_test.go
pkg/controllers/disruption/suite_test.go
pkg/controllers/state/cluster.go

Fixes #N/A 
Rather than using a time-based mechanism to ensure that we bail out of `waitOrTerminate` when we get an ICE error, this change updates it to use cluster state as a consistent in-memory store. Cluster state is updated immediately when the NodeClaims are created. The NodeClaim name is only removed from the cluster state if the NodeClaim informer sees the object deleted.

chore: Use cluster state to check replacement NodeClaim existence

---

kwok/charts/templates/clusterrole.yaml

This commit adds additional rbac rules to allow the kwok-provider when deployed with Helm to patch `nodeclaims` and `nodepools` finalizers. This is needed for kwok-provider to work on clusters that have the `OwnerReferencesPermissionEnforcement` admission webhook enabled (e.g., OpenShift).
Fixes #2323
Installed a kind cluster with this config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
kubeadmConfigPatches:
- |
kind: ClusterConfiguration
apiServer:
extraArgs:
enable-admission-plugins: OwnerReferencesPermissionEnforcement,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,DefaultIngressClass,DefaultStorageClass,DefaultTolerationSeconds,LimitRanger,MutatingAdmissionWebhook,NamespaceLi …
```

fix: add helm rbac for kwok-provider to update finalizers

---

go.mod
go.sum
pkg/controllers/controllers.go

Fixes #N/A 
The `operator_nodeclaim_status_condition_transition_seconds_bucket` and `operator_nodeclaim_termination_duration_seconds_bucket ` metrics emitted by Karpenter can be used to time the life-cycling of NodeClaim's and identifying potential bottlenecks.  Unfortunately they are configured with a default set of buckets that cap out at 5seconds.  This largely makes the metrics unusable.
https://github.com/awslabs/operatorpkg/pull/164 adds the ability to configure these buckets.  
This PR uses that configuration with 15 buckets increasing exponentially from 0.5 to 8192 (0.5, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192).  Open to suggestions on a more suitable spread.
`make test`
By submitting this pull request, I …

feat: configure CRD status operator with larger histogram buckets

---

pkg/controllers/disruption/queue.go
pkg/controllers/state/statenode.go

Fixes #N/A 
This change ensures that we re-grab the object when doing retries in-code rather than continually trying to patch with an old version of the object

fix: Fix re-retrieving object on retry

---

pkg/controllers/provisioning/scheduling/reservationmanager.go
pkg/controllers/provisioning/scheduling/reservationmanager_test.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #2318
Add a short circuit to the `Reserve` function that will prevent the same hostname from taking multiple capacity
Added a new test package for the reservation manager and a test specifically for the functionality.
```
Running Suite: Scheduling - /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling
==============================================================================================================================
Random Seed: 1751928679
Will run 27 of 318 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS …
```

fix: no longer allow the same hostname to take multiple capacity

---

test/suites/regression/nodeclaim_test.go

Fixes #N/A  Fixes error encountered in https://github.com/aws/karpenter-provider-aws/pull/8250/#issuecomment-3059863501.
**Description** `kubernetes-sigs/karpenter` tests running in `aws/karpenter-provider-aws` fail due to `{"level":"ERROR","time":"2025-07-11T00:38:25.533Z","logger":"controller","caller":"controller/controller.go:353","message":"Reconciler error","commit":"5bf129e-dirty","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"swisherdestiny-3-y3pfejlvlb"},"namespace":"","name":"swisherdestiny-3-y3pfejlvlb","reconcileID":"67645973-bcb1-443b-8de8-ead0fdffb70c","provider-id":"test-provider-id","error":"getting instance ID, provider id does not match known format (provider-id=test-provider-id)"}`. This change fixes …

fix: update provider ID to ensure that Cloud Provider tests pass

---

pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/options.go

Fixes #N/A 
Promotes the `ReservedCapacity` feature to beta and adds additional testing around default handling when a subset of feature gates are specified.

chore: promote ReservedCapacity feature gate to beta

---

test/suites/regression/expiration_test.go

Fixes #N/A 
`should expire the node after the expiration is reached` has been failing fairly frequently after https://github.com/kubernetes-sigs/karpenter/pull/2324 since the node and nodeclaim objects are deleted so quickly that the current validation doesn't work. This commit removes that validation since the eventual check of the node and nodeclaim being deleted should be good enough. I looked around to see if we can use any event to validate the expiration more precisely but couldn't find anything else.
Ran the test and it succeeds locally now. It would fail before this change.

fix: flakiness in expiration tests

---

pkg/controllers/provisioning/scheduling/reservationmanager.go
pkg/controllers/provisioning/scheduling/reservationmanager_test.go
pkg/controllers/provisioning/scheduling/suite_test.go

Fixes #N/A 
Backporting https://github.com/kubernetes-sigs/karpenter/pull/2356 to 1.5

fix: no longer allow the same hostname to take multiple capacity (#2356)

---

pkg/controllers/nodeclaim/lifecycle/liveness.go
pkg/controllers/nodeclaim/lifecycle/liveness_test.go
pkg/test/expectations/expectations.go

Fixes #N/A 
If Karpenter encounters issues launching instances then we should retry for a shorter amount of time than the full registration timeout. This unblocks provisioning decisions for pods that may be stuck waiting for compute that will not come up due to launch failures. This also allows Karpenter to make new decisions about what compute should be provisioned.
This PR changes an alpha metric for nodeclaim disruptions. The metric reason `liveness` will change to `registration_timeout`.
Unit tests.

feat: (BREAKING) addition of launch timeout for nodeclaim lifecycle

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/suite_test.go
pkg/scheduling/taints.go
pkg/test/expectations/expectations.go

Fixes issue in aws-provider - https://github.com/aws/karpenter-provider-aws/issues/8066
When using Kyverno to apply tolerations to the pod, Karpenter was creating two nodeClaims because the node comes up with this taint that gets removed later - 
```
- key: "node.kubernetes.io/not-ready"
operator: "Exists"
effect: "NoExecute"
```
This PR will consider this taint as ephemeral if the node isn't initialized which will prevent karpenter from creating two nodeclaims for the same pod.
Added tests. Tested this on my dev cluster.

chore: Consider node.kubernetes.io/not-ready:NoExecute as ephemeral

---

pkg/controllers/node/termination/terminator/eviction.go
pkg/controllers/node/termination/terminator/suite_test.go

Fixes #N/A 
Updates the requeue behavior in the eviction controller to use `Requeue: true` rather than `RequeueAfter` when there are blocking PDBs. Previously, this resulted in us requeuing once every 100ms per pod bypassing any rate limiting on the work queue. With this change, we will enter exponential backoff (max of 10s) and still respect the overall controller rate limit.

fix: rate limit eviction when PDBs are blocking

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/scheduling/volumetopology.go

Fixes #N/A 
This change allows Karpenter to ignore pods that use unsupported provisioner within their storageClass. Cloudproviders can use this to ignore pods with certain provisioners.
Tested on my dev cluster with aws-provider by tweaking it to ignore a fakeProvisioner and ensuring that we don't create a node for it. Also added unit test for it.

chore: ignore pods that use unsupported provisioner in the storageClass

---

pkg/controllers/metrics/pod/controller.go
pkg/controllers/metrics/pod/suite_test.go

Fixes #2403 
`karpenter_pods_startup_duration_seconds` is taking negative values for terminal pods because pod status condition Ready is set to False for terminal pods. 
Added unit tests. Deployed to my dev cluster.

fix: pod metrics when pod is terminal

---

designs/static-capacity.md

Fixes 
* Static Capacity support for Karpenter - [#749]
This RFC plans to address static provisioning feature request by extending existing Nodepool to support replicas.

docs: static capacity RFC

---

.github/workflows/run-bench-test.yaml

Fixes #N/A 
This PR pins all of our third-party actions to a full-length SHA to ensure they are not vulnerable to a supply-chain attack. This is the best practice for third-party GHA as described here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
This work was originally done in other actions in #801 and is being added here for the new run-bench-test workflow

chore: Pin GH action SHAs for run-bench-test

---

.github/workflows/kind-e2e.yaml
.github/workflows/presubmit.yaml
hack/toolchain.sh
kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
kwok/charts/crds/karpenter.sh_nodeclaims.yaml
kwok/charts/crds/karpenter.sh_nodeoverlays.yaml
kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodeoverlays.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/test/environment.go
pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml

Fixes #N/A 
This ensures that we properly test K8s versions 1.33 and 1.34 in testing our upstream changes since these versions weren't added since the recent upstream release

ci: Include K8s version 1.33 and 1.34 in testing

---

pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go

Fixes #N/A 
This change increases the instance types that are set in a NodeClaim from 60 to 600. The number 600 was chosen to be sufficiently high but still putting an upper-bound on the number of instance types set in the NodeClaim. 
This should not increase scheduling latency since truncation occurs after scheduling/bin-packing simulations. 
The AWS Cloud Provider is still truncating to 60 instance types, set [here](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/instance/instance.go#L62).
The Azure Cloud Provider sorts the NodeClaim's instance types and only passes 1 to the provisioning API [here](https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/instance/instance.go#L626).
Manual testing:
1. …

chore: increase MaxInstanceTypes to give cloud-providers more control over instance type truncation

---

.github/workflows/kind-e2e.yaml
.github/workflows/presubmit.yaml
hack/toolchain.sh
pkg/test/environment.go

Fixes #N/A 
Reverts the addition of the k8s 1.34 tests. A change was made to how `matchLabelKeys` for TSC is injected by the API server which causes this test suite to fail. A fix for the issue can be tracked in https://github.com/kubernetes-sigs/karpenter/pull/2471.

ci: revert k8s 1.34 addition

---

pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/operator/options/options.go
pkg/operator/options/suite_test.go
pkg/test/options.go
pkg/test/pods.go
pkg/utils/pod/scheduling.go

Currently Karpenter creates nodes that can't satisfy DRA requirements and keep trying to schedule pod to the node.
Karpenter should recognize that pods are DRA enabled and not try to create nodes to fulfill them.
Unit tests and manually tested pod with resourceClaims in spec and scheduler correctly logs skipping message.

fix: Don't schedule a pod with DRA requirements

---

pkg/controllers/provisioning/scheduling/topologygroup.go

Fixes #N/A 
When a topology spread constraint defines duplicate expressions in it's label selector, it can result in a hash collision with other `TopologyGroups` even if they have a different expression. This is a manifestation of https://github.com/mitchellh/hashstructure/issues/36. 
This issue surfaced itself when we enabled k8s 1.34 testing. This is due to https://github.com/kubernetes/kubernetes/pull/129874, which changed the behavior of `matchLabelKeys` for TSC to match that of pod affinity. As a result, both Karpenter and the API server are injecting expressions for `MatchLabelKeys`. Consider the following example from our tests:
```yaml
kind: Pod
apiVersion: v1
metadata:
labels:
test-label: "value-a"
spec:
topologySpreadConstraints:
- topologyKey: …
```

fix: avoid hash collisions with duplicate match expressions

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/scheduling/volumetopology.go
pkg/scheduling/volumeusage.go

Fixes #N/A 
#2400 originally introduced a change that ensured that Karpenter didn't try to launch nodes for provisioners that it knew that it doesn't support through the ValidatePersistentVolumeClaims function. Unfortunately, this change did not handle volumes that were already bound, as well as not handling PVs that were migrated to CSI.

fix: Validate unsupported provisioners on bound PVs

---

pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/suite_test.go
pkg/utils/daemonset/daemonset.go
pkg/utils/daemonset/suite_test.go

Fixes #N/A 
Context can be found in this [comment](https://github.com/kubernetes-sigs/karpenter/pull/2383#issuecomment-3304327210).
> > Personally, I think Karpenter doesn't need to implement this logic explicitly, but WDYT?
> 
> So the issue is that the defaulting applies to the pods created for the daemonset, but not for the daemonset itself. Karpenter reads the daemonset spec to compute the "daemonset overhead" for a NodePool. We do this by creating fake daemonset pods based on the specs ([ref](https://github.com/kubernetes-sigs/karpenter/blob/6825a12e67c9c951a2b103120f164ce6c0f73281/pkg/controllers/provisioning/provisioner.go#L465-L490)) and then calling RequestsForPods against those pods ([ref](https://github.com/kubernetes-sigs/karpenter/blob/6825a12e67c9c951a2b103120 …

fix: merge limits into requests when constructing ds pods

---

pkg/operator/options/options.go
pkg/operator/options/suite_test.go

Fixes https://github.com/aws/karpenter-provider-aws/issues/8495
This change eases configuration by allowing helm charts to specify this env var as a function of the container's resource requests. When a container doesn't specify resource requests, or specifies a value of 0, we'll fall back to the default (1000).

fix: default CPU_REQUESTS when non-positive value is provided

---

pkg/controllers/state/cluster.go
pkg/controllers/static/deprovisioning/controller.go
pkg/controllers/static/provisioning/controller.go
pkg/controllers/static/provisioning/suite_test.go

Fixes over provisioning of NodeClaims during controller crashes.
Since we use local Cluster NodePoolState to account for limits, if during provisioning controller dies then the next leader would need to wait until cluster state is populated to avoid over-provisioning of resources. 
We dont need to sync on cluster state for deprovisioning as we gradually populate NodePoolState and look at the replicas to delete NC when over-provisioned.
UT and tested by rolling and restarting karpenter to check if we overprovision resources.
Even tested deprovisioning case.

fix: over provisioning static nodeclaims during controller crashes

---

pkg/controllers/nodeclaim/consistency/controller.go

Fixes #N/A 
Demotes errors from the consistency controller to info logs. This avoids confusion around the impact of the consistency check. Nodes that fail consistency checks are still usable and Karpenter won't deprovision them or treat them as unhealthy. It just informs the end user that Karpenter's internal view of resources available for an instance type aren't consistent with reality.

chore: drop consistency error to info log

---

kwok/charts/crds/karpenter.sh_nodepools.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1/nodepool.go

fix: nodepool crd definition should explicitly say replicas field as alpha
Fixes #N/A 
make presubmit

fix: nodepool crd definition should explicitly say replicas field as alpha

---

pkg/controllers/controllers.go
pkg/controllers/nodeclaim/garbagecollection/suite_test.go
pkg/controllers/nodeclaim/lifecycle/controller.go
pkg/controllers/nodeclaim/lifecycle/liveness.go
pkg/controllers/nodeclaim/lifecycle/liveness_test.go
pkg/controllers/nodeclaim/lifecycle/registration.go
pkg/controllers/nodeclaim/lifecycle/registration_test.go
pkg/controllers/nodeclaim/lifecycle/suite_test.go
pkg/controllers/nodepool/registrationhealth/controller.go
pkg/controllers/nodepool/registrationhealth/suite_test.go
pkg/state/nodepoolhealth/suite_test.go
pkg/state/nodepoolhealth/tracker.go
pkg/test/nodepool.go
pkg/utils/ringbuffer/buffer.go
pkg/utils/ringbuffer/suite_test.go

Fixes #N/A 
This change is intended to allow `NodeRegistrationHealthy` SC on the nodePool to be updated to `False` even if it was previously set to `True` depending on the values stored in the boolean `NodePoolNodeRegistrationBuffer`. In this implementation, the size of this buffer is `4` and if there are >=2 registration failures, we update the `NodeRegistrationHealthy` SC to `False` even if it was `True` previously. This wasn't possible in the existing implementation because once the SC was set to `True`, it could only be set to `Unknown` on updates to nodePool/nodeClass. This change allows it to go back to `False`.
Deployed to my dev cluster and tested. Also added unit tests.
By submitting this pull request, I confirm that my contribution …

chore: Update NodeRegistrationHealthy SC to use a buffer mechanism
