.github/workflows/presubmit.yaml, pkg/apis/provisioning/v1alpha5/suite_test.go
=> chore: remove accidental dependency on aws-go-sdk

Makefile, go.mod, go.sum
=> Fix: knative dep causing crash loops

pkg/apis/provisioning/v1alpha5/labels.go
=> chore: promote spot/ondemand to become a neutral concept

go.mod, go.sum, pkg/webhooks/webhooks.go
=> chore: migrate webhooks

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go, pkg/controllers/termination/suite_test.go, pkg/test/expectations/expectations.go, pkg/test/nodes.go, pkg/test/pods.go
- Add testing configuration and expectations that can be leveraged by Node Termination Handler
=> test: Add additional expectations and configuration to testing

go.mod, go.sum, pkg/webhooks/webhooks.go
Fixes the remove of `webhooks` package in #18 
=> chore: Add `webhooks` package back

go.mod, go.sum, pkg/webhooks/webhooks.go
=> Revert "bug: Fix Broken Knative Webhook"

pkg/test/metadata.go
=> test: add a discovery label to all test objects for cleanup

pkg/apis/config/registration.go, pkg/apis/config/settings/settings.go, pkg/controllers/provisioning/batcher.go, pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go, pkg/operator/controller/suite_test.go, pkg/operator/settingsstore/fake/settings.go, pkg/operator/settingsstore/settingsstore.go, pkg/operator/settingsstore/suite_test.go, pkg/test/settings.go
Adds a default to any `ConfigMaps` watched by the `settingsstore.Store`
=> fix: Add defaults to Settings

Makefile, pkg/apis/apis.go, pkg/apis/provisioning/v1alpha5/provisioner_defaults.go, pkg/apis/provisioning/v1alpha5/provisioner_validation.go, pkg/apis/provisioning/v1alpha5/register.go, pkg/test/provisioner.go, pkg/webhooks/webhooks.go
- `make apply && TEST_FILTER=TestIntegration make e2etests`
=> chore: renamed webhooks to be specific to api group

pkg/controllers/counter/controller.go, pkg/controllers/metrics/pod/controller.go, pkg/controllers/metrics/provisioner/controller.go, pkg/controllers/node/controller.go, pkg/controllers/provisioning/controller.go, pkg/controllers/termination/terminate.go
=> chore: use client.IgnoreNotFound

pkg/controllers/deprovisioning/emptiness.go
N/A
- Don't log when the node does not have an emptiness annotation
```
...
karpenter-547b9b8478-tmqk2 controller 2022-11-04T14:26:12.217Z	DEBUG	controller.nodetemplate	Reconciled the SQS interruption queue	{"commit": "33fc137-dirty", "queueName": "wagnerbm-karpenter-dev-us-east-2"}
karpenter-547b9b8478-tmqk2 controller 2022-11-04T14:26:12.353Z	DEBUG	controller.nodetemplate	Reconciled the EventBridge interruption rules	{"commit": "33fc137-dirty"}
karpenter-547b9b8478-tmqk2 controller 2022-11-04T14:26:12.353Z	INFO	controller.nodetemplate	Ensured existence of interruption-handling infrastructure	{"commit": "33fc137-dirty"}
karpenter-547b9b8478-tmqk2 controller 2022-11-04T14:27:55.572Z	DEBUG	controller.deprovisioning	Unable to parse …
```
=> chore: do not log when node does not have emptiness annotation

.github/pull-request-template.md
=> chore: add PR template

Makefile
=> test: trigger CI based off of github env var CI

pkg/scheduling/requirements.go, pkg/scheduling/requirements_test.go
Detect some typos and try to clarify the error message that occurs when a pod requires a label that we don't know about.
Unit testing & deployed to EKS.
Samples of the improved error messages are in the unit test.
=> chore: add better error messages

pkg/operator/operator.go, pkg/operator/options/options.go
Fixes # 
- Disables the webhook with `DISABLE_WEBHOOK`
`make run`
=> chore: Allow disabling webhook for local debugging

pkg/test/randomdelay.go
=> fix: update randomdelay to match new version of Ginkgo

pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Fixes # 
- Remove deadcode from scheduling profiling
=> chore: Remove deadcode from scheduling profiling

pkg/operator/operator.go
=> fix: Reduced webhook grace period for faster restarts

pkg/controllers/termination/terminate.go
Fixes # 
- Fix logging cordoning and deleting multiple times on termination
=> fix: Fix logging cordoning and deleting multiple times on termination

pkg/controllers/deprovisioning/singlenodeconsolidation.go, pkg/controllers/provisioning/provisioner.go
=> chore: remove unused code

pkg/controllers/provisioning/scheduling/suite_test.go, pkg/controllers/provisioning/volumetopology.go
Fixes https://github.com/aws/karpenter/issues/2651
Unit testing & deployed to EKS.
=> fix: ignore pods with ephemeral volumes using an invalid storage class name

pkg/controllers/provisioning/scheduling/machine.go, pkg/controllers/provisioning/scheduling/machinetemplate.go, pkg/controllers/provisioning/suite_test.go
Fixes # 
- Add resource requests to the Machine spec when creating the Machine
=> chore: Add Machine `.spec.resources.requests`

pkg/controllers/deprovisioning/consolidation.go, pkg/controllers/deprovisioning/controller.go, pkg/controllers/deprovisioning/drift.go, pkg/controllers/deprovisioning/expiration.go, pkg/controllers/deprovisioning/helpers.go, pkg/controllers/deprovisioning/multinodeconsolidation.go, pkg/controllers/deprovisioning/types.go, pkg/controllers/deprovisioning/validation.go, pkg/controllers/provisioning/provisioner.go, pkg/controllers/provisioning/scheduling/existingnode.go, pkg/controllers/provisioning/scheduling/node.go, pkg/controllers/provisioning/scheduling/scheduler.go, pkg/controllers/provisioning/scheduling/suite_test.go, pkg/controllers/provisioning/scheduling/topologynodefilter.go
=> chore: Reason in scheduling in terms of nodes

pkg/controllers/deprovisioning/consolidation.go, pkg/controllers/deprovisioning/controller.go, pkg/controllers/deprovisioning/drift.go, pkg/controllers/deprovisioning/emptiness.go, pkg/controllers/deprovisioning/emptynodeconsolidation.go, pkg/controllers/deprovisioning/events/events.go, pkg/controllers/deprovisioning/expiration.go, pkg/controllers/deprovisioning/helpers.go, pkg/controllers/deprovisioning/multinodeconsolidation.go, pkg/controllers/deprovisioning/reporter.go, pkg/controllers/deprovisioning/singlenodeconsolidation.go, pkg/controllers/provisioning/provisioner.go, pkg/utils/pretty/changemonitor.go
Adds more visibility regarding consolidation decisions/
Deployed to EKS.
=> feat: add more deprovisioning logs

pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/types.go
Fixes # 
IsNodeDrifted will be use for automatic upgrades. 
=> feat: Added IsMachineDrifted into CP interface

pkg/apis/v1alpha1/machine.go, pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/metrics/cloudprovider.go, pkg/cloudprovider/types.go, pkg/controllers/termination/terminate.go
Fixes # 
- Reasons in terms of `v1alpha1.Machine` for the termination loop
=> chore: Create a pseudo machine for node termination loop

pkg/apis/v1alpha1/machine.go, pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/metrics/cloudprovider.go, pkg/cloudprovider/types.go, pkg/controllers/termination/terminate.go
This reverts commit 5d50fbf4f4449f03cb4c6cf27bd2e18c27dd34c7.
Fixes # 
=> Revert "Create a pseudo machine for node termination loop (#112)"

charts/karpenter-core-crd/Chart.yaml, charts/karpenter-core/Chart.yaml
Fixes # 
Bump version to v0.0.2 since v0.0.1 already exists.
=> chore: bump chart version to v0.0.2

pkg/apis/apis.go, pkg/apis/v1alpha1/machine_defaults.go, pkg/apis/v1alpha1/machine_validation.go, pkg/cloudprovider/types.go
Fixes # 
- Registers the `Machine` CR with the controller-runtime client scheme
=> chore: Register the Machine CR with the scheme

pkg/apis/v1alpha1/machine.go
Fixes # 
- adds in a function to convert a node to a Machine
=> chore: add in nodeToMachine function

charts/karpenter-core-crd/templates/karpenter.sh_machines.yaml, pkg/apis/v1alpha1/machine.go
Fixes # 
Excludes machine crd from helm package
=> fix: Exclude machine crd

pkg/controllers/provisioning/provisioner.go
=> chore: reduce log spam

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/docs-request.yaml, .github/ISSUE_TEMPLATE/request.yaml
Fixes # 
Copies over the same github issue templates used in github.com/aws/karpenter.
=> chore: Add github issue templates

pkg/controllers/node/controller.go, pkg/controllers/termination/controller.go
Fixes # 
- Revert moving some code logic into `WithEventFilter` that is causing consistency issues with events coming in prior to the object being modified.
=> fix: Remove event filters and move logic back into reconcile

pkg/controllers/node/controller.go, pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go
Fixes # 
- We can simplify the eviction observer mechanism by doing a short requeue on the node controller to check for emptiness
=> chore: Short requeue to check for emptiness rather than using an observer

pkg/cloudprovider/fake/cloudprovider.go, pkg/controllers/node/controller.go, pkg/controllers/node/drift.go, pkg/controllers/node/suite_test.go
Fixes # 
- make apply && change awsnodetemplate and see drift with changes enabled
=> chore: move drift controller to karpenter-core

pkg/controllers/provisioning/provisioner.go, pkg/controllers/provisioning/scheduling/topology_test.go
Fixes: https://github.com/aws/karpenter/issues/3239
We were incorrectly expanding our universe of topology domains based on instance type requirements.  These needs to be intersected  with the provisioner requirements to ensure that restricting domains by provisioner works correctly.
Unit testing and deployed to EKS.
=> fix: restrict topology domain universe by provisioner

.github/dependabot.yml
Fixes # 
- Add dependabot to karpenter-core
=> chore: Add dependabot to karpenter-core

pkg/metrics/metrics.go
Fixes # 
- Add machine created/terminated counters (`karpenter_machines_created` and `karpenter_machines_terminated`)
=> chore: Add machine created/terminated counters

charts/karpenter-core-crd/templates/karpenter.sh_provisioners.yaml
Fixes # 
- Fix symlink in `crds`
=> chore: Fix symlink in `crds`

pkg/apis/crds/karpenter.sh_machines.yaml, pkg/apis/v1alpha5/machine.go
Fixes # 
Add JSON printer column for `topology.kubernetes.io/zone`
Applying the CRD manually to cluster
=> chore: Add JSON printer column for `topology.kubernetes.io/zone`

.github/workflows/stale.yaml
Fixes # 
Add stale bot to karpenter-core
=> chore: Add stale bot to karpenter-core

pkg/controllers/deprovisioning/suite_test.go, pkg/test/eventrecorder.go
Fixes # 
Fixes a DATA RACE in deprovisioning testing that was being caused by resetting the events in the fake EventRecorder to an empty buffer. This change now uses Karpenter's EventRecorder for event tracking.
`FOCUS=Deprovisioning make deflake`
=> test: Fix DATA RACE in deprovisioning testing

charts/karpenter-core-crd/templates/karpenter.sh_machines.yaml
Fixes # 
Symlink path should have an additional `../` in it to be valid
=> chore: Fix bad symlink path for release

pkg/controllers/deprovisioning/consolidation.go, pkg/controllers/deprovisioning/controller.go, pkg/controllers/deprovisioning/drift.go, pkg/controllers/deprovisioning/emptiness.go, pkg/controllers/deprovisioning/emptymachineconsolidation.go, pkg/controllers/deprovisioning/expiration.go, pkg/controllers/deprovisioning/metrics.go, pkg/controllers/deprovisioning/multimachineconsolidation.go, pkg/controllers/deprovisioning/singlemachineconsolidation.go, pkg/controllers/provisioning/scheduling/machine.go
Fixes # 
- Cherry-picks scheduling logging (https://github.com/aws/karpenter-core/pull/317)
- Cherry-picks deprovisioning metrics (https://github.com/aws/karpenter-core/pull/331)
=> Release v0.27.4

pkg/controllers/provisioning/scheduling/machine.go
Fixes # 
Its not as helpful to know just the pod resource
request when you're trying to diagnose why a node
won't launch. You need to know the daemonset + pod resource requests that Karpenter is using in its
calculation.
Deploying on an EKS cluster with a pod that had a large request size.
=> fix: log the cumulative resource request that failed

.github/workflows/presubmit.yaml
=> remove k8s 1.21 as it went end of support in Feb 2023

pkg/controllers/node/drift.go
Fixes # 
- Allow more visibility to client to aware of errors are being produced
- Manually tested
=> chore: Ignore Machine Not Found Error for Drift

.github/workflows/stale.yaml
Fixes #N/A 
- Update stalebot to close stale PRs
=> chore: Update stalebot to close stale PRs

pkg/operator/operator.go
Fixes #N/A 
- We are seeing issues were knative readiness and liveness probs are require to use port 8080. If port 8080 is being utilized we see that user will have issues with karpenter start up. https://github.com/aws/karpenter/issues/4145
- Manually tested 
=> fix: Disable knative liveness and readiness probes

pkg/controllers/controllers.go, pkg/controllers/machine/garbagecollection/suite_test.go, pkg/controllers/machine/lifecycle/controller.go, pkg/controllers/machine/lifecycle/launch.go, pkg/controllers/machine/lifecycle/suite_test.go, pkg/controllers/machine/termination/suite_test.go
We need to have improved visibility of ICE events when karpenter encounters them.
=> feat: create kubernetes events in case of insufficient capacity errors

Makefile, hack/toolchain.sh
Fixes #N/A 
- Fix broken bool check in `make verify`
`make verify`
=> ci: Fix bool check in "make verify" and update toolchain

go.mod
Fixes #N/A 
- Add retracted to `go.mod` for published test version
- `v0.100.101-test` was erroneously published so we should retract it within the `go.mod`
=> ci: Add retracted version for published test version

pkg/controllers/provisioning/provisioner.go
Fixes #N/A 
Currently, the provisioner polling singleton controller employs the default rate limiter from [NewSingletonManagedBy](). This means that when the provisioner controller experiences an error, it will backoff that error in an exponential manner. If we get especially unlucky or the batching window is sufficiently large, it may not forget the backoff value, causing the backoff to grow larger and larger until it gets to max backoff (~16 minutes).
We should backoff in the case that we are getting server-side errors, but in a scenario where there are no provisioners we should not be backing off
`make apply` manually tested on a cluster, validating that other controllers have the correct rate limiter while the provisioner requeues at a …
=> fix: Warn instead of Error on 'no provisioners found'

pkg/controllers/deprovisioning/controller.go
Fixes #N/A 
`retry.Do()` can hang the controller during termination when the controller is waiting for termination or replacement of a node. The default context for `retry.Do()` is the background context which will not get cancelled when the controller receives the SIGTERM to start shutting down. This causes the controller to hang until its graceful termination.
This change injects the controller context into the retry loops so that the retry loop will get cancelled as soon as the SIGTERM is received.
- Manual Validation with short `ttlSecondsUntilExpired`
```console
controllerGroup":"karpenter.sh","controllerKind":"Machine"}
{"severity":"INFO","timestamp":"2023-07-30T23:58:55.192562-07:00","logger":"controller","caller":"manager/runnable_gro …
```
=> fix: Prevent `retry.Do()` from hanging controller on termination

pkg/test/metadata.go
Fixes #N/A 
- Needed a new label to identify testing resource with their test clusters.
- N/A
=> chore: Discovery cluster test label

pkg/controllers/provisioning/scheduling/existingnode.go, pkg/controllers/provisioning/scheduling/machine.go, pkg/controllers/provisioning/scheduling/topology_test.go, pkg/scheduling/requirements.go
Fixes #N/A 
We were treating preferred node affinities as required for topology spread purposes. This would cause us to incorrectly restrict the pod's domains to only ones that were acceptable per the preference.  In some cases, this can lead to pods remaining pending as we assume a pod will schedule to an existing node, but it won't due to a required topology spread and our incorrect restriction.
Unit test
=> fix: resolve issue interpreting preferred node affinities

pkg/controllers/machine/disruption/drift.go, pkg/controllers/machine/disruption/types.go
Fixes #N/A 
- Remove NotDrifted drift disruption type
=> chore: Remove not drifted for disruption type

pkg/controllers/machine/disruption/drift.go, pkg/controllers/machine/disruption/types.go
Fixes #N/A 
- Change static drift to provisioner static drift
- `make test`
=> chore: change StaticDrift reason to ProvisionerStaticDrift

pkg/operator/operator.go
Fixes #N/A 
Improve readiness checks to include cache hydration. Currently, readiness is blocked on webhooks, but which can become ready before the manager, giving us a false readiness signal.
=> feat: Block readiness until caches are synced

pkg/controllers/deprovisioning/pdblimits.go, pkg/controllers/deprovisioning/suite_test.go
Fixes https://github.com/aws/karpenter-core/issues/454
If a PDB is configured with an unhealthyPodEvictionPolicy of AlwaysAllow, then unhealthy pods can be evicted.  We will no longer allow those pods to block consolidation.
=> fix: support pdb policies

pkg/controllers/machine/disruption/drift.go, pkg/controllers/machine/disruption/drift_test.go
Fixes #N/A 
We checked cloud provider drift before provisioner neutral drift, resulting in always making an cloudprovider.IsMachineDrifted() and subequent API calls for each reconciliation loop. We shouldn't need to make those calls if the Provisioner is drifted. 
=> fix: reorder drift checks to save on computation

pkg/controllers/machine/disruption/drift.go, pkg/controllers/machine/disruption/drift_test.go
Fixes #N/A 
- Updates drift reason to reflect changes with our docs and streamline drift reason
- Related to https://github.com/aws/karpenter/pull/4436
- N/A
=> chore: Update drift reason

pkg/controllers/deprovisioning/suite_test.go
Fixes #N/A 
- Deflake consolidation timeout testing by not triggering the verify action until after the consolidation timeouts have been hit
`FOCUS="Consolidation Timeout" make deflake`
=> test: Deflake consolidation timeout testing

pkg/operator/operator.go
Fixes #N/A 
- Scooping leases to Kube-node-leases to limit karpenter permission on leases
- https://github.com/aws/karpenter/pull/4453
=> chore: Scope Lease to namespace `kube-node-lease`

pkg/controllers/counter/controller.go
Fixes #N/A 
Previously, we were not reacting to `Machine` updates when updating the Provisioner resources status, which meant that we would wait until `Nodes` were created in order to update the status. This PR adds a Watch on `Machine` to enqueue for a Provisioner update any time there is an update to the `Machine`.
`make apply`
=> Requeue on `Machine` status updates for Counter Controller

pkg/controllers/metrics/node/suite_test.go, pkg/controllers/metrics/nodepool/controller.go, pkg/controllers/metrics/nodepool/suite_test.go, pkg/controllers/metrics/pod/suite_test.go
Fixes #N/A 
This PR adds metrics generation for the `v1beta1/NodePool` controller and preps for the v1beta1 launch
=> chore: Add `v1beta1/NodePool` metrics controller

pkg/controllers/machine/disruption/drift.go
Fixes #N/A 
Fix hash annotation key resolution for `v1beta1/NodeClaim` so that the correct annotation resolves based on the resolved annotation that is used by the `NodeClaim`
=> chore: Fix hash annotation key resolution for `v1beta1/NodeClaim`

pkg/controllers/deprovisioning/metrics.go
Fixes #N/A 
Register the metric so that it shows up .
=> fix: register timeout metrics

pkg/controllers/termination/terminator/eviction.go
Fixes https://github.com/aws/karpenter/issues/2811
This PR bumps the `policy/v1beta1` Eviction request that is generated as part of the termination controller to `policy/v1`. `policy/v1` [became available in 1.22+](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/#calling-the-eviction-api) which is beyond the supportability window for upstream kubernetes.
`make apply`
=> chore: Bump eviction api to policy/v1

pkg/controllers/nodepool/hash/nodepool_test.go, pkg/controllers/nodepool/hash/provisioner_test.go, pkg/controllers/nodepool/hash/suite_test.go
Fixes #N/A 
This PR adds `v1beta1` testing for the hash controller for the `NodePool` resource
=> test: Add testing for `v1beta1` hash controller

pkg/operator/operator.go
This reverts commit f17d213c5f708b1e0abc7f71f2b7c577151c6c94.
Fixes #N/A 
Reverting this as this change was made for another change that isn't needed anymore.
=> chore: Revert "feat: index default namespace endpoints for discovery (#512)"

pkg/controllers/deprovisioning/drift_test.go, pkg/controllers/deprovisioning/emptiness_test.go, pkg/controllers/deprovisioning/expiration_test.go, pkg/controllers/deprovisioning/suite_test.go, pkg/controllers/nodepool/counter/nodepool_test.go, pkg/controllers/nodepool/counter/provisioner_test.go, pkg/controllers/nodepool/counter/suite_test.go, pkg/test/expectations/expectations.go
Fixes #489 
Adds in suite tests for the counter controller.
=> test: add provisioner and nodeclaim counter suite tests

pkg/controllers/provisioning/provisioner.go
Part of fixing https://github.com/aws/karpenter/issues/4698
This allows cloud providers to return errors for GetInstanceTypes and not block all provisioning.
New error message:
```
karpenter-d7887b4d7-wx64q controller 2023-09-28T13:04:14.064Z	ERROR	controller.provisioner	skipping, unable to resolve instance types, resolving node class, resolving node template, getting providerRef, AWSNodeTemplate.karpenter.k8s.aws "defaultFake" not found	{"commit": "ff540d0", "provisioner": "default"}
karpenter-d7887b4d7-wx64q controller 2023-09-28T13:04:14.066Z	ERROR	controller.provisioner	Could not schedule pod, all available instance types exceed limits for provisioner: "default"	{"commit": "ff540d0", "pod": "default/inflate-54b8bcf56d-fq8kk"}
``` …
=> fix: try other provisioners if one fails

pkg/controllers/provisioning/scheduling/scheduler.go
Fixes #N/A 
Record the scheduling duration in the log to make it easier to debug situations in which scheduling is taking too long leading to slower node launches. Ran into situations where users do have logs for the timer period in question, but don't have metrics.
=> chore: record the scheduling duration in the log

pkg/scheduling/requirements.go, pkg/scheduling/requirements_test.go
Fixes #499  
```make presubmit```
=> perf: Enhanced key matching Labelhints

pkg/operator/logging/logging.go
Fixes #N/A 
This change defaults the log level for the webhook component to `error`
=> chore: Default log level for webhook component

pkg/cloudprovider/fake/cloudprovider.go, pkg/controllers/deprovisioning/emptymachineconsolidation.go, pkg/controllers/deprovisioning/helpers.go, pkg/controllers/deprovisioning/machine_consolidation_test.go, pkg/controllers/deprovisioning/nodeclaim_consolidation_test.go, pkg/controllers/deprovisioning/validation.go, pkg/controllers/nodepool/counter/nodepool_test.go, pkg/controllers/nodepool/counter/provisioner_test.go, pkg/controllers/nodepool/counter/suite_test.go, pkg/controllers/provisioning/provisioner.go, pkg/controllers/provisioning/scheduling/nodepool_topology_test.go, pkg/controllers/provisioning/scheduling/provisioner_topology_test.go, pkg/controllers/provisioning/scheduling/scheduler.go, pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go, pkg/utils/nodepool/nodepool.go, pkg/utils/nodepool/suite_test.go, pkg/utils/provisioner/suite_test.go
Fixes #N/A 
This PR takes in cherry-picked changes for the `v0.31.1` release
=> release: Patch `v0.31.x` release for `v0.31.1`

Makefile, hack/validation/kubelet.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/nodeclaim.go, pkg/apis/v1beta1/nodeclaim_validation_test.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go, pkg/apis/v1beta1/nodepool_validation_webhook_test.go
=> feat: CEL Validation for NodeClaim Kubelet

pkg/test/expectations/expectations.go
Fixes #N/A 
Adds in check for bindings for node claims
make presubmit
=> test: fix bindings expectation

pkg/controllers/disruption/metrics.go
Fixes #N/A 
This PR updates the description metric descriptions to be inline with their naming and labels
=> chore: Update the disruption metric descriptions

pkg/controllers/nodeclaim/lifecycle/initialization.go
Fixes #N/A 
Initialization is the last stage of machine/node claim creation. It should be at info level, since `created` and `registered` are also at that level.
make presubmit
=> chore: change log level of initialization

Makefile, hack/validation/taint.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/nodepool_validation.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go, pkg/controllers/nodeclaim/disruption/nodeclaim_drift_test.go, pkg/controllers/provisioning/provisioner.go
=> feat: CEL Validation for NodeClaim Taints

pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go
Fixes #N/A 
This PR adds a change that causes nodes that we are watching not to be reconciled into the state until the node has its providerID and has the instance type label applied to it. This function will pass-through still if the instance type label doesn't exist but the node is considered to be initialized with the `karpenter.sh/initialized` label.
`make apply`/`make e2etests`
=> chore: Wait for instance type label to exist for managed nodes

Makefile, hack/validation/requirements.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/labels.go, pkg/apis/v1beta1/nodeclaim.go, pkg/apis/v1beta1/nodepool_validation.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go
=> feat: CEL Validation for NodeClaim Requirement 

Makefile, hack/validation/labels.sh, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/nodeclaim_validation.go, pkg/apis/v1beta1/nodepool_validation.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go
=> feat: CEL Validation for `NodePool.Spec.Template` Labels

pkg/test/nodepool.go
Fixes #N/A 
Add a test function that allows node requirement replacement on keys
=> test: Add a test function that allows node requirement replacement on keys

.github/workflows/presubmit.yaml, go.mod, go.sum, pkg/controllers/deprovisioning/suite_test.go, pkg/controllers/state/cluster.go, pkg/controllers/state/statenode.go, pkg/controllers/state/suite_test.go, pkg/utils/nodeclaim/nodeclaim.go
Fixes #N/A 
This PR patches in the #604 PR for `v0.31.2`
=> chore: Patch in changes for `v0.31.2`

go.mod
Fixes #N/A 
Retracts the v0.27.7 release. It was accidentally created without patching all of the known vulnerabilities. 
N/A
=> chore: retract v0.27.7 release

pkg/apis/v1beta1/nodepool_validation_cel_test.go
Fixes #N/A 
Adds testing for CEL for budgets
=> chore: add suite tests for budgets

pkg/utils/nodeclaim/nodeclaim.go, pkg/utils/nodepool/nodepool.go, pkg/utils/nodepool/suite_test.go
Fixes #N/A 
Removes provisioner conversion utils
make presubmit
update core on aws/karpenter and make presubmit
=> chore: remove provisioner utils

NOTICE
Fixes #N/A 
Update NOTICE file to add new contributor and remove njtran
=> chore: Update NOTICE file to add new contributor and remove njtran

OWNERS_ALIASES
Fixes #N/A 
Update owner alias for ellistarn
=> chore: Update owner alias for ellistarn

.openvex/templates/README.md, .openvex/templates/main.openvex.json
Fixes #N/A 
This PR is created to ensure the project has a VEX feed under the `Cloud Native Security Slam`
This PR initialize the VEX feed
=> feat: Initialize the VEX feed

SECURITY-INSIGHTS.yml
Fixes #877
This PR fixes #877
Related to `Kubernetes Security Slam`  task- 11 and 12.2, mentioned here in the [doc](https://docs.google.com/document/d/1TLahqW6OpWQXbaVJ-SR8z-o0yLSoGKYTHxPU0PyyjXo/edit?pli=1#heading=h.p9rkzz6519c8)
=> docs: SECURITY-INSIGHTS.yml Configuration

README.md
Fixes #835
Updates meeting link to community owned zoom link.
Tested ability to join zoom link and claim host via previously shared host key.
=> docs: Update meeting link to Community Owned Zoom

SECURITY-INSIGHTS.yml
Fixes #
Due to this typo the `CLO MONITOR` test is giving warnings for `Dependencies policy` and `Security insights` under security check.
This PR will fix that to pass those checks successfully.
https://clomonitor.io/projects/cncf/karpenter#karpenter_security
=> fix: typo in 'SECURITY-INSIGHTS.YML' file

SECURITY-INSIGHTS.yml
Relates to `Task-12 Security Slam`
Currently, Dependencies Policy test is failing due to this. Although i am not familiar what will be the `policy-url` for this.
Example - https://github.com/argoproj/argo-cd/blob/master/SECURITY-INSIGHTS.yml#L127-L128
// @jonathan-innis  
https://clomonitor.io/projects/cncf/karpenter#karpenter_security
=> Dependencies Policy

pkg/controllers/disruption/helpers.go, pkg/controllers/disruption/suite_test.go
Fixes #N/A 
When Karpenter replaces nodes within disruption, Karpenter previously considered nodes that weren't deleting, which meant that nodes that were launching or registering were also counting towards the total. This means while processing another command, a NodePool's allowed disruptions could change when using percentage based budgets. We should only be using the nodes that Karpenter considers healthy when determining whether a budget threshold will be reached. 
make presubmit
=> fix: only include initialized towards the budget total

hack/toolchain.sh
Fixes #N/A 
This drops unneeded packages that aren't actually used in this repo that were copied over from `aws/karpenter-provider-aws`
`make toolchain`
=> chore: Remove unneeded packages from toolchain

pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go
Fixes #N/A 
This solves a data race problem that we had in our cluster state `Synced()` call when we were access map data without holding the mutex
`make test` (which calls `go test` with the `-race` parameter)
=> fix: Fix data race in cluster state

pkg/test/pods.go
Fixes #N/A 
Add readiness and liveness probe options to the `test.Pods()` function
=> test: Add readiness and liveness pod options

.github/workflows/presubmit.yaml, hack/toolchain.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/test/environment.go
Fixes #N/A 
Adds K8s 1.29 to the version matrix for CI.
N/A
=> ci: run test suite for K8s 1.29

hack/toolchain.sh, pkg/controllers/provisioning/scheduling/topology.go, pkg/controllers/provisioning/scheduling/topologygroup.go, pkg/utils/pretty/pretty.go
Fixes #N/A 
- Adding in cherry picked commits to the v0.32.x release branch
- N/A
=> chore: Adding cherry picked commits to `release-v0.32.x`

hack/validation/kwok-requirements.sh
Fixes #968  
Fixes an error with the validation script where the wrong labels were validated, preventing kwok from working
make apply and manually test
=> fix: fix kwok requirements cel

README.md
Fixes #N/A 
Fixes the zoom meeting time to say 14:00 instead of 15:00
=> docs: Fix zoom meeting time to be correct

pkg/test/pods.go
Fixes #N/A 
add command and prestop into test pod options
make verify
=> test: add command and prestop into test pod options

go.mod, pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Fixes #N/A 
Updates the benchmark to have anti-affinity pods.
=> update benchmark to have anti-affinity pods

hack/toolchain.sh, pkg/controllers/provisioning/scheduling/topology.go, pkg/controllers/provisioning/scheduling/topologygroup.go, pkg/utils/pretty/pretty.go
Fixes #N/A 
Adding in cherry picked commits to the v0.33.x release branch
- https://github.com/kubernetes-sigs/karpenter/pull/959
- https://github.com/kubernetes-sigs/karpenter/pull/958
=> chore: Adding cherry picked commits to release-v0.33.x

pkg/test/expectations/expectations.go
Fixes #N/A 
Adds a missed `Should(Succeed())` to `EventuallyExpectTerminating`
=> test: Add Should(Succeed()) to EventuallyExpectTerminating

pkg/utils/pod/scheduling.go
Fixes #N/A 
Adds a comment to describe in more detail why Karpenter evaluates the FailedToSchedule condition and the impact of this choice on other schedulers that Karpenter might interact with
=> chore: Add note on how Karpenter responds to Unschedulable

pkg/controllers/state/cluster.go
Fixes #N/A 
Ensure that we return the right value for `cluster_state_synced` even if the function exits early
=> fix: Ensure that cluster_state_synced metric gets set if function exits early

go.mod, go.sum, kwok/main.go, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/nodepool.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go, pkg/apis/v1beta1/nodepool_validation_webhook_test.go, pkg/controllers/controllers.go, pkg/controllers/disruption/consolidation.go, pkg/controllers/disruption/consolidation_test.go, pkg/controllers/disruption/orchestration/suite_test.go, pkg/controllers/disruption/suite_test.go, pkg/controllers/node/termination/suite_test.go, pkg/controllers/node/termination/terminator/eviction.go, pkg/controllers/node/termination/terminator/suite_test.go, pkg/controllers/provisioning/provisioner.go, pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go, pkg/controllers/provisioning/scheduling/suite_test.go, pkg/controllers/provisioning/scheduling/topology.go, pkg/controllers/provisioning/scheduling/topologygroup.go, pkg/controllers/provisioning/suite_test.go, pkg/scheduling/requirements.go, pkg/scheduling/requirements_test.go, pkg/utils/resources/resources.go
Fixes #N/A 
- https://github.com/kubernetes-sigs/karpenter/pull/998
- https://github.com/kubernetes-sigs/karpenter/pull/1006
- https://github.com/kubernetes-sigs/karpenter/pull/982
- https://github.com/kubernetes-sigs/karpenter/pull/1012
- https://github.com/kubernetes-sigs/karpenter/pull/1010
- https://github.com/kubernetes-sigs/karpenter/pull/1017
N/A
=> chore: Adding cherry picked commits to release-v0.34.x

pkg/controllers/disruption/controller.go
Fixes #N/A 
Missed a %s on the string print
make verify
=> fix: add missing print directive

pkg/controllers/node/termination/machine_test.go, pkg/controllers/node/termination/nodeclaim_test.go, pkg/controllers/node/termination/suite_test.go, pkg/controllers/node/termination/terminator/eviction.go, pkg/controllers/node/termination/terminator/suite_test.go
=> chore: Patch in race condition for eviction queue fixes to v0.32.x

pkg/controllers/node/termination/suite_test.go, pkg/controllers/node/termination/terminator/eviction.go, pkg/controllers/node/termination/terminator/suite_test.go
=> chore: Patch in race condition for eviction queue fixes to v0.33.x

pkg/scheduling/volumeusage.go
Fixes #N/A 
This PR addresses a performance issue brought forward [here](https://github.com/aws/karpenter-provider-aws/issues/5505). Based on the provided profile image in this [comment](https://github.com/aws/karpenter-provider-aws/issues/5505#issuecomment-1944034348) we can see that `GetVolumes` is using a disproportional amount of CPU time (204 / 586 seconds). 
The culprit line:
```
ctx = logging.WithLogger(ctx, logging.FromContext(ctx).With("pod", pod.Name))
```
At most scales this is negligible, however, for each scheduling loop this new logger with be injected `n*p` times, where `n` is the number of existing nodes on the cluster and `p` is the number of pods being considered in a given scheduling loop. Deferring the `With` calls to the log site rather than injecting …
=> perf: don't inject new loggers in GetVolumes

pkg/apis/v1beta1/nodepool.go, pkg/apis/v1beta1/nodepool_budgets_test.go
Fixes #N/A 
Cherry-pick commit into v0.34
https://github.com/kubernetes-sigs/karpenter/pull/1063
N/A
=> chore: cherry pick commit (#1063)

pkg/apis/v1beta1/nodepool.go, pkg/apis/v1beta1/nodepool_budgets_test.go
Fixes #N/A 
Cherrypicks a change for v0.35.x patch release
make presubmit
=> cherrypick: fix: add hardcoded utc prefix to crontab (#1063)

pkg/controllers/disruption/suite_test.go, pkg/controllers/provisioning/scheduling/volumetopology.go, pkg/controllers/provisioning/suite_test.go, pkg/test/statefulsets.go, pkg/test/storage.go
Fixes #N/A 
Cherry-picks over #1018 into the v0.33.x release branch
=> feat: Drop the hostname requirement when handling PV topology for release-v0.33.x (#1018)

pkg/controllers/disruption/suite_test.go, pkg/controllers/provisioning/scheduling/volumetopology.go, pkg/controllers/provisioning/suite_test.go, pkg/test/storage.go
Fixes #N/A 
Cherry-picks over #1018 into the v0.34.x release branch
=> feat: Drop the hostname requirement when handling PV topology for release-v0.34.x (#1018)

pkg/controllers/disruption/suite_test.go, pkg/controllers/provisioning/scheduling/volumetopology.go, pkg/controllers/provisioning/suite_test.go, pkg/test/storage.go
Fixes #N/A 
Cherry-picks over #1018 into the v0.35.x release branch
=> feat: Drop the hostname requirement when handling PV topology for release-v0.35.x (#1018)

hack/toolchain.sh, pkg/controllers/disruption/suite_test.go, pkg/controllers/provisioning/nodepool_test.go, pkg/controllers/provisioning/provisioner_test.go, pkg/controllers/provisioning/scheduling/volumetopology.go, pkg/test/statefulsets.go, pkg/test/storage.go
Fixes #N/A 
Cherry-picks over #1018 into the v0.32.x release branch
=> feat: Drop the hostname requirement when handling PV topology for release-v0.32.x (#1018)

go.mod
Fixes #N/A 
Bumps go version to 1.22.
=> deps: bump to go 1.22

pkg/controllers/nodeclaim/termination/controller.go
Fixes #N/A 
`Update()` operations to the finalizer allow us to avoid the errors that were mentioned in #1086 around strategic merge patching. This is the better alternative compared to `Patch()`, since it allows us to do optimistic locking and avoid spurious errors in Karpenter for adding finalizers due to list replacement on JSON merge patching. `removing termination finalizer, NodeClaim.karpenter.sh \"slothboulder-2-etpuq1of8e-bnllc\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"foregroundDeletion\"}"}`
=> chore: Remove finalizer with `Update()` instead of `Patch()`

pkg/controllers/disruption/multinodeconsolidation.go
Fixes #N/A 
I know these PRs are silly, just saw it as i was breaking down multi-node consolidation and figured I would fix it.
it wasn't
=> chore: nit spelling fix

.github/workflows/release.yaml
Fixes #N/A 
- Bump version of tejolote for the release GitHub actions for v0.35.x
- N/A
=> chore: Bump tejolote for v0.34.x

.github/workflows/release.yaml
Fixes #N/A 
- Bump version of tejolote for the release GitHub actions for v0.35.x
- N/A
=> chore: Bump tejolote For v0.35.x

pkg/cloudprovider/types.go
Fixes #N/A 
We may want to ignore retryable error in certain scenarios. Added a method for that in the PR.
=> chore: Add method to ignore Retryable error

pkg/test/environment.go
Fixes #N/A 
Retry retrieving the default namespace until it gets propagated into etcd and in the cache. This should reduce flakiness called out in https://github.com/kubernetes-sigs/karpenter/issues/887 until controller-runtime v0.18.0 is available for use.
=> chore: Retry retrieving default namespace to reduce flakiness

pkg/controllers/disruption/consolidation_test.go, pkg/controllers/disruption/emptynodeconsolidation.go, pkg/controllers/disruption/multinodeconsolidation.go, pkg/controllers/disruption/singlenodeconsolidation.go, pkg/controllers/disruption/validation.go
Fixes #N/A 
Cherry picks #1180.
`karpenter snapshot` run in the AWS provider (TODO)
=> cherry-pick: address disruption taint race condition (#1180)

README.md
**Description**: Changed wording related to Karpenter cloud implementations based on discussions in [PR #45802](https://github.com/kubernetes/website/pull/45802/files#r1598686549). Feel free to suggest alternates ways of wording this.
=> Changed wording for Karpenter implementations

pkg/apis/v1beta1/nodeclaim_validation.go, pkg/apis/v1beta1/nodeclaim_validation_cel_test.go, pkg/apis/v1beta1/nodeclaim_validation_webhook_test.go, pkg/apis/v1beta1/nodepool.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go, pkg/apis/v1beta1/nodepool_validation_webhook_test.go, pkg/controllers/disruption/consolidation_test.go, pkg/controllers/disruption/drift_test.go, pkg/controllers/disruption/expiration_test.go, pkg/controllers/disruption/suite_test.go, pkg/controllers/node/termination/suite_test.go, pkg/controllers/nodeclaim/disruption/drift_test.go, pkg/controllers/nodeclaim/disruption/emptiness_test.go, pkg/controllers/nodepool/hash/suite_test.go, pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go, pkg/controllers/provisioning/scheduling/preferences.go, pkg/controllers/provisioning/scheduling/suite_test.go, pkg/controllers/provisioning/suite_test.go, pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go, pkg/test/deployment.go, pkg/test/expectations/expectations.go, pkg/test/statefulsets.go, pkg/test/storage.go, pkg/utils/nodeclaim/nodeclaim.go
Fixes #N/A 
This just changes the knative pkg/ptr to use lo.ToPtr and lo.FromPtr
make presubmit here
=> chore: change knative ptr to lo ptr

go.mod
Fixes #N/A 
1.22.4 was just released, including some CVE patches
make verify
=> chore: update go to 1.22.4

pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/types.go, pkg/controllers/disruption/consolidation.go, pkg/controllers/disruption/multinodeconsolidation.go, pkg/controllers/provisioning/scheduling/instance_selection_test.go, pkg/controllers/provisioning/scheduling/nodeclaim.go
Fixes #N/A 
Remove `Get()` in the offerings call in favor of `Compatible()`
=> chore: Remove `Get()` in offerings in favor of `Compatible()`

pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/types.go, pkg/scheduling/requirements.go
Fixes #N/A 
Helper to simplify some upcoming requirements changes.
=> chore: Add IsCompatible

kwok/main.go, pkg/controllers/controllers.go
=> chore: encapsulate state.Cluster inside of NewControllers

pkg/controllers/provisioning/suite_test.go
Fixes #N/A 
The native sidecar container testing was sitting in the wrong Context block (it was in the DaemonSet block). This moves it out into the generally testing set since it's validating more fundamental scheduling behavior
=> chore: Move native sidecar container testing out of DaemonSet Context

go.mod
Fixes #N/A 
Addresses vulnerability in https://pkg.go.dev/vuln/GO-2024-2963
=> chore: address GO-2024-2963

pkg/apis/v1/nodepool.go, pkg/apis/v1/nodepool_validation_webhook_test.go
Fixes #N/A 
Removes dependency on knative ptrs
=> chore: remove knative ptr

hack/install-kwok.sh, kwok/charts/templates/clusterrole.yaml, kwok/cloudprovider/cloudprovider.go, pkg/controllers/nodepool/validation/controller.go, pkg/controllers/nodepool/validation/suite_test.go
Fixes #N/A 
Patches in some changes to fix the kwok controller based on some other previously made commits
make install-kwok && make apply
=> chore: fix kwok for previous changes

kwok/charts/templates/clusterrole.yaml, kwok/charts/templates/role.yaml, test/suites/perf/scheduling_test.go
Fixes #N/A 
permissions were added for conversion webhooks in downstream PR, but not in kwok 
make apply 
=> chore: fix kwok permissions

test/pkg/environment/common/setup.go
Fixes #N/A 
Prints the pods, nodes, nodeclaims, nodepools, and nodeclasses in the cluster when the test fails 
failed tests with make e2etests
=> test: add cluster log dump when test fails

designs/disruption-controls-by-reason.md, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1/nodepool.go, pkg/apis/v1/nodepool_validation_cel_test.go, pkg/apis/v1beta1/nodepool.go, pkg/apis/v1beta1/nodepool_validation_cel_test.go
Fixes #N/A 
Capitalizes the disruption budgets by reason so that they model the status conditions they're linked to. 
make apply
=> chore: capitalize disruption budgets by reason

test/pkg/environment/common/setup.go
=> chore: pretty print cluster on testing

pkg/controllers/leasegarbagecollection/metrics.go, pkg/controllers/leasegarbagecollection/suite_test.go, pkg/controllers/nodeclaim/consistency/metrics.go, pkg/controllers/nodeclaim/disruption/drift_test.go, pkg/controllers/nodeclaim/disruption/emptiness_test.go, pkg/controllers/nodeclaim/expiration/suite_test.go, pkg/metrics/metrics.go
Fixes #N/A 
This PR updates counter metrics to have suffix `_total`
NA
=> chore: Update counter metrics to have suffix _total

designs/v1-roadmap.md
Fixes #N/A 
Add logging config dropping to the v1 RFC
=> chore: Add logging config dropping to the v1 RFC

.github/actions/install-prometheus/action.yaml, hack/install-prometheus.sh
/kind cleanup
Fixes #N/A 
use script to install kube-promethues, to make it easier for people to get started locally karpenter.
=> chore: add script for install kube-prometheus.

hack/validation/status.sh, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Fixes #N/A 
- Move status validation to be on v1beta1 nodeclaims
=> chore: Status validation to be on v1beta1 NodeClaims

pkg/controllers/nodeclaim/consistency/controller.go
Fixes #1498  
Fixes the lack of information on consistency failures
=> fix: fix log line on consistency errors

pkg/controllers/metrics/node/controller.go
Fixes #N/A 
Updated the code so that `karpenter_nodes_total_pod_requests` and `karpenter_nodes_total_pod_limits` will now include daemon set resources.
=> chore: update node pod requests and limits to include daemon set

pkg/controllers/metrics/node/controller.go
Fixes #N/A 
Updated metric description for karpenter_nodes_total_pod_requests and karpenter_nodes_total_pod_limits to include daemonSet pods.
NA
=> chore:Update metrics description

Makefile, hack/validation/status.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Fixes #N/A 
- Add in validation for when controller edit v1 version of the resource
=> chore: Include status validation for v1 NodeClaim in v0.33.x

Makefile, hack/validation/status.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Fixes #N/A 
- Add in validation for when controller edit v1 version of the resource
=> chore: Include status validation for v1 NodeClaim in v0.34.x 

Makefile, hack/validation/status.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Fixes #N/A 
- Add in validation for when controller edit v1 version of the resource
=> chore: Include status validation for v1 NodeClaim in v0.36.x

pkg/controllers/disruption/controller.go
Fixes #N/A 
old log was `disrupting via Drifted`
new log is `disrupting drifted nodeclaims`
make presubmit
=> chore: fix capitalization in disruption log

pkg/controllers/disruption/controller.go, pkg/controllers/disruption/orchestration/queue.go
Fixes #N/A 
Minor fixes to logging for the disruption reason
=> chore: Minor fixes to disruption logging

pkg/apis/v1/nodepool.go, pkg/controllers/disruption/consolidation_test.go, pkg/controllers/disruption/controller.go, pkg/controllers/disruption/drift.go, pkg/controllers/disruption/drift_test.go, pkg/controllers/disruption/emptiness.go, pkg/controllers/disruption/emptiness_test.go, pkg/controllers/disruption/multinodeconsolidation.go, pkg/controllers/disruption/singlenodeconsolidation.go, pkg/controllers/disruption/suite_test.go
Fixes #N/A 
Disruption reason casing is still wrong for prometheus and for logging
=> chore: Fix disruption reason casing

pkg/apis/v1/labels.go, pkg/apis/v1/nodeclaim_conversion.go, pkg/apis/v1/nodeclaim_conversion_test.go, pkg/apis/v1/nodepool_conversion.go, pkg/apis/v1/nodepool_conversion_test.go
=> chore: Backport conversion webhooks changes for v0.33.x

pkg/apis/v1/labels.go, pkg/apis/v1/nodeclaim_conversion.go, pkg/apis/v1/nodeclaim_conversion_test.go, pkg/apis/v1/nodepool_conversion.go, pkg/apis/v1/nodepool_conversion_test.go
=> chore: Backport conversion webhooks changes for v0.35.x

pkg/apis/v1/labels.go, pkg/apis/v1/nodeclaim_conversion.go, pkg/apis/v1/nodeclaim_conversion_test.go, pkg/apis/v1/nodepool_conversion.go, pkg/apis/v1/nodepool_conversion_test.go
=> chore: Backport conversion webhooks changes for v0.36.x

pkg/apis/v1/labels.go, pkg/apis/v1/nodeclaim_conversion.go, pkg/apis/v1/nodeclaim_conversion_test.go, pkg/apis/v1/nodepool_conversion.go, pkg/apis/v1/nodepool_conversion_test.go
=> chore: Backport conversion webhooks changes for v0.34.x

pkg/controllers/nodeclaim/lifecycle/controller.go
Fixes #N/A 
Backporting: https://github.com/kubernetes-sigs/karpenter/pull/1561
=> chore: Backport (#1561) v37.x

pkg/controllers/nodeclaim/lifecycle/controller.go
Fixes #N/A 
Backporting: https://github.com/kubernetes-sigs/karpenter/pull/1561
=> chore: Backport (#1561) v36.x

pkg/controllers/nodeclaim/lifecycle/controller.go
Fixes #N/A 
Backporting: https://github.com/kubernetes-sigs/karpenter/pull/1561
=> chore: Backport (#1561) v35.x

pkg/controllers/nodeclaim/lifecycle/controller.go
Fixes #N/A 
Backporting: https://github.com/kubernetes-sigs/karpenter/pull/1561
=> chore: Backport (#1561) v33.x

kwok/cloudprovider/cloudprovider.go, pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/types.go
Fixes #N/A 
Add Cloud Provider DisruptionReasons() cloud provider method.
=> feat: add cloud provider disruption reasons

pkg/operator/operator.go
Fixes #N/A 
This check was dropped ahead of v1 in https://github.com/kubernetes-sigs/karpenter/pull/1460
Adding it back.
Manual validation
=> chore: Add readiness check on cache sync

pkg/controllers/metrics/node/controller.go, pkg/controllers/metrics/node/suite_test.go, pkg/controllers/node/termination/controller.go, pkg/controllers/node/termination/metrics.go, pkg/controllers/node/termination/suite_test.go, pkg/utils/resources/resources.go
I'm adding a cluster utilization metric to track the utilization of resources and a couple of node metrics to track the longevity of the nodes.
I added unit tests for the new metrics.
=> chore: added cluster utilization metric and a couple of node lifetime metrics 

kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/controllers/disruption/validation.go, pkg/controllers/nodeclaim/consistency/controller.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml, pkg/webhooks/webhooks.go
=> fix: Fix spurious transport errors (v1.0.x)

go.mod, go.sum
Fixes #N/A 
Bump `github.com/awslabs/operatorpkg` to the latest
=> chore: Bump github.com/awslabs/operatorpkg to latest

kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1/nodepool.go, pkg/apis/v1/nodepool_default_test.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
=> fix: add default disruption stanza (#1662)

pkg/controllers/disruption/controller.go, pkg/controllers/disruption/orchestration/queue.go, pkg/controllers/node/termination/controller.go, pkg/controllers/node/termination/terminator/terminator.go, pkg/controllers/nodeclaim/consistency/controller.go, pkg/controllers/nodeclaim/disruption/controller.go, pkg/controllers/nodeclaim/lifecycle/controller.go, pkg/controllers/nodeclaim/lifecycle/initialization.go, pkg/controllers/nodeclaim/lifecycle/registration.go, pkg/controllers/nodeclaim/podevents/controller.go, pkg/controllers/nodeclaim/termination/controller.go, pkg/controllers/nodeclaim/termination/suite_test.go, pkg/controllers/nodepool/readiness/controller.go, pkg/controllers/nodepool/validation/controller.go, pkg/controllers/state/statenode.go, pkg/scheduling/taints.go, pkg/utils/pretty/pretty.go, pkg/utils/termination/termination.go
…t match (#1658)
Fixes #N/A 
Cherry-pick change from #1658 onto `release-v1.0.x`
=> chore: Cherry pick patch with conflict fix onto `release-v1.0.x`

README.md
Fixes #N/A 
We are working on [Alibaba Cloud](https://www.alibabacloud.com/en?_p_lc=1&utm_key=se_1008118490&utm_content=se_1008118490&gad_source=1&gclid=Cj0KCQjwxsm3BhDrARIsAMtVz6Obl6GuG-96KSfOX8a_TB0UtGFpEqy7Fx0l6UNKq9cOkidoJpZstagaAuPoEALw_wcB) Provider with Alibaba Cloud employees(@ringtail and @IrisIris)
none
=> docs: add Alibaba Cloud repo link

pkg/controllers/migration/crd/controller.go
Fixes #N/A 
Correctly checks for lack of `v1beta1`
Make presubmit
=> fix: migration crd no-op

pkg/controllers/migration/crd/controller.go, pkg/controllers/migration/crd/suite_test.go
Fixes #N/A 
Ensures that we only patch the stored versions on a CRD when the storage version is v1beta1. This prevents an edge-case where a user upgrading from a pre-v1 version, who doesn't have any resources created for a CRD, and who upgraded their controller before their CRDs.
`make test`
=> fix: only patch CRDs when storage version is v1

.github/workflows/kind-e2e.yaml, .github/workflows/presubmit.yaml, hack/toolchain.sh, pkg/test/environment.go
Fixes #N/A 
This drops 1.25 from CI as well.
make presubmit
=> chore: upgrade CI to use 1.31

pkg/controllers/metrics/pod/controller.go, pkg/controllers/metrics/pod/suite_test.go
Fixes #N/A 
Adding pod metrics -
1. current_unbound_time_seconds
2. bound_duration_seconds
3. unstarted_time_seconds
=> chore: Add pod metrics

pkg/controllers/state/statenode.go
Fixes #N/A 
Found disruption code with no references.
`make test` focused on state
=> chore: remove dead disruptable code

pkg/controllers/disruption/suite_test.go, pkg/controllers/state/statenode.go
Fixes #N/A 
Clarify logs that communicate internal Karpenter concepts.
N/A
=> fix: clarify state node logging

kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/controllers/disruption/multinodeconsolidation.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Fixes #N/A 
Cherry-pick #1763 
=> fix: check for nil pointer dereference (#1763)

README.md
Fixes #N/A 
We talk to the cloud provider, alibabacloud is a more accurate name
Do not need this
=> doc: update alibabacloud repo link

pkg/operator/operator.go, pkg/operator/options/options.go, pkg/operator/options/suite_test.go, pkg/test/options.go
Fixes #N/A 
chore: make leader election ID configurable
Unit tests
=> chore: make leader election ID configurable

pkg/cloudprovider/types.go, pkg/controllers/nodeclaim/lifecycle/launch.go, pkg/controllers/nodeclaim/lifecycle/launch_test.go
Fixes #N/A 
Create a new error type that can wrap error message and actual error.
NA
=> chore: create new error type to wrap message and error

pkg/controllers/provisioning/scheduling/scheduler.go
Fixes #N/A 
Convert `karpenter_scheduler_unfinished_work_seconds` to seconds
=> chore: Convert `karpenter_scheduler_unfinished_work_seconds` to seconds

README.md
Fixes #N/A 
update the readme to contain a reference to the cluster-api provider for karpenter.
N/A
=> add cluster-api provider to readme

Makefile, kwok/charts/README.md, kwok/charts/values.yaml
Fixes #N/A 
Update the kwok chart to latest by setting the MetricsPort to the changed port on v1 (8080) and to update the Makefile to use the correct Makefile values
=> chore: Update kwok chart to latest

pkg/controllers/controllers.go
Fixes #N/A 
- Removed a controller that was used for testing.
- The controller is based inside of feature flag and enabled using the flag
- `make apply`
=> chore: Remove a controller that was used for testing

pkg/utils/termination/suite_test.go
Fixes #N/A 
Follow-up test for #1835
`make test`
=> test: ensure NodeClaim root condition reamains known during termination

go.mod, go.sum
Fixes #N/A 
Bump `github.com/awslabs/operatorpkg` to latest
=> chore: Bump `github.com/awslabs/operatorpkg` to latest

README.md
Fixes #N/A 
We’ve just released the Alibaba Cloud provider: [https://github.com/cloudpilot-ai/karpenter-provider-alibabacloud/releases](https://github.com/cloudpilot-ai/karpenter-provider-alibabacloud/releases). Excitingly, some end users are already leveraging this initial version to manage their clusters for Spark Jobs.  
Our next step is to bring this solution to GCP. We’re confident we can improve upon it and deliver the best possible experience to the community users.  
This marks a significant milestone for the Karpenter community—once GCP is supported, Karpenter will extend its reach to the leading three cloud providers: AWS, Azure, and GCP.  
none
By submitting this pull request, I confirm that my contribution is made under the terms …
=> docs: add gcp provider

pkg/controllers/disruption/types.go, pkg/controllers/state/statenode.go
Fixes #N/A 
Updates the conditional check for erroring when creating a disruption candidate to improve readibility.
=> chore: clarify disruption candidate conditional

pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/operator/operator.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml, pkg/webhooks/webhooks.go
Fixes #N/A 
Pulls in changes from #1914 as a cherry-pick
=> fix: Modify conversion webhook check to check for v1 version existence (cherry-pick v0.35.x) 

pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/operator/operator.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml, pkg/webhooks/webhooks.go
Fixes #N/A 
Pulls in changes from #1914 as a cherry-pick
=> fix: Modify conversion webhook check to check for v1 version existence (cherry-pick v0.36.x) 

pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/operator/operator.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml, pkg/webhooks/webhooks.go
Fixes #N/A 
Pulls in changes from #1914 as a cherry-pick
=> fix: Modify conversion webhook check to check for v1 version existence (cherry-pick v0.34.x) 

pkg/controllers/provisioning/scheduling/nodeclaim.go
Fixes #N/A 
This change ensures that we don't create a new slice every time we are evaluating the offerings for an instance type 
```
scheduled 40151 against 8031 nodes in total in 1m0.598067383s 662.578886323755 pods/sec
400 instances 1 pods      1 nodes     181.661µs per scheduling      181.661µs per pod
400 instances 50 pods     10 nodes    43.569498ms per scheduling    871.389µs per pod
400 instances 100 pods    20 nodes    85.327955ms per scheduling    853.279µs per pod
400 instances 500 pods    100 nodes   420.066861ms per scheduling   840.133µs per pod
400 instances 1000 pods   200 nodes   801.483167ms per scheduling   801.483µs per pod
400 instances 1500 pods   300 nodes   1.213672s per scheduling      809.114µs per pod
400 instances …
```
=> perf: Remove `Available()` call inside of filterInstanceTypesByRequirements

go.mod
Fixes #N/A 
Bump go minor version to 1.23.6
N/A
=> chore: Bump go minor version to 1.23.6

pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go
Fixes #N/A 
Fix Daemonset calculation bug that was introduced by #1968
=> chore: Fix daemonset calculation bug

kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Fixes #N/A 
Bump `controller-gen` to the latest version by getting the latest version
=> chore: Bump controller-gen to the latest version

pkg/controllers/provisioning/provisioner.go, pkg/controllers/provisioning/scheduling/suite_test.go, pkg/controllers/provisioning/suite_test.go
Fixes #N/A 
If during one scheduling loop, pod is scheduled to a nodePool but it doesn't get scheduled and is seen in the next scheduling loop and this time there are no valid nodepools in the cluster, clear the scheduling decisions made for this pod.
=> chore: clear pod scheduling decisions if there are no valid nodepools

pkg/controllers/node/health/controller.go
=> chore: fix spelling error in node health log

go.mod
Fixes #N/A 
Bumps go version to 1.24.0
=> deps: bump go to 1.24.0

README.md
Add Proxmox to adopters list.
Fixes #N/A 
I have started working on implementing Karpenter for Proxmox (bare metal solution) and have successfully developed an MVP. Based on this progress, I believe a full implementation is achievable.
I hope this link will help bring the community together to contribute to the project with additional functionality.
We already have integrations:
* Proxmox CCM - https://github.com/sergelogvinov/proxmox-cloud-controller-manager
* Proxmox CSI - https://github.com/sergelogvinov/proxmox-csi-plugin
And finally, to complete the full ecosystem, the node autoscaler:
* Karpenter provider for Proxmox - https://github.com/sergelogvinov/karpenter-provider-proxmox
Thanks. …
=> docs: add proxmox provider

pkg/controllers/provisioning/scheduling/topology.go
We're iterating over Pods to count the topology domains, which requires looking up Nodes and computing the Nodes requirements.  The order that we do this doesn't matter, so we can just sort the Pods by the Node name to minimize the number of times we need to fetch the Node and recompute its requirements.
=> perf: sort Pods by node name to allow re-use of scheduling requirements

go.mod, kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/controllers/nodeclaim/lifecycle/controller.go, pkg/controllers/nodeclaim/lifecycle/events.go, pkg/controllers/nodeclaim/lifecycle/initialization_test.go, pkg/controllers/nodeclaim/lifecycle/registration.go, pkg/controllers/nodeclaim/lifecycle/registration_test.go, pkg/controllers/nodeclaim/lifecycle/suite_test.go, pkg/controllers/nodeclaim/lifecycle/termination_test.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
=> chore: Backport removal registration enforcement 1.2.x

go.mod, kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/controllers/nodeclaim/lifecycle/controller.go, pkg/controllers/nodeclaim/lifecycle/events.go, pkg/controllers/nodeclaim/lifecycle/initialization_test.go, pkg/controllers/nodeclaim/lifecycle/registration.go, pkg/controllers/nodeclaim/lifecycle/registration_test.go, pkg/controllers/nodeclaim/lifecycle/suite_test.go, pkg/controllers/nodeclaim/lifecycle/termination_test.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Fixes #N/A 
Backports https://github.com/kubernetes-sigs/karpenter/pull/1991
make test
=> chore: Backport removal registration enforcement 1.1.x

pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go
Fixes #N/A 
Backports #1957 and #1958
=> test: Fix `ConsolidationState()` test failure in state testing (#1957) 1.2.x

pkg/controllers/state/suite_test.go
Fixes #N/A 
Backport #1958 to v1.0.x release branch
=> chore: Backport #1958 to v1.0.x release branch

pkg/controllers/disruption/controller.go, pkg/controllers/node/termination/terminator/events/events.go, pkg/controllers/node/termination/terminator/eviction.go
Fixes #N/A 
Set disruption reason as the `Reason` field in the `DisruptionReason` condition and don't return error from `evictionReason`
=> chore: Refactor some detials of disruption reason condition

OWNERS_ALIASES
Fixes #N/A 
Removing @jackfrancis from reviewers since he's become less directly involved in maintaining the project
Jack shows as < 10 contributions in the last year: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes-sigs%2Fkarpenter&var-country_name=All
=> chore: Remove jackfrancis from karpenter-reviewers

pkg/test/environment.go
Fixes #N/A 
Adds a field indexer helper for tests for the NodeClassRef on NodePools.
=> test: add nodepool nodeclassref field indexer

go.mod, kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Fixes #N/A 
- Bump go mod version to avoid vulnerability-check 
=> chore: Bump Go mod version

pkg/controllers/disruption/singlenodeconsolidation.go
Fixes #N/A 
Previously, if a candidate for a NodePool was blocked by a budget or was empty, it would be considered "unseen". This change considers those NodePools as seen, and moves the timeout to the top of the candidate loop such that the log is now correct.
Unit tests and in cluster with a NodePool budget set to 0 nodes allowed.
```
spec:
disruption:
budgets:
- nodes: "0"
consolidateAfter: 0s
consolidationPolicy: WhenEmptyOrUnderutilized
```
Before:
> {"level":"DEBUG","time":"2025-04-11T16:28:02.800Z","logger":"controller","caller":"disruption/singlenodeconsolidation.go:145","message":"prioritizing nodepools that have not yet been considered due to timeouts in previous runs: arm-2cpu","commit":"f57f895-dirty","controller":"disruption","nam …
=> fix: consider candidate NodePool seen when blocked by budgets or empty

pkg/controllers/state/suite_test.go
Fixes #N/A 
Add a couple more tests for resource tracking in cluster state. This is a follow-up to https://github.com/kubernetes-sigs/karpenter/pull/2142
=> test: Add more resource tracking cluster state testing

pkg/controllers/metrics/pod/suite_test.go, pkg/controllers/provisioning/provisioner.go, pkg/controllers/provisioning/scheduling/scheduler.go, pkg/controllers/provisioning/suite_test.go, pkg/controllers/state/cluster.go, pkg/controllers/state/suite_test.go
Fixes #N/A 
Store the mapping between the pod and the nodeClaim against which it should schedule.
N/A
=> chore: Update pod schedulable time

test/suites/integration/suite_test.go
Fixes #N/A 
- Apply KWOK requirement to only be applied for KWOK nodes 
=> test: Apply KWOK requirement to only work with KWOK nodeclass

test/suites/integration/chaos_test.go, test/suites/integration/expiration_test.go
Fixes #N/A 
- Update the expiration to disable drift on nodeclaims that are launched after the first nodeclaim. This will ensure that the does contain a race between test validation on and node expiration on the newly provisioned capacity.
- https://github.com/aws/karpenter-provider-aws/actions/runs/14744106366)
- https://github.com/aws/karpenter-provider-aws/actions/runs/14741509367/job/41380396156
=> test: Update E2E tests to disable expiration for new nodes that have expired 

.github/workflows/kind-e2e.yaml
Fixes #N/A 
- Related to a merged PR: https://github.com/kubernetes-sigs/karpenter/pull/2204
- Removing extra unnecessary steps
- `make presubmit
=> ci: Temporarily Disable Karpenter KPI actions 

pkg/controllers/provisioning/scheduling/scheduler.go
Fixes #N/A 
Update the error check to use `context.DeadlineExceeded` instead of `context.Canceled`
=> chore: Fix scheduling timeout error check

test/suites/integration/nodeclaim_test.go
Fixes #N/A 
- `should create a standard NodeClaim based on resource requests`
- Lower memory request for NodeClaim tests 
=> test: Lower resource requests for NodeClaim test

README.md
Fixes #N/A 
Updates the issue triage meeting to monthly as opposed to bi-weekly, as discussed in working group.
=> docs: update issue triage meeting schedule

test/pkg/environment/common/expectations.go, test/suites/regression/nodeclaim_test.go
=> test: add validating admission policy for nodeclass status

pkg/controllers/node/termination/controller.go, pkg/controllers/node/termination/suite_test.go
Fixes #N/A 
Updates the node termination controller to fail open rather than closed when a NodeClaim can not be found for the node. This is an invariant that shouldn't be broken, but discovered that it's currently possible if the node joins the cluster in time for the same reconciliation of the lifecycle controller to perform launch and registration **and** it fails to persist the provider-id to the NodeClaim's status. This likely will never happen in a real cloudprovider, but does occur in KWOK simulation testing. 
=> fix: fail open for missing nodeclaims in termination

Makefile, hack/install-kwok.sh
Fixes #N/A 
Fix our `./install-kwok.sh` script so that it works with multiple partitions again
`make install-kwok`
=> chore: Ensure we can stand up multiple partitions with kwok

hack/install-kwok.sh
Fixes #N/A 
Inject KWOK resource requests into the pod through a Kustomize patch
`make install-kwok`
=> chore: Inject resources into Kwok through a patch

pkg/controllers/node/termination/controller.go
Fixes #N/A 
This change ensures that we don't override the `err` that's returned from any of the `terminationFuncs` when we make a patch call. Currently, if the Patch call doesn't return an error, we can completely ignore an error that actually came from the CloudProvider
=> fix: Fix overriding error with patch call

pkg/controllers/node/termination/suite_test.go
Fixes #N/A 
- Since we are not able to sync the fake clock with kubectl.Delete, there is always a chance we may see a bigger difference in the timestamp we expect vs what is defined on the pod
=> test: Bump the termination time for the deletion timestamp

pkg/controllers/disruption/consolidation_test.go, pkg/controllers/disruption/controller.go, pkg/controllers/disruption/emptiness.go, pkg/controllers/disruption/emptiness_test.go, pkg/controllers/disruption/multinodeconsolidation.go, pkg/controllers/disruption/singlenodeconsolidation.go, pkg/controllers/disruption/singlenodeconsolidation_test.go, pkg/controllers/disruption/suite_test.go, pkg/controllers/disruption/types.go, pkg/controllers/disruption/validation_test.go
Fixes #N/A 
#2369 merged before @jmdeal had a chance to look at the changes -- this PR addresses code style comments from him
=> refactor: Update disruption testing from PR comments

README.md
Fixes #N/A 
added IBM Cloud provider to the list of Karpenter implementations in the README.md
N/A docs only
=> docs: Add IBM Cloud provider

pkg/operator/options/options.go, pkg/operator/options/suite_test.go, pkg/test/options.go
Added StaticCapacity feature flag for #2309 
Fixes #N/A 
Ran make presubmit
=> feat: Add StaticCapacity feature flag

go.mod
Fixes #N/A 
Address CVE: https://github.com/advisories/GHSA-j5pm-7495-qmr3
make presubmit
=> chore: bump go version to 1.24.6

kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml, kwok/charts/crds/karpenter.sh_nodeclaims.yaml, kwok/charts/crds/karpenter.sh_nodepools.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/cloudprovider/fake/cloudprovider.go, pkg/cloudprovider/types.go, pkg/controllers/nodeclaim/disruption/drift.go, pkg/controllers/nodeclaim/disruption/drift_test.go, pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Fixes #N/A 
Cherry-picks #2476
=> fix: support arbitrary reserved capacity labels for drift

pkg/controllers/provisioning/scheduling/topology_test.go, pkg/controllers/provisioning/scheduling/topologygroup.go
Fixes #N/A 
Cherry picks #2511 
=> fix: handle nil selector when hashing in topology

OWNERS_ALIASES
Fixes #N/A 
Backports @jmdeal's approver status to the v1.1.x branch
=> chore: backport jmdeal approver status to v1.1.x

OWNERS_ALIASES
=> chore: backport jmdeal approver status to v1.0.x

OWNERS_ALIASES
=> chore: backport jmdeal approver status to v1.2.x

OWNERS_ALIASES
=> chore: backport jmdeal approver status to v1.3.x
